### ISSUE TITLE
Utrekk inntekt der siste måned er 0 (https://jira.adeo.no/browse/ARENA-6684)

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#1012]
Ref https://jira.adeo.no/browse/ARENA-6684

- [x] Basert på en [liste av inntektsider](https://github.com/navikt/dagpenger/files/7743294/inntektsID.txt), lag et uttrekk der siste månedsinntekt er 0 
- [x]  [Basert på alle inntekter](https://github.com/navikt/dagpenger/files/7820908/Inntekt-uttrekk-22.12.2021.xlsx) der siste månedsinntekt er 0, gjør en spørring mot inntektskomponenten/skatt og hent inntekt, sjekk om siste inntektsmåned er 0
- [x] Nytt uttrekk fra excel ark xx (avslag?) 

[inntektsID.txt](https://github.com/navikt/dagpenger/files/7743294/inntektsID.txt)

**Comment by geiralund** [comment]
~Fant bare disse:
Tom arbeids inntekt maaned 01DP8G798K6RHW42XCDHQRB706
Tom arbeids inntekt maaned 01DP8DWGXVH2HKFW0BJM4WN9TF
Tom arbeids inntekt maaned 01DPARVSWZPWB1M711VQD07PNQ
Tom arbeids inntekt maaned 01DXJNSNDCV1Y7E273DNKK8NAY
Tom inntektList 01ERPHTNPSPJAKZ3Y8ZMNN0J6D~

Det over er feil, se vedlegg

**Comment by geiralund** [comment]
[Inntekt-uttrekk-22.12.2021.xlsx](https://github.com/navikt/dagpenger/files/7820908/Inntekt-uttrekk-22.12.2021.xlsx)

**Comment by gtcno** [comment]
[inntekt.csv](https://github.com/navikt/dagpenger/files/7837290/inntekt.csv)
[inntekt2.csv](https://github.com/navikt/dagpenger/files/7837293/inntekt2.csv)
[mangler_inntekt.csv](https://github.com/navikt/dagpenger/files/7837295/mangler_inntekt.csv)


inntekt.csv - Kjøring av alle inntekst id 
inntekt2.csv - Alle inntekstid med merknad fra enten vårt datagrunnlag eller skatt. Dvs fjernet inntekst id der det ikke finnes merknad fra vårt grunnlag eller skatt.

**Comment by gtcno** [comment]
[inntekt.csv](https://github.com/navikt/dagpenger/files/7855885/inntekt.csv)
[mangler_inntekt.csv](https://github.com/navikt/dagpenger/files/7855886/mangler_inntekt.csv)
@geiralund

**Comment by geiralund** [comment]
Siste uttrekk for innvilgende vedtak: 

Her med merknad fra skatt sammenlignet med det som er registrert i inntektdatabasen til digidag.
Det er forskjellige kombinasjoner og det er de diverger er interessante.
feks inntektid 01F75W5D1XZ96S30S1P81GRKDF der vi har ikke har med siste månedsinntekt.
`Siste avsluttende kalendermåned er 2021-05, registrert inntekt fra 2021-04`
 og skatt melder
`Siste inntektsmåned er ikke 0, registrert inntekt fra 2021-05`


[Inntekt_uttrekk_merknad_skatt13.01.2022.xlsx](https://github.com/navikt/dagpenger/files/7868584/Inntekt_uttrekk_merknad_skatt13.01.2022.xlsx)

**Comment by geiralund** [comment]
Ny rapport klar. (For innvilgelse)
Det er to type sjekker i denne;
Sjekk om inntektsmåned er samme for digidag og skatt, hvis ikke
`Skatt har registrert inntekt på senere tidspunktRegistrert i DigiDag 2019-10 Sum : XXX	Registrert i skatt 2019-11 Sum : XXXX`
Om  inntektsmåned er samme for digidag og skatt, MEN summen diverger:
`Inntekt fra samme måned er ulikRegistrert i DigiDag 2019-10 Sum : 974.44	Registrert i skatt 2019-10 Sum : 1101.99`

[Inntekt_uttrekk_merknad_skatt13.01.2022.xlsx](https://github.com/navikt/dagpenger/files/7903921/Inntekt_uttrekk_merknad_skatt13.01.2022.xlsx)

**Comment by geiralund** [comment]
Ny rapport (for de som ikke har fått innvilgelse)

[Inntekt-merknad-skatt-20.01.2021.xlsx](https://github.com/navikt/dagpenger/files/7906841/Inntekt-merknad-skatt-20.01.2021.xlsx)

**Comment by geiralund** [comment]
DOne
