### ISSUE TITLE
Registreringsløsning nede 21. desember 2021 klokken 2300 til 2330 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#1015]
![image](https://user-images.githubusercontent.com/82581338/146934826-f44d68fe-4ede-48fa-a7a2-b88c62404788.png)

Listen kan legges her og si ifra til meg når klar: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7Beb69bad7-fb19-45c5-98a0-cac249a925a1%7D&action=editnew

**Comment by geiralund** [comment]
@Eivind833 Har lagt til kandidater i excel arket

**Comment by EivindRoyrvik** [comment]
Gjennomgått listen, alt ok.
