### ISSUE TITLE
Registreringsløsningen nede 30. desember 2021 kl. 2330 til 0300 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#1018]
![image](https://user-images.githubusercontent.com/82581338/147909703-f55cc2b1-77cf-49c6-8860-6bd845fde32e.png)

Listen kan legges her og si ifra til meg når klar: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7B4acc197d-ba76-43f0-b7ad-f5cbe3d5e93a%7D&action=editnew

**Comment by geiralund** [comment]
@Eivind833 Gjorde spørring og fant ingen som søkte i det tidsrommet, altså 0 stk

**Comment by EivindRoyrvik** [comment]
Den er god, lukker denne.
