### ISSUE TITLE
Registreringsløsningen nede 26. januar 2022 kl. 2300 - 0300 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#1021]
https://nav-it.slack.com/archives/CEE8ZNS81/p1643189138054300

![image](https://user-images.githubusercontent.com/82581338/151138060-1198de26-9b12-4508-8659-27a78904cfa1.png)

Listen kan legges her og si ifra til meg når klar: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7B47827726-aeec-424a-b031-53a5a097c34d%7D&action=editnew

**Comment by geiralund** [comment]
@Eivind833 Lagt til 17 stk

**Comment by EivindRoyrvik** [comment]
Gjennomgått listen, ok.
