### ISSUE TITLE
Registeringsløsningen nede 23. februar 2022 kl. 2300 til 2330 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#1026]
https://nav-it.slack.com/archives/CEE8ZNS81/p1645618199452879
![image](https://user-images.githubusercontent.com/82581338/155337847-81369146-510c-4dc9-9609-5a242ff412ea.png)

Listen kan legges her og si ifra til meg når klar: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7Bc8d4844a-2b39-4e40-a5e1-e5c207dfea08%7D&action=editnew

**Comment by geiralund** [comment]
Lagt til to kandidater @Eivind833

**Comment by EivindRoyrvik** [comment]
Gjennomgått, ok.
