### ISSUE TITLE
Registreringsløsningen nede 4. mars 2022 kl. 2300 til 2359 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#1027]
https://nav-it.slack.com/archives/CEE8ZNS81/p1646393288506709

![image](https://user-images.githubusercontent.com/82581338/156770497-ce0b4465-624c-43d5-bffe-59af4313ca60.png)

Listen kan legges her og kan si ifra til meg når klar: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7B13112593-531e-4149-bf3b-b9f6065d4fdf%7D&action=editnew

**Comment by geiralund** [comment]
Lagt til 2 kandidater @Eivind833

**Comment by EivindRoyrvik** [comment]
Gjennomgått, ok.
