### ISSUE TITLE
Registreringsløsningen nede 9. mars 2022 kl. 2300 til 0300 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#1028]
https://nav-it.slack.com/archives/CEE8ZNS81/p1646816866817009

Kan legge listen her og si ifra til meg når klar: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7B99a998aa-9f0d-449e-8612-ceee213a0239%7D&action=editnew

**Comment by celinetendam** [comment]
@Eivind833  Denne er klar

**Comment by EivindRoyrvik** [comment]
OK
