### ISSUE TITLE
Registreringsløsningen nede 7. april 2022 kl. 2300 til 0400 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#1030]
https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7B17fa8bc2-9b84-4603-b57f-359afa536f3f%7D&action=editnew
![image](https://user-images.githubusercontent.com/82581338/162436202-266d3fc5-9106-495a-8c06-017765dd1e4d.png)

Listen kan legges her og si ifra til meg når klar: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7B17fa8bc2-9b84-4603-b57f-359afa536f3f%7D&action=editnew

**Comment by celinetendam** [comment]
@Eivind833 Denne er klar

**Comment by EivindRoyrvik** [comment]
OK
