### ISSUE TITLE
Golden Gate

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#119]
Kort beskrivelse
DigiDag har behov for å få informasjon fra Arena når et dagpengevedtak iverksettes av beslutter eller avbrytes av saksbehandler. Tilsvarende er det behov for å få informasjon fra Arena når et tilbakebetalingsvedtak iverksettes av beslutter eller avbrytes av saksbehandler, dersom tilbakebetalignsvedtaket er knyttet mot ett eller flere kontrollvedtak med dagpengerettighet. Dette for at DigiDag kan sørge for konsistens med Arena, samt slette inntekter som ikke har ligget til grunn for vedtaket.

Forutsetninger og avgrensninger 
Løsningen forutsetter at DigiDag benytter GoldenGate for å fange hendelser på ny tabell FERDIGSTILTE_DAGPENGEVEDTAK.

Sjekk løsningsbeskrivelse fra Arena: 
https://confluence.adeo.no/pages/viewpage.action?pageId=320036698

**Comment by geiralund** [comment]
Må sette igang bestilling av GC 
https://jira.adeo.no/plugins/servlet/desk/portal/542/IKT-20414
