### ISSUE TITLE
Fikse grunnbeløp: for de ulike reglene

### ISSUE THREAD

**Issue by tonjemjovik** [navikt/dagpenger#130]
Dette er hjemlet i ftrl. § 1-4 siste ledd og forskrift av 24.05.2019 nr 670 om grunnbeløp, reguleringsfaktorer … etc.
 
I forskriftens § 6 står det følgende: «Virkningstidspunktet for regulering av kravet til minsteinntekt for rett til ytelser etter folketrygdloven kapitlene 4, 8, 9 og 14 settes til 27. mai 2019.»
 
Altså er virkningstidspunktet avgjørende, dvs. det tidspunktet det innvilges dagpenger i fra.
 
Vi får da:
-          Nytt krav til minsteinntekt (inkl. § 4-15): Gjelder for dagpengevedtak (ny rettighet) med fra-dato 27.5.19 eller senere.
-          Gammelt krav til minsteinntekt (inkl. § 4-15): Gjelder for dagpengevedtak (ny rettighet) med fra-dato tidligere enn 27.5.19.

**Comment by androa** [comment]
Levert med:

navikt/dp-biblioteker#8
navikt/dp-regel-grunnlag#27
navikt/dp-regel-minsteinntekt#22
navikt/dp-regel-periode#18
