### ISSUE TITLE
Måle bruk av nytt GUI

### ISSUE THREAD

**Issue by elinkarlsen** [navikt/dagpenger#137]
Det er ønskelig at vi setter opp noen målinger på saksbehandlers bruk av nytt GUI

Hvor ofte korrigeres inntekter 
hvor ofte innhentes inntekter (oppfrisker)
hvor ofte inntekt fra fangst og fisk (hyre og lott)

**Comment by elinkarlsen** [comment]
Vi har ikke noe oppe på denne @androa  ?

**Comment by androa** [comment]
> hvor ofte inntekt fra fangst og fisk (hyre og lott)

Mener du hvor ofte det er fangst og fisk med i inntektene som vises i GUI, eller når de gjør korrigeringer?
