### ISSUE TITLE
Ikke ha med næringsinntekter i klassifisering og GUI

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#142]
Elin vet hva som ikke skal være med.
Klassifiseringen er basert på oversikten vi fikk fra arena: [inntektskoder i Arena.xlsx](https://github.com/navikt/dagpenger/files/3296519/inntektskoder.i.Arena.xlsx)

**Comment by elinkarlsen** [comment]
![image](https://user-images.githubusercontent.com/51826130/59614282-b5684000-9120-11e9-8d8f-e0c98c03c28a.png)
