### ISSUE TITLE
Ytelsesrapportresultat - Få ned responstider for behandling av behov.

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#173]
Få ned responstider. 
Behandling av behov på kafka

**Comment by androa** [comment]
Det viser seg at prod går vesentlig raskere enn det gjorde under testinga. Enn så lenge har vi akseptable responstider (bortsett fra når vi spør inntektskomponenten).

Det har vært gjort noen små eksperimenter med å skrive om til plain Consumer/Producer, men det viser seg å ha uforutsett høy kost. Jeg lukker denne fram til det evt. blir et større problem.

Det virker uansett å være clusteret som er begrensende.
