### ISSUE TITLE
Teste minusinntekt

### ISSUE THREAD

**Issue by tonjemjovik** [navikt/dagpenger#179]

**Comment by tonjemjovik** [comment]
Avklare hva som skal skje her.

**Comment by androa** [comment]
@tonjemjovik Ble konklusjonen at alt er riktig? Eller trengs det å endre noe?

**Comment by tonjemjovik** [comment]
@androa Jeg tror det ja, men det tuller til noen av de feature-testene, så jeg begynte å se på de

**Comment by tonjemjovik** [comment]
Pull-requestene på reglene:
Minsteinntekt: https://github.com/navikt/dp-regel-minsteinntekt/pull/19
Periode: https://github.com/navikt/dp-regel-periode/pull/16
Grunnlag: https://github.com/navikt/dp-regel-grunnlag/pull/21

~WIP - endring av featureTestene: https://github.com/navikt/dp-regel-api-arena-adapter/compare/featureTest~ Flyttet til dagpenger-funksjonelle-tester
Mangler å få testet at ingen inntekt gir feilen "Inntektene gir 0 eller negativ resultat i grunnlag"

**Comment by androa** [comment]
Ktlint klager på noe formattering og når jeg fikser de får jeg noe issues med mockinga av `getSubsumsjonSynchronously`. Er den fortsatt WIP eller skal jeg se om jeg får fiksa det?

**Comment by tonjemjovik** [comment]
@androa Du kan gjerne se på det hvis du har mulighet!

**Comment by tonjemjovik** [comment]
Jeg har fikset ferdig reglene, og oppdatert feature-testene slik at de ikke tester problemer. Det som mangler er å få lagt på problem i adapteret dersom grunnlag er negativt. 
NB! Feature-testene er oppdatert i arena-adapter, men ser nå at noe av det er flyttet til funksjonelle-tester?
Lykke til

**Comment by gtcno** [comment]
> Jeg har fikset ferdig reglene, og oppdatert feature-testene slik at de ikke tester problemer. Det som mangler er å få lagt på problem i adapteret dersom grunnlag er negativt.
> NB! Feature-testene er oppdatert i arena-adapter, men ser nå at noe av det er flyttet til funksjonelle-tester?
> Lykke til

Jeg skal rydde opp i arena-adapter når jeg har fått på plass pipeline og automatisk kjøring av cucumber testene.
