### ISSUE TITLE
Backend: NavAnsatt endepunkt

### ISSUE THREAD

**Issue by PetterRuud** [navikt/dagpenger#185]
Lage et endepunkt for å hente ut informasjon om innlogget navansatt

eksempel DTO

```
brukernavn: "z990752"
funksjonellTid: "2019-07-02T11:50:54.74422"
kanBehandleKode6: false
kanBehandleKode7: false
kanBehandleKodeEgenAnsatt: true
kanBeslutte: true
kanOverstyre: true
kanSaksbehandle: true
kanVeilede: false
navn: "F_Z990752 E_Z990752"
```

**Comment by androa** [comment]
Denne kan vi sikkert skru litt på nå med GraphQL. Hva er egentlig behovet? Slik vi autentiserer oss bakover så skal tjenestene bakover utføre tilgangskontroll (men vi bør dobbeltsjekke at de har implementert de riktige kontrollene).

**Comment by PetterRuud** [comment]
Hadde vært greit å ha måte kunne skille på tilgang i frontend også, men siden vi ikke har noen forskjellige roller (saksbehandler, beslutter osv). Så trenger vi ikke denne.
