### ISSUE TITLE
Informere om nytt/endringer/tatt bort på Dagpengerinntektsredigering

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#191]

**Comment by androa** [comment]
Vi kan også bruke noe sånt som https://introjs.com/

**Comment by androa** [comment]
Er dette en must-have til å avslutte LEL @elinkarlsen? Ellers foreslår jeg at vi bare lukker den og lager en ny når vi må.

**Comment by elinkarlsen** [comment]
Dette er ikke en must for å fullføre LEL - P.t. har vi informert manuelt om endringer. Vi kan heller plukke opp ballen igjen når vi utvidere innsynsløsningen for saksbehandler. Per nå har vi sagt at vi ikke forbedrer inntektsinnsynet - det er godt nok

**Comment by androa** [comment]
OK, da lukker jeg denne :) 👍
