### ISSUE TITLE
Flytte lokalt kodeverk inn i soknaddagpenger-server

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#196]
Vi bruker i dag "lokalt kodeverk" i `henvendelse`. Det er planlagt å sanere og fjerne dette, så vi må flytte det inn i `sendsoknad-server`. Fordelen er at vi kan begynne å endre navn på vedleggene uten å påvirke andre søknader :)

Litt mer informasjon:
[Løse opp i kodeverk](https://confluence.adeo.no/pages/viewpage.action?pageId=322899701)
~[Kode som var nødvendig i `sendsoknad`](https://stash.adeo.no/projects/SOKD/repos/sendsoknad/pull-requests/952/overview)~ (Denne måten har Team søknad gått vekk fra)

Kort, Enonic skal erstattes med Sanity. Sanity har en egen ressurs for uthenting av kodeverk (https://tjenester.nav.no/soknadsveiviserproxy/skjemautlisting) som skal brukes. Sanity vil til enhver tid være kilden for `nav skjema nr` (aka `netsid` aka gosysid) 

- [x] Fjerne avhengighet til `no.nav.sbl.dialogarena:common-lokalt-kodeverk` pakka
- [x] Hente kodeverk fra sanity (Kjøretid eller byggetid?) (Team søknad henter det kjøretid og cacher, henter ny ved regelmessige intervaller)
- [x] Utvide kall til henvendelsetjenestekall som skal ta med mer info om skjemaet (se `createTilleggInfo` i sendSoknad)

[Kommentarer i koden fra team søknad sesjon](https://stash.adeo.no/projects/SOKD/repos/soknaddagpenger-server/commits/f27e0c2c56a2791eb0e81e9b9418d1df608ca1b2)
[Branch i sendsøknad som kan være til inpirasjon](https://stash.adeo.no/projects/SOKD/repos/sendsoknad/compare/commits?sourceBranch=refs%2Fheads%2Ffeature%2Fpurge-lokaltkodeverk&targetBranch=refs%2Fheads%2Fmaster) 

[Se på commits i master branchen til `sendSoknad`](https://stash.adeo.no/projects/SOKD/repos/sendsoknad/browse) (må nok ta branchen over som utgangspunkt)

**Comment by androa** [comment]
Klarer du å oppsummere kortfattet hva som må gjøres her @geiralund?

**Comment by geiralund** [comment]
yes! 
Nå angrer jeg veldig på at jeg ikke gjorde det den dagen jeg satt med team søknad :( 
Skriver det i beskrivelsen.

**Comment by androa** [comment]
(det var det jeg tenkte :D Ikke nødvendigvis at noen andre skal gjøre det, men Meget Lurt:TM: å ha sånt nedskrevet :D)

**Comment by geiralund** [comment]
Enig!

**Comment by androa** [comment]
Begynte på en ADR for løsning her https://github.com/navikt/dagpenger/blob/master/docs/adr/0008-hvordan-l%C3%B8se-lokalt-kodeverk.md
