### ISSUE TITLE
Implementere GraphQL mellom tjenester og frontend

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#197]
Vi har nå et ganske chatty integrasjonsmønster mellom GUI og API. VI har også måttet putte ting i "feil" API for at det skal være enklere. Vi bør flytte, konsolidere, og forenkle kommunikasjonen mellom frontend og API.

**Comment by androa** [comment]
Vi har en GraphQL-tjeneste som nå aggregerer all kommunikasjon til upstream tjenester.

**Comment by PetterRuud** [comment]
@geiralund 
Da vi nå skal bruke gamle rest endepunktet for å sende tilbake igjen til inntekt-api. Så må jeg vite hvilket felter som trengs eller om alle må være med?

Når det opprettes en ny postering i frontend så er det kun disse feltene som blir satt

```
fordel: values.fordel,
beloep: values.beloep,
utbetaltIMaaned: values.dato,
verdikode: 'denne kommer',
inntektskilde: 'dagpenger-regel-ui',
inntektsperiodetype: 'Maaned',
virksomhet: values.virksomhet,
inntektsmottaker: arrayHelpers.form.values.person.identifikator,
opplysningspliktig: values.virksomhet,
```

holder disse?
