### ISSUE TITLE
Hvordan håndterer vi hengende G

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#198]
Hvordan skal vi løse hengende G? Trenger vi å gjøre noe endringer?

"Hengende G" er perioden fra 1. Mai (når ny G normalt gjelder fra) fram til perioden den fastsettes (typisk i slutten av Mai). Alle vedtak hvor kravet til *minsteinntekt* sjekkes og beregningsdatoen er satt til et sted mellom 1. Mai og xx. Mai, skal bruke gammel G, mens vedtak etter xx. Mai skal få ny G.

Vi [fastsetter G basert på beregningsdato](https://github.com/navikt/dp-regel-minsteinntekt/blob/master/src/main/kotlin/no/nav/dagpenger/regel/minsteinntekt/Fakta.kt#L17) og [G mappes opp med datoer](https://github.com/navikt/dp-biblioteker/blob/master/grunnbelop/src/main/kotlin/no/nav/dagpenger/grunnbelop/Grunnbelop.kt#L22-L43).

For beregning av grunnlag henter vi også ut [G basert på beregningsdato](https://github.com/navikt/dp-regel-grunnlag/blob/06f699a21c0eef7e5532803d699a4c69002738d3/src/main/kotlin/no/nav/dagpenger/regel/grunnlag/Fakta.kt#L22).

**Comment by androa** [comment]
Betyr dette at vi tidlig i Mai deploye nytt sett av G med virkningsdato fra xx. Mai. Når er det riktig å endre fra xx. Mai til 1. Mai? Etter xx. Mai?

**Comment by androa** [comment]
Etter å ha pratet litt med @elinkarlsen og tegna på tavla så tror jeg revidert forklaring er sånn:

Det er ulike ting som styrer om nytt grunnbeløp skal brukes, avhengig av om det gjøres i kontekst av minsteinntekt, eller i fastsetting av grunnlag.

Ny G blir kjent xx. Mai. Etter ny G er kjent, så kjøres G-justering og ved G-justering skal ny G gjelde, med tilbakevirkende kraft til 1. Mai, for fastsetting av grunnlag og dermed også satsene.

Etter G-justering er kjørt, skal ny G gjelde for krav minsteinntekt, men fra første mandag etter G-justering.

Så for *grunnlag* gjelder et grunnbeløp fra 1. Mai (etter G-justering) -> 30. April. For vurdering av minsteinntekt så gjelder G alltid fra xx. Mai -> xx. Mai.

**Comment by androa** [comment]
Vi trenger hengende G :) Arenas rutine for G-justering forklarer begrepene ganske enkelt: https://confluence.adeo.no/display/TEAMARENA/Rutine+for+G-regulering+i+Arena.

I Arena så finnes G(Grunnbeløp) og HG(Hengende Grunnbeløp). G brukes til beregning av grunnlag, og HG brukes til vurdering av minsteinntekt. De to har ulike gyldighetsperioder.

Vi kan enten lage G/HG som ulike verdier, eller utvide [dagens Grunnbeløp-tabell](https://github.com/navikt/dp-biblioteker/blob/master/grunnbelop/src/main/kotlin/no/nav/dagpenger/grunnbelop/Grunnbelop.kt#L22-L43) med flere gyldighetsperioder, avhengig av hvilken regel som spør.

**Comment by elinkarlsen** [comment]
Det er både kravet til minste inntekt og kravet til hvor mye du må ha tjent for å få 104 uker som endres fra og med dagen etter G-reguleringen. Det betyr at Hengende G får konsekvens for både regel om minste inntekt og regel om stønadsperioden. Årsaken til dette er at begge regelen bruker inntektsbegrepet i 4-4 (kravet til minsteinntekt). Det er kun grunnlag og sats som bruker utvidet inntektsbegrep. Var det forståelig? @androa @tonjemjovik  @atleno @geiralund

**Comment by elinkarlsen** [comment]
eksempel fra i år der G-regulering var helgen 25-26. mai . Inntekt på minst 2 x 96.883 gir 104 uker så lenge fra virkningsdato (beregningsdato i Arena) er før 27.05.19. Fra 27.05 innvilges 104 uker når inntekt er minst 2 x 99858.

**Comment by androa** [comment]
#130 beskriver allerede at vi trenger hengende G :)

**Comment by androa** [comment]
Implementasjon løses med #130 så jeg lukker denne :)
