### ISSUE TITLE
Finne ut hvordan vi løser G-justering

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#199]

**Comment by androa** [comment]
Arbeidsfordelingen blir grovt sett som følgende:
- Arena gjør kandidatuttrekk (altså finner de som skal G-justeres)
- Arena kaller oss med person, nytt vedtak(id), beregningsdato, og en gitt inntektsId (fra forrige vedtak)
- Arena oppdaterer grunnlag og sats
- Arena regner ut differanse på eventuelle utbetalinger

**Comment by androa** [comment]
Vi må bygge støtte for at ulike regler kan bruke ulike G til ulik tid: #198

**Comment by espenjohansen** [comment]
Har snakket litt med Arena-leverandør, og det er ikke noe inntektsID i Arena på de vedtak som Digidag har beregnet. De tenker å sende over opplysninger som DPBERDATO, VERNP3AV12, INNFANFISK og BARNMSTON. Er det tilstrekkelig for at vi kan beregne grunnlag og sats på nytt? Hovedsaklig gjelder dette vedtak om dagpenger som er innvilget med fra dato 1. mai 2020 og senere, som da skal ha ny beregning på opprinnelig inntekt/vedtak i henhold til ny G. I tillegg kommer alle de som har grunnlag på 3G pga militært grunnlag, som da skal ha nye 3G.

**Comment by androa** [comment]
At det mangler inntekts-id er jo et problem. Uten den så har ikke vi noe logikk for å forstå hvilke inntekter som skal brukes. Da må vi i så fall ha med IDen til vedtaket som utførte den opprinnelige beregningen.

Vi har diskutert en del hvor nødvendig det er å ta med vedtaksid, vs bare kombinasjonen av person + beregningsdato. Mulig vi må tenke ekstra godt gjennom det. @geiralund @tonjemjovik

**Comment by geiralund** [comment]
Ai, inntekts-id er essensiell ja.

Sånn modellmessig synes jeg at inntekt "hører" til en person og en gitt dato - men vi har vel diskutert dette før, og mener å huske at er noe som gjør at en må ha vedtaksid

**Comment by androa** [comment]
Bekreftet av Mona at de tar vare på inntektsId.

Da begynner jeg på implementering i #207
