### ISSUE TITLE
Regel uten vedtakid - regelkjøringer startet av sluttbruker

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#203]
Vi bør støtte å kjøre reglene i mange ulike kontekster.

Tre kontekster som allerede utmerker seg er:
- Veiledning/serviceberegning - altså før søknad fylles ut)
- Søknad
- Vedtak/saksbehandling

Det bør nok være en tuple ala `{ kontekstType: String, kontekstId: String }` eller en URI `no.nav.dagpenger.kontekst.[TYPE]:[ID]`.

**Comment by androa** [comment]
Etter å ha pratet litt med @geiralund i dag tidlig, så bør vi nok heller ikke propagere disse IDene rått inn i vårt system. Vi bør nok alltid ha en mapping tabell som gir oss en helt unik intern ID for hver kontekst + id.

**Comment by androa** [comment]
Lukker denne til fordel for #212
