### ISSUE TITLE
Grafanaboard på søknad - gir oss info om hvem dagpengesøkerne er

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#208]

**Comment by androa** [comment]
Jeg har så smått begynt på en branch som ganske rått legger til "alle" felter i søknaden på et influx event. Men føler at det veldig fort blir høy noise-to-signal ratio, og at det er bedre å ta seg tid til å modellere litt mer eksplisitt hva vi er ute etter.

Foreslår en liten sesjon for å tenke hva som er gøy data, og så implementere de eksplisitt.
