### ISSUE TITLE
Grovestimere nytt innløp

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#211]
Vi trenger å grovestimere nytt innløp for å vite om det skjer i 2019 eller neste år.

**Comment by androa** [comment]
For å ha et sted å begynne å estimere trenger vi en grov liste over ting som må gjøres. Her er de jeg husker:

- Mottak fra Joark
- (Oppslag av) GT/skjermingskode og mapping mot behandlende enhet
- Vurdering av ny sak / nytt vedtak i eksisterende sak
- Opprette sak i GSAK
- Opprette sak/vedtak i Arena
- Opprette oppgave i Arena

Legg til ting som mangler :)

Alternativt er at vi lager noen brukerhistorier og prøver å dra de hele veien igjennom. Men vi klarer uansett ikke å iterativt erstatte gamle Ruting, så det blir en big bang launch :(

**Comment by tonjemjovik** [comment]
Eventuelt opprette oppgave i GSAK ?
Ferdigstille journalpost?

**Comment by geiralund** [comment]
Fra tidligere jobbing: https://confluence.adeo.no/pages/viewpage.action?pageId=294131690

**Comment by elinkarlsen** [comment]
Fredag er frist for å gi estimatene - beklager masa her :)

**Comment by androa** [comment]
Vi grovestimerte vel litt her og sa 3 utviklere i 3 måneder, men nå er vi uansett ganske langt forbi fristen så jeg lukker :D
