### ISSUE TITLE
For å kunne slette subsumsjoner som IKKE er brukt trenger vi et konsept om eksterne id'er og eksterne kontekster 

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#212]
I dagens datamodell i dp-regel-api har vi ikke noe konsept om eksterne id'er når et behov kommer, som gjør det vanskelig å vite hvor et behov kom fra. Vi trenger å utvide datamodellen slik at vi kan mappe hvilke ekstern id'er som har produsert hvilke behov.

Tanken er å utvide lage en  `v2_behov` og `v1_behov_ekstern_id` (navn må bestemmes) tabell hvor `v2_behov` utvides til å inneholde en referanse id som er definert i `v1_behov_ekstern_id`
`v1_behov_ekstern_id` inneholder ekstern kontekst + id

**Comment by androa** [comment]
Er #203 egentlig en duplikat av denne?

**Comment by geiralund** [comment]
Du har nok helt rett @androa  -  #203 kan muligens lukkes / kobles til denne.
