### ISSUE TITLE
BruktSubsumsjon consumer i dp-inntekt-api stopper

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#224]
I dag stoppet `KafkaSubsumsjonBruktDataConsumer` i `dp-inntekt-api` opp.

Kibana sier `[Consumer clientId=consumer-1, groupId=dp-inntekt-api-consumer] Node 1 was unable to process the fetch request with (sessionId=1285789303, epoch=8027): FETCH_SESSION_ID_NOT_FOUND.`.

Jeg løste det med å slette poddene. Vi burde både fange opp disse feilene, finne rotårsaken, men også sørge for at `isHealthy`-endepunktet fanger det opp så poden blir restartet.

**Comment by chriswk** [comment]
Ref dette, vi burde utvide consumeren til å implementere HealthCheck også, slik at det er en av tingene som sjekkes når isHealthy blir pollet

**Comment by chriswk** [comment]
Ref https://github.com/navikt/dp-regel-api/blob/master/src/main/kotlin/no/nav/dagpenger/regel/api/streams/KafkaSubsumsjonBruktConsumer.kt

**Comment by androa** [comment]
Det skjer igjen nå :(

**Comment by geiralund** [comment]
Det er som er litt kjipt med å legge den som HelthCheck og legge til i isHealthy sjekk er at det kan potensielt ta ned APIet som egentlig er helt uavhengig av consumeren. Mulig vi skal legge 1) consumere som dette i egne tjenester, eller 2) lage en "ConsumerMonitor" som restarter consumeren innad i APIet

**Comment by androa** [comment]
Vi bør lage selve consumeren litt mer robust internt.

Å trekke den ut i en egen tjeneste høres lurt ut (og utføre operasjonen via API og ikke rett mot database).

Å restartet den automatisk via healthcheck med en veldig lang grace period (typ, 2-3 timer) er kanskje en mer quickfix-løsning? Altså at consumeren må ha vært død ganske lenge før podden blir restartet.

**Comment by geiralund** [comment]
Jeg la til en kvikkfiks ved at den restartes nå - men en grace er nok lurt å legge til. Skal se på det.
