### ISSUE TITLE
BRUT (aka Ruting): avgrense behandling av "Ny-Ny" Papir/digital

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#228]

**Comment by gtcno** [comment]
Vi har snakket med Team ISA/ v Tor Erik Eide. 

Team ISA skal endre BRUT til å IKKE håndtere 
` 
 "NAV 04-01.03" 
"NAV 04-01.04" 
`

Vi må journalføre disse og også håndtere manuell journalføring. 
Det blir ingen feature toggle, pga kompleksitet. Men vi kan rulle tilbake versjoner raskt. 

Saken kan følges i https://jira.adeo.no/browse/ISA-928
