### ISSUE TITLE
 HentInngaaendeJournalpost skal fases ut - erstattes med Query: journalpost

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#233]
I dagpenger-joark-mottak benytter vi https://confluence.adeo.no/display/BOA/TJOARK056-+HentInngaaendeJournalpost for å hente journalpostmetadata - denne tjenesten er under avvikling og skal erstattes med https://confluence.adeo.no/display/BOA/Query%3A+journalpost
Vi må skrive om tilsvarende.

**Comment by Bendreas** [comment]
Noen observasjoner: 
- Feltene er ikke identiske. Noen er like, noen finnes det tilsvarende av, og noen få finnes ikke lenger. Hvordan kan jeg finne ut hvilke som faktisk trengs? Det fine med GraphQL er jo at vi kan ta akkurat det vi vil ha og ingenting mer.
- Det er få GraphQL-klienter for jvm. Den mest kjente – apollo-android synes jeg var ganske kjip. Tror det i første omgang er best å gjøre post-kall med vanlige http-klienter.
