### ISSUE TITLE
Kalkulator frontend: Håndtere problems fra kalk-api. (Egendefinerte feilmeldinger)

### ISSUE THREAD

**Issue by kmriise** [navikt/dagpenger#264]

**Comment by PetterRuud** [comment]
Alt av feilmeldinger håndteres nå i ErrorBoundary.
Enkelt å endre tekster osv basert på statuskoder.

**Comment by kmriise** [comment]
La til statuskode for bad gateway når vi timer ut mot skatt, viser nå egendefinert feilmelding hos kalkulatorfrontenden
