### ISSUE TITLE
Set up metrics we need verification before production

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#28]
Before we go live, we need to set up all metrics we need confirmation on to have sufficient trust in our solution.

**Comment by nicokk** [comment]
I've added metrics-gathering in:
- joark-mottak (see https://github.com/navikt/dagpenger-joark-mottak/pull/16)
- skanning (see https://github.com/navikt/dagpenger-journalforing-skanning/pull/4)
- ruting (https://github.com/navikt/dagpenger-journalforing-ruting/blob/master/src/main/kotlin/no/nav/dagpenger/journalf%C3%B8ring/ruting/Journalf%C3%B8ringRuting.kt#L78)
