### ISSUE TITLE
** Lage q2 syntetisk verdikjede **

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#294]
- [x] dp-datalaster-inntekt - Giao
- [x] dp-inntekt-api - Giao - PR 
- [x] dp-oppslag - Giao  - PR
- [x] dp-inntekt-klassifiserer -  Giao - PR
- [x] dp-regel-api-arena-adapter - Geir Andre - PR 
- [x] dp-regel-api - Geir Andre - PR 
- [x] dp-regel-sats - Geir Andre
- [x] dp-regel-periode - Geir Andre
- [x] dp-regel-minsteinntekt - Geir Andre
- [x] dp-regel-grunnlag - Geir Andre
~dp-vedtaksresultat-lytter~

**Comment by geiralund** [comment]
dp-regel-api-arena-adapter og dp-regel-api
Ligger i PR - opprettet Vault secrets for de, ble usikker på om det må gjøres noe mer for  dp-regel-api og databasen

**Comment by geiralund** [comment]
Denne er done!

**Comment by gtcno** [comment]
Fra: Richardsen, Torbjørn <Torbjorn.Richardsen@nav.no>
Sendt: tirsdag 28. januar 2020 16.12
Til: Malik, Waseem <Waseem.Malik@nav.no>; Skevik, Wenche <Wenche.Skevik@nav.no>
Emne: SV: Arena og Digidag - Utfordringer med synt miljø

 

Har nå fått godkjente vedtak på gammel og ny løsning, dvs vurdering av inntekt før og etter Digidag. Mao koblingen mot Digidag funket.
