### ISSUE TITLE
Som utvikler i digitale dagpenger skal det være lett lage nye apps 

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#310]
Det er i dag mye manuelt som skal til for å få en ny app ut. Blant annet; opprette systembruker, legge til app i vault-iac,  opprette kafka topic og roller for topicet, nais filer etc. 

MVP? Kan vi gjøre prosessen lettere? Kan vi automatisere?

**Comment by androa** [comment]
Ta dette litt underveis og ved behov.
