### ISSUE TITLE
Kjøre datalast fra produksjon på inntekt databasen til q0. La dp-inntekt-api bruke q0 databasen istedet for dp-inntekt-db-preprod

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#317]

**Comment by gtcno** [comment]
- [x] Last inn data fra dp-inntekt-db i produksjon til dp-inntekt-db-q0 i preprod, 

- [x] La dp-inntekt-api  i preprod-fss/default peke til dp-inntekt-db-q0

- [x] Etter at Arena er ferdig med testing. Truncate dp-inntekt-db-q0 database. 

- [x]  La dp-inntekt-api  i preprod-fss/default peke til dp-inntekt-db-preprod

- [x] Hente inntekt basert på InntektsId i dp-inntekt-klassifiserer, ser ut til at dette ble borte under flytting fra dp-datalaster-inntekt (https://github.com/navikt/dp-datalaster-inntekt/blob/master/src/main/kotlin/no/nav/dagpenger/datalaster/inntekt/Datalaster.kt#L51-L60)

**Comment by magnefjeld** [comment]
Trellokort: https://trello.com/c/hvKlcTQV/93-g-justering-2020-utsatt
