### ISSUE TITLE
Opprette testmiljø i q0 for G-reguleringstest - Arena

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#318]
- Avhenger av navikt/dagpenger#318 er gjort
- Arena kjører datalast søndag 26.04 kl. 07:40 , vi må gjøre det før det. 

Apper som må kjøre for reberegningstest

- [ ] dp-inntekt-api  (med database!)
- [ ] dp-regel-api (med database!)
- [ ] dp-regel-api-arena-adapter 
- [ ] dp-inntekt-klassifiserer 
- [ ] dp-regel-minsteinntekt
- [ ] dp-regel-grunnlag
- [ ] dp-regel-periode
- [ ] dp-regel-sats

**Comment by gtcno** [comment]
Etter å snakket med Arena. Har vi bestemt at de kan bruke q1 mijøet(DVS default-namespace) i preprod-fss.

Vi trenger dog å laste inn inntekter fra prod. Dette gjøres i #317
