### ISSUE TITLE
Fikse feilen med Hyre og Annet

### ISSUE THREAD

**Issue by elinkarlsen** [navikt/dagpenger#319]
Vi må endre måten vi håndterer Hyre og Annet for å overholde korrekt lovtolkning av arbeidsinntekt i kap 4. ASD er orientert og har en svarfrist. 

Hvis ASD er enig så skal dette implementeres fra og med 17. mars. Det er meget sannsynlig at de er enig justeringen vi gjør nå så vi endrer i reglene våre nå og sikre at dette blir lansert 17. mars

**Comment by elinkarlsen** [comment]
Slik skal Hyre korrekt håndteres etter ny tolkning:

I dag er det slik at vi kun tar med Hyre dersom "inntekt fra fangst og fisk" er satt til ja. Endringer blir at så lenge brukeren har inntekt fra hyre så skal hyre med i både minsteinntekt  4-4, dagpengeperiode (4-15) og dagpengegrunnlaget (4-11). Altså nå uavhengig om fangstogfiske er ja eller nei

Unntak: SYKEPENGER_TIL_FISKER_SOM_BARE_HAR_HYRE og DAGPENGER_TIL_FISKER_SOM_BARE_HAR_HYRE skal bare med i dagpengegrunnlaget 4-11 også uavhengig fangst og fisk er ja eller nei. 

Jeg har sendt en avklaring til Kjetil på denne: Dagpenger til fisker og Sykepenger til fisker, for den mener jeg kun skal med i grunnlaget 4-11 dersom inntekt fangst og fisk ja. 

Hyre er de inntektene som har tilleggsbeskrivelse "hyre til mannskap på fiske-, småhvalfangst- og selfangstfartøy" og postfiks h. 

ta kontakt om noe er uklart :)

**Comment by elinkarlsen** [comment]
Slik skal Annet håndteres etter ny tolkning: 
![image](https://user-images.githubusercontent.com/51826130/75993779-4c1c9d00-5efa-11ea-83c5-8e207af69c26.png)

Tidligere har vi hatt alle disse som nei hos oss, nå skal disse seks endres til ja. NB her må vi synkes med team register for hvis de endrer filteret først og vi ikke har satt disse til ja risikerer man kodeverksfeil! 

det skal ikke gjøres andre endringer knyttet til annet

**Comment by magnefjeld** [comment]
Hei. Vi utreder om vi kan levere denne natt til fredag 13 mars. Er det noen hindringer for det?

**Comment by atleno** [comment]
Stemmer det, at det er dette som skal gjøres:

**Inntektskomponenten begynner å gi oss inntekt med denne tilleggsinformasjonen:**
Lønn og annen godtgjørelse som ikke er skattepliktig,
Lønn fra den norske stat, opptjent i utlandet,
Lønn ved konkurs eller statsgaranti

Fra før av tar vi imot disse, som vi klassifiserer til henholdsvis FANGST_FISKE og TILTAKSLØNN:
Hyre til mannskap på fiske-, småhvalfangst- og selfangstfartøy
Lønn ved arbeidsmarkedstiltak

**Vi endrer vår klassifisering, og begynner å klassifisere disse til ARBEIDSINNTEKT:**
Hyre til mannskap på fiske-, småhvalfangst- og selfangstfartøy
Lønn og annen godtgjørelse som ikke er skattepliktig,
Lønn fra den norske stat, opptjent i utlandet,
Lønn ved konkurs eller statsgaranti

Eneste som vi klassifiserer til FANGST_FISKE da, er 
N_LOTT_KUN_TRYGDEAVGIFT
N_VEDERLAG



**Skal SYKEPENGER_TIL_FISKER_SOM_BARE_HAR_HYRE og DAGPENGER_TIL_FISKER_SOM_BARE_HAR_HYRE håndteres som før?**
I dag klassifiserer vi de til DAGPENGER_FANGST_FISKE og SYKEPENGER_FANGST_FISKE

Minsteinntekt og periode bruker disse klassene:
Uten fangst/fiske: ARBEIDSINNTEKT
Med fangst/fiske: ARBEIDSINNTEKT + FANGST_FISKE

Grunnlag bruker disse klassene:
Uten fangst/fiske: ARBEIDSINNTEKT + DAGPENGER + SYKEPENGER + TILTAKSLØNN
Med fangst/fiske: ARBEIDSINNTEKT +  DAGPENGER + SYKEPENGER + TILTAKSLØNN + FANGST_FISKE + DAGPENGER_FANGST_FISKE + SYKEPENGER_FANGST_FISKE

**Sånn som jeg har skjønt det, så skal vi putte litt mer inn i ARBEIDSINNTEKT, og ha mindre i FANGST_FISKE, men for reglene så er disse inntektsklassene fortsatt riktig?**

**Comment by magnefjeld** [comment]
Hei. Da er det landet at endringen leveres til fredag 13. mars (i løpet av kvelden/natten 12 mars) ref https://jira.adeo.no/browse/PROD-14726 . Vi (og Team Arena) må levere først, deretter Team registre.  Se for øvrig bestilling til team Arena (https://jira.adeo.no/browse/ARENA-3997) og bestilling til team Registre (https://jira.adeo.no/browse/REG-7215)

**Comment by elinkarlsen** [comment]
Hei @atleno jeg har nå forsøk å tydeliggjøre hvordan vi skal håndtere hyre - se vedlegg. Er det forståelig? Hovedpoenget er at vi har håndtert alt som heter hyre som næringsinntekt slik at inntektene kun er tatt med når vedtaksfakta fra Arena på fangst og fiske er satt til oppfylt så har hyre blitt med. Dersom fangst og fisk har vært false har vi ikke tatt med hyre i beregningen og det er dette som er feil. 

Vært obs på skille mellom inntektene som tas med i beregningen av både minsteinntekt, periode og dagpengegrunnlag og de inntektene som heter sykepenger og dagpenger til fisker som bare har hyre. De to sistnevnt skal kun med i dagpengegrunnlaget 4-11 og aldri i minsteinntekt eller periode. 
[Håndtere hyre.xlsx](https://github.com/navikt/dagpenger/files/4317776/Handtere.hyre.xlsx)

Jeg kommer med en oppdatering på hvordan annet skal håndteres

**Comment by elinkarlsen** [comment]
Her kommer beskrivelse av annet @atleno Det er viktig å understreke at det er kun disse seks som skal endres, så selv om du finner andre inntektsbeskrivelser som nevner annet - ikke rør :) det er bare disse seks som skal endres. Du vil se at en heter både annet og hyre sånn den er nevnt i begge excelarkene. 

ta kontakt om spm
[Håndtere annet.xlsx](https://github.com/navikt/dagpenger/files/4317861/Handtere.annet.xlsx)
