### ISSUE TITLE
Finne ut hvor vi kan få tak i strukturert søknadsdata fra

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#320]
For at automatisk saksbehandling skal treffe riktig trenger vi å kunne filtrere på forskjellige fakta fra søknaden.
Joark har sikkert noe, men vi må finne ut hvilket endepunkt vi må spørre.

**Comment by urenhale** [comment]
denne
https://confluence.adeo.no/display/BOA/saf+-+REST+hentdokument

**Comment by atleno** [comment]
Fikk manuelt hentet strukturert jsondata fra joark nå. f.eks: 
https://saf-q1.nais.preprod.local/rest/hentdokument/466990042/485206279/ORIGINAL

når man huker av for verneplikt ser det slikt ut:
```
{
   "faktumId":774624,
   "soknadId":10619,
   "parrentFaktum":null,
   "key":"ikkeavtjentverneplikt",
   "value":"false",
   "faktumEgenskaper":[
   ],
   "properties":{
   },
   "type":"BRUKERREGISTRERT"
},
```
litt rart med dobbel negering bare
