### ISSUE TITLE
Finne ut hvordan vi skal angripe innsyn/innsikt.

### ISSUE THREAD

**Issue by kmriise** [navikt/dagpenger#322]
Kartlegge:
Hvilke målinger har vi tilgjengelig nå?
Hvilke målinger mangler vi?
Hvaslags innsyn kan vi hente ut nå?
Hvaslags innsyn mangler vi?
Hvordan kan vi vise innsyn nå?
Hvordan bør vi vise innsyn i fremtiden?

**Comment by androa** [comment]
Lukker denne. Vi trenger en liten reboot nå post-corona og få samlet trådene igjen.
