### ISSUE TITLE
Skru av og arkivere dp-vilkaar-tester

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#324]
Denne er erstattet med av innløpet ved at den markerer minste arbeidsinntekt avslag på Arena oppgaver

**Comment by urenhale** [comment]
venter på pr-er som skal gå gjennom via vault, og mangler mulighet til å slette servicebruker (hører med mats)

**Comment by geiralund** [comment]
Jeg lurer på om det er en delt systembruker forresten. Men ble usikker

11. mar. 2020 kl. 20:00 skrev Marte Pedersen <notifications@github.com>:

﻿

venter på pr-er som skal gå gjennom via vault, og mangler mulighet til å slette servicebruker (hører med mats)

**Comment by urenhale** [comment]
@geiralund den heter jo `srvdp-vilkaar`, så rart hvis den er delt?

**Comment by geiralund** [comment]
ja, jeg husker nok feil. Vi delte systembruker mellom dagpenger-journalforing-arena og dagpenger-journalforing-ferdigstill.

**Comment by urenhale** [comment]
mats sletter bruker på mandag
