### ISSUE TITLE
For automatisk saksbehandling vil vi kunne sjekke om søker har andre ytelser

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#333]
Kode 6/7?
Fnr/dnr infotrygd
Fom og tom til infotrygd

Trenger fom og tom til infotrygd hvor kommer denne fra?

- [x] Deploy til prod.

 

Test1: Mislykkes 401. Infotrygd hendelse må whiteliste tokenet so blir sendt.

Littt debug og fiksing på infotrygde siden så gikk det gjennom.  

Test2:  OK

**Comment by Bendreas** [comment]
Finne ut nøyaktig fom og tom-dato
