### ISSUE TITLE
Fastsette vanlig arbeidstid

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#336]
For å vurdere fastsette vanlig arbeidstid må vi hente alle aktive ar beidsforhold fra AA-registeret og regne ut.

Hypotese om mulig god nok løsning: Hent arbeidsforhold fra AA-registeret.

https://lovdata.no/dokument/LTI/forskrift/2020-04-03-602

**Comment by Bendreas** [comment]
Løse tråder:
* hvordan skal vi matche arbeidsforhold fra søknad til aa-reg?
* hvilket tidspunkt skal vi bruke for å se etter "aktive arbeidsforhold"?

**Comment by Bendreas** [comment]
Vi skal kun behandle brukere med ett arbeidsforhold.
Hvor langt bak i tid må bruker bare ha ett arbeidsforhold i aa-reg for at vi kan være sikre på at søknadsarbeidsforholdet er det samme?

**Comment by Bendreas** [comment]
dok aareg: https://modapp-q1.adeo.no/aareg-core/api/swagger-ui.html#/arbeidsforhold.v1/finnArbeidsforholdPrArbeidstaker

**Comment by Bendreas** [comment]
Siden vi kun skal ta hundre prosent permittert fra ett enkelt arbeidsforhold med hundre prosent stilling, vet vi at arbeidstid allti vil være det som står rapportert i aa-reg under feltet timerPerUke. Dette får vi fra dp-oppslag-arbeidsforhold. Vi må kanskje runde opp timene til 37.5.
