### ISSUE TITLE
Fastsette virkningstidspunkt

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#337]
For å vite hvilken dato vedtaket skal gjelde fra må vi fastsette virkningstidspunktet

Hypotese om mulig god nok løsning: Siste dato etter:
- Søknadstidspunkt
- Registrering
- Permitteringsdato fra søknad/aareg + 2 dager.

- [x] Få ut skall
- [x]  Avklare hva virkningstidspunkt er
- [x] Implementert mvp
- [ ]  Vente på politisk svar på om løsningen er innafor, med den nye korona-forskriften

**Mvp**:
Kun tenke på de med ett arbeidsforhold
Kun tenke på de som er permittert etter 20 mars - 15 dager (den opprinnelige lønnsplikten)
Vi går utifra at de er 100% permittert (har det noe å si?)

For de som har permitteringsdato 18. mars eller før, er beregingsdato 20. mars + 18 dager,
fordi lønnspliktsperioden er ferdig 20. mars.
For de med permitteringsdato 20. mars eller senere, er beregningsdato permitteringsdato + 2 + 18 dager.

**Comment by elinkarlsen** [comment]
foreslått tellemåte @Bendreas 
Fra søknad om dagpenger oppgir den permitterte selv fra hvilket tidspunkt han/hun er permittert. Vi foreslår å legge det tidspunktet til grunn for når permitteringen trådte i kraft og deretter telle på en forenklet måte de neste 20 dagene.  

vi skal vurdere retten til dagpenger fra dag 21.


Vi foreslår lik telling av de to lønnspliktdagene og de resterende 3-20 dagene. Fra og med 20. mars gjelder regler om 2 lønnspliktdager.  

Permitteringslønnsloven § 3 b gjelder for nye permitteringer. For iverksatte permitteringer fryses det antallet avviklede lønnspliktdager som arbeidsgiver har utbetalt permitteringslønn for, fra og med 20. mars 2020 

Vanlig dagpengeregelverk: 
Telling av lønnspliktdager skjer i dag manuelt og er basert på når personen skulle ha jobbet, avviklet ferie mv. arbeidsgiver avgjør.  

Særlige regler tilknyttet Korona-krisen 
Fra og med 20. mars gjelder bare krav om 2 lønnspliktdager. For å få fart i saksbehandlingen og for å legge til rette for automatisk behandling av Koronapengene, telles disse på samme måte som perioden dag 3-20.  

Konklusjon på begge 
Koronapenger løper i 18 virkedager (mandag til fredag) etter at lønnsplikten er avviklet. Perioden forskyves ikke ved avtalt tjenestefri, sykmeldt sykdom eller omsorgsfri. Perioden forskyves heller ikke som følge av helligdager eller ved delvis arbeid. Det samme gjelder telling av de to lønnspliktdagene før eventuelle Koronapenger. 

Eksempel 
Dersom arbeidsgiver permitterer fra og med 20. mars, telles arbeidsgivers lønnsplikt i to dager fredag og mandag. Deretter telles fortløpende 18 Koronapengedager fra og med tirsdag 24. til og med torsdag 16. april. De ses bort fra bevegelige og ubevegelige helligdager. Det ses bort fra eventuell forskyvning av lønnsplikten ved avtalt tjenestefri osv.  

Dagpenger under permittering kan da innvilges fra 17. april. 

 

NB dette er de samme retningslinjene som er oversendt til NAV Arbeid og Ytelser og som de legger til grunn for den manuelle saksbehandlingen. Manuell og automatisk saksbehandling av dagpenger bør legge til grunn den samme forenklede saksbehandlingen.

**Comment by Bendreas** [comment]
Hva skjer om man er permittert fra flere arbeidsforhold. hvilken dato skal man bruke?

**Comment by Bendreas** [comment]
Skal vi ikke ta hensyn til "hvilken dato søker du dagpenger fra"?

**Comment by androa** [comment]
Vi må iallefall ha datoen man har søkt fra for å avgjøre hvilken side man er på av 20. Mars.

**Comment by atleno** [comment]
@magnefjeld Tar du en titt på det vi har skrevet om mvp-versjonen av løsningen, er dette bra nok for nå?

**Comment by 80IngeborgA80** [comment]
> For å vite hvilken dato vedtaket skal gjelde fra må vi fastsette virkningstidspunktet
> 
> Hypotese om mulig god nok løsning: Siste dato etter:
> 
> * Søknadstidspunkt
> * Registrering
> * Permitteringsdato fra søknad/aareg + 2 dager.
> * [x]  Få ut skall
> * [x]   Avklare hva virkningstidspunkt er
> * [x]  Implementert mvp
> * [ ]   Vente på politisk svar på om løsningen er innafor, med den nye korona-forskriften
> 
> **Mvp**:
> Kun tenke på de med ett arbeidsforhold
> Kun tenke på de som er permittert etter 20 mars - 15 dager (den opprinnelige lønnsplikten)
> Kun de som er 100% permittert **fra 100% stilling** (har det noe å **si? - **ja, vi må få endelig avklaring først**)****
**> Kun de som ikke har skift/turnus/rotasjon (noe annet må vi vente på avklaring)**

> For de som har permitteringsdato 18. mars eller før, er beregingsdato 20. mars + 18 dager,
> fordi lønnspliktsperioden er ferdig 20. mars.
> For de med permitteringsdato 20. mars eller senere, er beregningsdato permitteringsdato + 2 + 18 dager.

**Comment by 80IngeborgA80** [comment]
> @magnefjeld Tar du en titt på det vi har skrevet om mvp-versjonen av løsningen, er dette bra nok for nå?

Jeg har gjort noen endringer, se det jeg har endret i fet.

**Comment by atleno** [comment]
Har implementert det slik som Ingeborg skrev
