### ISSUE TITLE
Avklare ny/gjenopptak

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#339]
For å vurdere om det skal være ny eller gjenopptak må vi hente tidligere vedtak.

Hypotese om mulig god nok løsning: Sjekk at personen ikke har vedtak i Arena siste 2 år.

**Comment by Bendreas** [comment]
https://confluence.adeo.no/display/ARENA/Arena+-+Tjeneste+Webservice+-+ArbeidOgAktivitetVedtak_v1

**Comment by Bendreas** [comment]
Eller vent.... 

> **Bør ikke brukes for dagpenger**
> Denne operasjonen bør ikke brukes for dagpenger siden uttrekket i mange tilfeller ikke vil gi forventet resultat. Spesifikt, vedtak som har fraDato før fom-dato i input og ingen tilDato, vil ikke bli returnert av operasjonen. Dermed kan det løpende dagpengevedtaket bli filtrert bort. Bakgrunnen er at dette er ønsket filtrering av AAP-vedtak som normalt har tilDato satt på vedtaket. Dette i motsetning til dagpengevedtak som normalt ikke har tilDato satt på vedtaket.

Må høre med Elin om den allikevel kan brukes siden vi setter 2 år fra i dag. Kan kanskje eventuelt bruke denne https://confluence.adeo.no/display/ARENA/Arena+-+Tjeneste+Webservice+-+YtelseVedtak_v1

**Comment by Bendreas** [comment]
https://confluence.adeo.no/display/ARENA/Arena+-+Tjeneste+Webservice+-+Ytelseskontrakt_v3 er nok den beste ja.

Må avklare hva vi egentlig leter etter i listen. Som en start går vi gjennom alle dagpengesaker og alle vedtak som hører under disse. Hvis et vedtak er aktivt og har til og med dato som er innenfor perioden i dag - 2 år, sier vi det er gjenopptak. Dette må avklares videre.

**Comment by elinkarlsen** [comment]
For å vurdere om det skal være ny eller gjenopptak må vi hente tidligere vedtak. Vi skal behandle Ny Rettighet for permitterte med virkningstidspunkt 20.mars, resterende saker må gå til manuell behandling

Sjekk at personen ikke har vedtak (til og med dato)  i Arena siste 1.5 år. Jeg får ikke redigert din opprinnelige tekst @androa  så det blir en kommentar nedi her.

**Comment by Bendreas** [comment]
Referer til Arena-folket som har sagt vi skal se etter:

> Da må du se på ytelsestype DAGP der det finnes vedtak (her kalt ihtVedtak - aner ikke hvorfor...) med følgende karakteristikk:
> * periodetypeForYtelse O, E eller G
> * status IVERK eller AVSLU
> * vedtaksperiode som stemmer med perioden du er ute etter. Dersom til-dato ikke har verdi, betyr det at vedtaket fortsatt er gjeldende. Bruker kan ha hatt flere etterfølgende vedtak i løpet av de siste 78 dagene, så du kan ikke gå ut fra at ett vedtak dekker hele perioden, selv om det sikkert ofte gjør det.

det har og blitt nevnt: 

> trenger ikke å hensynta tidsbegrenset bortfall eller forlenget ventetid, fordi brukeren vil uansett ha et annet vedtak som går i paralllell med de vedtakene. Så det vi da er ute etter er til og med dato på vedtak og at det ikke er mindre enn 78 uker siden på det tidspunkt vi spør.
