### ISSUE TITLE
dp-graphql OOMer

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#341]
https://nav-it.slack.com/archives/CAEG6DW56/p1585595679010300?thread_ts=1585593393.010200&cid=CAEG6DW56

Fra tid til annen: 
```FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory```

https://grafana.adeo.no/d/000000283/nais-app-dashbord?orgId=1&var-interval=$__auto_interval_interval&var-datasource=prod-fss&var-app=dp-graphql&var-namespace=All&var-docker_image=81103ba&var-ingress_url=All&from=1584313200000&to=now

**Comment by gtcno** [comment]
https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas
