### ISSUE TITLE
Opprettet mekanisme som kaller på Behov i nye rapid-rivers kjeden i dp-saksbehandling

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#345]
Denne avhenger av https://github.com/navikt/dagpenger/issues/346 først 

For å kunne kalle opprette behov må det produseres i en topic fra dp-saksbehandling 

- [x] Avklare modell i dp-saksbehandling? (I #346 )
- [ ] Aktivitetslogg i fra spleis? Den blir brukt som mediator for å produsere behov
- [ ] Person, sak, vedtak - skal vi modellere dette ?

**Comment by geiralund** [comment]
Denne avhenger av #346 først

**Comment by androa** [comment]
Vi [lytter allerede på hendelsene](https://github.com/navikt/dp-saksbehandling/blob/master/saksbehandling-mediators/src/main/kotlin/no/nav/dagpenger/saksbehandling/hendelse/model/S%C3%B8knadMessage.kt) fra `dp-soknad-mottak` og setter i gang hele saksbehandlingsløpet i `dp-saksbehandling` så jeg lukker denne.
