### ISSUE TITLE
Specce opp modell for dp-saksbehandling

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#346]
Vi trenger å bygge opp en modell i dp-saksbehandling som gir oss knagger å henge data, hendelser, tilstander, og behov på.

**Comment by androa** [comment]
Arena baserer seg på:
- Person
- Sak
- Vedtak

Etter å ha fundert litt på det sammen med @geiralund så virker det som en logisk oppdeling.

**Comment by androa** [comment]
Grovt sett hvordan tilstandsmaskinene i Arena funker for nytt vedtak:

![image](https://user-images.githubusercontent.com/588046/78177379-54ff8080-745e-11ea-9d2b-876c8fa321a5.png)

Tilsvarende for intaktivering, stans og gjenopptak:

![image](https://user-images.githubusercontent.com/588046/78177422-69437d80-745e-11ea-9e54-a60203bdbb6c.png)

Grovt førsteforsøk for å tegne opp vår state:

![image](https://user-images.githubusercontent.com/588046/78177469-77919980-745e-11ea-8057-9c7034200c20.png)

```
@startuml

state Person {
    [*] --> SøknadMottatt

    state Ytelse {
        IYT -> DAGP
        DAGP -> IYT
    }
}

state Sak {
    state "Under behandling" as behandling
    Inaktiv -> behandling
    behandling -> Aktiv 
    behandling -> Inaktiv 
    Aktiv -> Inaktiv 
}

state Vedtak {
    SøknadMottatt --> Opprettet 
    state "Prøv inngangsvilkår" as inngang
    Opprettet --> inngang
    inngang -> Beregning
    inngang -> Avslag
    state "Fatt vedtak" as fatt
    Beregning -> fatt
    fatt -> Iverksatt
    Iverksatt --> [*]
    
    SøknadMottatt --> Inaktiv
    Opprettet -->Aktiv
    Iverksatt --> DAGP
}

@enduml
```

**Comment by geiralund** [comment]
Original confluence side https://confluence.adeo.no/pages/viewpage.action?pageId=296176590

**Comment by androa** [comment]
Vi har vel landet en slags modell her. Den er helt klart feil, men samtidig er den god nok til å komme igang med automatisering.
