### ISSUE TITLE
En tjeneste som kan sende nye søknader slik at dp-saksbehandling kan begynne behandling

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#351]
Vi trenger en tjeneste (dp-soknad-mottak?) der den  sender en subset av søknad på privat-dagpenger-behov-v2 rapid.
I tillegg lage en greie som sender samme meldig “on demand” for eksisterende søknader.

**Comment by gtcno** [comment]
> Vi trenger en tjeneste (dp-soknad-mottak?) der den sender en subset av søknad på privat-dagpenger-behov-v2 rapid.
> I tillegg lage en greie som sender samme meldig “on demand” for eksisterende søknader.

Tenker det er greit å bruke dp-soknad-mottak. Da er vi garanter at søknaden er persistert til db før vi starter prosessering. Dette er viktig fordi andre oppslags tjenester slår opp i datbasen for å legge på fakta til videre prosessering. 

Vi må bli enige om hva som skal legges på pakken.
