### ISSUE TITLE
Legge til oppgaveid fra Arena på innløpet

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#356]
Fra Arena

3:33 PM
Vet du tilfeldigvis om dere mottar oppgaveId i responsen når dere bestiller oppgave i Arena? Hvis jeg ser på riktig kode her, så ser det slik ut, men vi har vel flere tjenester for å opprette oppgave, så jeg vet ikke helt hvilken dere kaller?

3:33
Jeg må nemlig avslutte den oppgaven og selecten for å finne oppgaven er veldig treg..

3:34 PM
ah, jeg tror vi ikke tar vare på oppgave id

3:34 PM
så dersom dere har oppgaveId, hadde det vært strålende om den kunne sendes i request, så sparer vi noen sekunder

**Comment by Bendreas** [comment]
Hva er kontekst for dette? Er kanskje litt sent for automatisering av permittering?
