### ISSUE TITLE
Analyse: Søkere som har oppgitt mer enn 1 arbeidsforhold i søknaden

### ISSUE THREAD

**Issue by gorzan** [navikt/dagpenger#373]
Er det flere arbeidsforhold hos samme arbeidsgiver?
Er det stor avstand mellom "dato" på forholdene (typ sagt opp for tre år siden og permittert i går)
Er det ulik (slutt)årsak?

**Comment by androa** [comment]
Totalt antall søknader med flere arbeidsgivere: 27745
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Søknader med flere arbeidsforhold hos samme arbeidgiver: 12552 (45.24%)
Søknader med kun 1 arbeidsforhold per arbeidsgiver: 15908 (57.34%)
(Merk: disse tallene vil ha noe overlapp)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Antall søknader med nøyaktig 2 arbeidsforhold: 24479
Samme sluttårsak: 20672 (84.45%)
Ulik sluttårsak: 3807 (15.55%)
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Antall søknader med nøyaktig 2 arbeidsforhold og sluttdatoer
mellom 2000-01-01 og 2020-05-01: 21730
Antall med samme sluttdato: 12062 (55.51%)
Median datodiff (hvor datodiff != 0): 509 days 12:00:00
Mean datodiff (hvor datodiff != 0): 6757 days 10:25:16.259826
