### ISSUE TITLE
dp-regel-periode: Dagpengeperiode for lærlinger

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#374]
Lærlinger skal foreløpig ha en dagpengeperiode på 52 uker

- [x] Lese lærling parameter fra Packet
- [x] Beregne periode for lærling 
- [x] Putte resultatet på packet

**Comment by Bendreas** [comment]
Må sjekke hvilken periode som skal brukes om det er verneplikt og eller fangst/fisk

**Comment by Bendreas** [comment]
> Arbeids- og velferdsdirektoratet legger til grunn at regelen i § 4-15 om maksimal dagpengeperiode også gjelder lærlinger. Det innebærer at de fleste lærlinger gis 52 uker med dagpenger.

Ser ut som om periode forblir som før. Lukker dermed denne.

**Comment by geiralund** [comment]
Lærlinger skal ha 52 uker
