### ISSUE TITLE
Saksbehandling: Modellere og håndtere fakta/oppslage hendelse.

### ISSUE THREAD

**Issue by gtcno** [navikt/dagpenger#377]
FaktaInnhentet/FaktaInnhentetMessage må utvides til å dekke  de forskjellige dp-oppslag prosjektene.
FaktaInnhentet skal brukes til å avgjøre om en søknad skal sende til manuell behandling eller om den kan fortsette automatiserings proessess.

Se https://github.com/navikt/dp-saksbehandling/commit/432b243e8c492d2ff65af7193c45ea1b8f5b4cbf#diff-880b4806221b166f5aa31bfd18df510f  og 
https://github.com/navikt/dp-saksbehandling/blob/master/saksbehandling-model/src/main/kotlin/no/nav/dagpenger/saksbehandling/person/Sak.kt#L146
for eksempel 

dp-oppslag-*: 

- [x] dp-oppslag-arbeidsforhold
- [x] dp-oppslag-arbeidssøker
- [x] dp-oppslag-ytelser
- [x] dp-oppslag-virkningstidspunkt

- [ ] dp-oppslag-person <-- tror ikke vi trenger denne per nå, slik den er nå fungerer den mer som en regel uansett
- [ ] dp-oppslag-vedtak
- [ ] dp-oppslag-medlemskap <- dette er nok også en regel, krever beregningsdato

**Comment by androa** [comment]
I helga så lagde jeg noen flere tilstander i Vedtak for å støtte å fastsette beregningsdato/virkningstidspunktet før de reglene som krever det. Da ble denne ferdig/ting endra seg såpass at den ikke lenger gjelder.
