### ISSUE TITLE
Saksbehandling: Faktasjekk

### ISSUE THREAD

**Issue by gtcno** [navikt/dagpenger#378]
Legg til faktasjekk for å sende en søknad til manuelle behandling. 

Se https://github.com/navikt/dp-saksbehandling/blob/master/saksbehandling-model/src/main/kotlin/no/nav/dagpenger/saksbehandling/person/Sak.kt#L146

**Comment by androa** [comment]
Det gjenstår vel fortsatt ganske mye jobb på denne @gtcno? Det er jo flere fakta som må sjekkes for å filtrere de ut.

**Comment by gtcno** [comment]
Ja jeg slo sammen oppgavene i #377

**Comment by androa** [comment]
OK, da closer jeg denne.
