### ISSUE TITLE
Saksbehandling:  Lagre person i db.

### ISSUE THREAD

**Issue by gtcno** [navikt/dagpenger#384]
- [x] Database modell
- [x] Mapping fra intern modell til database modell
- [x] Lim

**Comment by androa** [comment]
Jeg vet ikke hvor mye du har fått sett på hva Helse gjør, men det er i stor grad oppsummert med:
```hentPerson(queryOf("SELECT data FROM person WHERE fnr = ? ORDER BY id DESC LIMIT 1", fødselsnummer))```

https://github.com/navikt/helse-spleis/blob/master/sykepenger-mediators/src/main/resources/db/migration/V1__initial_tables.sql

**Comment by gtcno** [comment]
> Jeg vet ikke hvor mye du har fått sett på hva Helse gjør, men det er i stor grad oppsummert med:
> `hentPerson(queryOf("SELECT data FROM person WHERE fnr = ? ORDER BY id DESC LIMIT 1", fødselsnummer))`
> 
> https://github.com/navikt/helse-spleis/blob/master/sykepenger-mediators/src/main/resources/db/migration/V1__initial_tables.sql

Jeg har sett på Helse.  Det  er nok riktigere å si at det er i stor grad oppsumert i https://github.com/navikt/helse-spleis/blob/master/sykepenger-model/src/main/kotlin/no/nav/helse/serde/SerialisertPerson.kt
