### ISSUE TITLE
Endringer mellom søknadstidspunktet og virkningstidspunktet - konkurs.

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#385]
Kan vi sjekke om arbg har gått konkurs i brreg? Er dette komplekst å gjøre?

**Comment by magnefjeld** [comment]
Snakket med Geir Vesterdal i dag om blant annet konkursåpning, og hvordan vi finner det.

Det er AA-registeret som setter i stor grad fixer dette nå. Når de får melding fra Enhetsregisteret om konkursåpning, så avslutter AA-registeret maskinelt arbeidsforholdet til den enkelte ansatte og det settes sluttdato på arbeidsforholdet. Dette er også sporbart, hvem som har satt arbeidsforholdet til avsluttet.
-	Tidligere var det bobestyrer som gjorde dette, ved at de sendte brev til NAV (AA-registeret).

Som Hovedregel skjer det pågående natt, men kan også gå 1-2 dager, om f.eks. konkurs åpnes på en fredag. Det er faktisk konkursdato som settes (konkursåpningsdatoen)

Konkurs åpnes på juridisk enhet, men det har vi uansett tilgang til. 

For automatisering, vil da annen logikk løse dette: Vi ser kun på aktive arbeidsforhold. Ved konkurs vil ikke bruker lenger ha et aktivt arbeidsforhold pga at AA-registeret maskinelt har satt en slutt dato.


I tillegg: I forbindelse med at NAV har levert på anmodningsvedtak om frilansere og selvstendig næringsdrivende, så ble det i mars 2020 levert slik at man på personnivå (f.nr) kan finne aktive roller i enhetsregisteret (dog ikke inaktive/historiske). Dette er utviklet av Team Registre, Under Anne Worren, av utvikler fra Visma: Reidar Lien. 

Ikke nødvendigvis for automatisering, men for å vise søker om dagpenger arbeidsforhold og hva de har av roller i ulike selskaper med videre, vil dette kunne være nyttig.

I tillegg, kan det være at vi også kan finne fram til bobestyrer, ved at vi vet hvilke person som søker dagpenger, arbeidsgiver er konkurs (les: AA-registeret har satt maskinelt sluttdato og informasjon om at dette er fordi det er konkurs, så kan man også sannsynligvis finne ny juridisk nummer opprettet for konkursboet og dermed også bobestyrer).
-	Vil være nyttig i søknader på sikt om dagpenger ved konkurs å kunne vise denne informasjonen til bruker. 

Det vil med andre ord si at om vi er riktig heldige, så er allerede https://jira.adeo.no/browse/REG-3530 / https://jira.adeo.no/browse/DIGIDAG-72 løst for oss:) Men det må sjekkes ut når vi har behov for det.
