### ISSUE TITLE
Analyse: Sjekke andel med oppgaver i Gosys etter søknad

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#387]
Vi må ta høyde for mulige endringer etter noen har søkt dagpenger. Det vil typisk komme inn som oppgaver i Gosys.

Vi vil vite hvor mange som har søkt dagpenger som har fått nye oppgaver i Gosys med tema DAG. @magnefjeld: Har du noe å tilføre?

Er det en høy andel så dukker det opp noen oppfølgingsspørsmål.

**Comment by magnefjeld** [comment]
Tenker at man også burde hensynta Arena-oppgaver, men de vil jo da være automatisk journalført i gosys. Men man vet jo ikke ut fra det om oppgaven fortsatt ligger i Arena. I gosys, vil det da mest sannsynlig være oppgaver under tema "Dagpenger", og da oppgavetype: "Journalføring", "Vurder henvendelse", "Vurder konsekvens for ytelse" og "Kontakt bruker". Journalføring er dokumenter/skjemaer/søknader, mens det andre er henvendelser/informasjon.
![image](https://user-images.githubusercontent.com/61459197/79845069-d347a680-83bc-11ea-806d-c4dd1c1f8261.png)
