### ISSUE TITLE
soknaddagpenger-server OOMer

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#388]
https://nav-it.slack.com/archives/CAHJ7634G/p1587321167132300

> 
> 3 tilfeller av OOM på 2 ulike poder rundt kl 20:32 med noen sekunders mellomrom. Det feiler i pdfbox ved konvertering til PNG ifm forhådsvisning. Jeg tipper det er en enkeltsøkers vedlegg som fører til for mye minnebruk ved konvertering i pdfbox slik vi har sett i sendsoknad tidligere. Vil dere se nærmere på det?
> 
> Bjørn Carlin:house_with_garden:  1 day ago
> Klarer ikke se noe problem med heap i appdynamics. Ser bare at det er brukt endel tid på hhv 3 og 5 major GC rundt kl 20:32, men ingen høy minnebruk. Så det virker som om det er disse enkelt-tilfellene i seg selv som krever for mye minne.
> 
> Bjørn Carlin:house_with_garden:  21 hours ago
> @geir.andre.lund @andre.roaldseth @giao.the.cung
> 
> Geir Andre Lund:house_with_garden:  20 hours ago
> Det er vanskelig å gjøre noe med de store vedleggene. Det eneste er å finne eller annet maksgrense for å gi til bruker at dette vedlegget(-ene) er for store
> 
> Bjørn Carlin:house_with_garden:  1 hour ago
> Det vi så med sendsoknad var at det var et fåtall tilfeller av enkelt-dokumenter som krevde ekstremt mye internt minne i pdfbox ved konvertering av PDF til PNG, og at minnebruken varierte endel med hvilken versjon av pdfbox som ble brukt. Det kan være en ide å forsøke å finne tilbake til dokumentet som fører til OOM og reprodusere feilen i testmiljø slik at man får sjekket om det er noe man kan gjøre med konfigurasjon eller annen tuning av pdfbox.
> 
> Geir Andre Lund:house_with_garden:  3 minutes ago
> Det kan være en idé, jeg vet ikke helt hvilken versjon av pdfbox vi bruker nå.
> Kan opprette en oppgave for det.
> Vi har beintøff prioritering akkurat nå og jobber med anmodningsvedtak og automatisering av dagpenger, så jeg redd det må vente hvis ikke det blir et daglig problem.
> :point_up_2:
> 1
> :dart:
> 1

**Comment by androa** [comment]
Dette er vel ikke lengre et issue, og målet må være å erstatte denne. Lukker, så får vi heller ta det opp igjen om det blir et problem.
