### ISSUE TITLE
Strukturerte data fra søknadsdialogen - tilgjengeliggjøres

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#395]
Det er behov for at faktaene/hva bruker har svart (unntatt fritekstfelt) i den digitale søknadsdialogen tilgjengeliggjøres. F.eks. via grafanabaords, amplitude e.l., slik at vi får kunnskap om hva dagpengesøkerne svarer.

Dette kan bidra til inn i produksjonsstyring i NAY, samt i automatiseringsarbeidet.

I tillegg er dette avgjørende for Kunnskapsavdelingen. Har vært i samtaler med Steinar Folkvord om dette. Legges dette f.eks. strukturert i en eller annen database, kafka el som Datavarehus kan koble seg på? Må naturlig nok gjøres en PVK.

Trellokort: https://trello.com/c/3HSQ32Jx/92-tilgjengelig-gj%C3%B8re-strukturerte-data-fra-s%C3%B8knadsdialogen

**Comment by androa** [comment]
Vi er nok ved veis ende her, vi kan lage mer spesifikke issues når det er relevant.
