### ISSUE TITLE
Næringskoder - Enhetsregisteret - Skille søknader om FISK fra PERM

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#396]
For i det hele tatt å klare skille de to permitteringsrettighetstypene fra hverandre, er det å hente informasjon om næringskoder på permitterende arbeidsgivere fra enhetsregisteret en mulighet. Om næringskode = X, så IKKE kandidat for automatisk behandling.

NAV har kopi av enhetsregisteret - [EREG](https://confluence.adeo.no/display/FEL/EREG).

Vi må da ha mulighet til å hente informasjon fra EREG.

se for øvrig: https://confluence.adeo.no/display/TDP/Automatiske+vedtak+om+dagpenger for mer informasjon om næringskoder og hvilke som vi har definert som ikke aktuelle kandidater for automatisk saksbehandling.

Eksempel arbeidsgiver med næringskode fra EREG: 
![image](https://user-images.githubusercontent.com/61459197/80388239-f1744180-88a9-11ea-817a-e0362e470c28.png)

**Comment by androa** [comment]
Det sies at ereg oppdateres sjeldnere enn brreg og har mindre data. Vi bør nok sannsynligvis integrere direkte mot brreg. Vi har noe som kalles brreg-proxy, men jeg er usikker på om det egentlig er nødvendig å bruke.

**Comment by magnefjeld** [comment]
@androa om man ikke kan benytte EREG eller brreg-proxy, må man da "bygge noe nytt"/etablere en ny tjeneste?

**Comment by androa** [comment]
Neida, det er hipp som happ :)
