### ISSUE TITLE
3. landsborgere -Identifisere

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#407]
Dagpengesøkere som er 3.landsborgere er ikke aktuelle for automatisering. Ref blant annet mulig forskrift rundt permitterte faglærte 3.landsborgere.

3. landsborgere må ha en eller annen form for arbeidstillatelse/oppholdstillatelse i Norge, og for å kunne få dagpenger må denne være av en slik art at bruker kan anses som reell arbeidssøker etter folketrygdloven § 4-5.

Vi har allerede informasjon tilgjengelig om hvilke land man er "statsborger" i via TPS når bruker søker dagpenger.

En annen ting er om denne allerede ivaretas av medlemssjekken til  P3 applikasjonen ?

**Comment by Bendreas** [comment]
https://confluence.adeo.no/display/FIP/Output+del+1+-+Prosesstegning+1.0++DEL+1+-+MVP+1
Punkt 1.2: sjekker om bruker er statsborger i Norge eller EØS. Det blir vel tilsvarende?

**Comment by Bendreas** [comment]
og videre punkt 1.7 og 1.8 her:
https://confluence.adeo.no/display/FIP/Output+del+3+-+Prosesstegning+1.0++DEL+3-+MVP+1

**Comment by magnefjeld** [comment]
da er det tilstrekkelig. Endret da litt på fakta vi trenger "Er søker EØS-borger ?" Norge er EØS-land. Om bruker er det, så er det kandidat for automatisering.
