### ISSUE TITLE
Ta i bruk og ha et bevisst forhold til Snyk.

### ISSUE THREAD

**Issue by gtcno** [navikt/dagpenger#412]
- [x] Sett opp og legge til prosjekter på snyk.io.
- [ ] Sette opp som en del av Intellij ?
- [x] Sette opp som en del av bygg?

**Comment by androa** [comment]
Nå er vel alle prosjektene på plass i Snyk, vi har eget team, og de blir sjekket on build.

Det går dog feil vei, vi øker i antall issues.

Jeg foreslår at vi begynner med "patch thursday" eller noe hvor alle fokuserer på å løse en eller flere issues i Snyk.
