### ISSUE TITLE
Lage akseptansetester for automatiseringsløpet ala det vi har i LEL

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#418]
Lage basic gjennomgang av saksbehandlingsløpet.

Første omgang sende en enkel søknad til manuell behandling

**Comment by atleno** [comment]
Blocked: dolly gir oss forskjellige aktørider i q0 og q1, og vi bruker inntektskomponenten i q0.
Dette på grunn av g-justering.

Trolig fikset: Vi har byttet inntektskomponent til q1

**Comment by atleno** [comment]
### Det som gjenstår/problemer:

Dolly trenger OIDC-token fra z-ident, så det funker ikke med systembruker.
Gjør det vanskelig å opprette testdata før vi kjører testen.

Vi kan bruke testpersoner som vi har laget på forhånd, men da må vi sende fnr rundt.

**I tillegg gir ikke dolly oss denne dataen:**

- Vedtak/sak i arena
- Arbeidssøkerstatus (fra arena)
- Søknadsdata

### Ett alternativ:
Vi lager riktig state i arena, og passer på at vi ikke endrer den når kjører testene.
Hvis dette går?
Aner ikke hvordan det blir med vedtak som går ut på dato og sånn

### Annet alternativ:
Vi returnerer mock-data isteden for å spørre Arena.

Enten ved å ha mock-data (inkludert fnr) i tjenestene, eller lage en mock-tjeneste som vi spør isteden for arena.
Eller noe lurere?

**Comment by Bendreas** [comment]
Kan vi legge fødselsnumrene i vault? Og deretter mocke vedtak/sak, arbeidssøkerstatus og søknadsdata

**Comment by androa** [comment]
Inntil Dolly støtter systembrukere og en bedre måte å provisjonere testdata så bør vi nok bruke "statisk" (les: manuelt) genererte brukere.

Jeg tror som @Bendreas nevner at det enkleste er å lagre fødselsnummerene i Vault og tilgjengeliggjøre de via environment-variabler.

Siden det blir "statiske" testdata så bør vi unngå å mutere tilstand i Arena (og andre plasser).
