### ISSUE TITLE
Avsjekk av må krav vi må ha i automatiseringsløpet

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#419]
Avsjekk mot "kravlisten" på  https://confluence.adeo.no/display/TDP/Automatiske+vedtak+om+dagpenger

**Comment by androa** [comment]
Den har vi vel nettopp gjort? :D 

Dette er det jeg har notert meg underveis:

- Sjekke at vi sjekker aktiv dagpengesak i Arena (#6)
- Sjekke at vi henter dp-oppslag-vedtak og sjekker at siste vedtaks til dato er minst 18 måneder gammelt fra virkningstidspunktet (#21)
- Mappe opp lærling i dp-oppslag-arbeidsforhold og sjekke dette (#7)
- Sjekke alder - må være mellom 18 og 67 ved virkningstidspunktet (#8, #9)
- Avsluttede arbeidsforhold må være kun ett 100% forhold (#12)
- Arbeidsforhold må være 100% stilling (#13)
- Permitteringsgrad må være minst 40% (#15)
- Hent permitteringsgrad fra a-ordning (#15)
- Sjekke næringskode for sjømat (#18)
- Sjekke om registrert som arbeidssøker tilbake i tid er ivaretatt (#20)
- Sjekke svaret på under utdanning fra søknad (#22)
- Sjekke svaret på egen næring fra søknad (#23, #24, #25)
- Sjekke svaret på andre ytelser fra søknad (#27) og utbetaling økonomisk goder (#34)
- Sjekke at kapittel 9 er inkludert i andre ytelser (#28) - evt. hvor må det sjekkes?
- Sjekke hva medlemskapstjenesten faktisk sjekker (#36)
- Sjekke at vi bruker EØS fra medlemskap
- Ikke sjekke skift/syklus/rotasjon (#35)
- Sjekke om det er oppgaver i gosys eller nye dokumenter i joark i automatisering (#38)
- Sjekke om bruker har svart ja på EØS i søknaden (#39)

Det er vel Best:TM: å lage separate issues for alt?

**Comment by androa** [comment]
Må også samkjøres med lista jeg har begynt på:
- Få dp-regel-periode til å svare nye behov med regel brukt (om Arena trenger det)
- Fikse SerDer så den funker med ny modell
- Utvide HendelseRecorder med alt som må lagres
- Finne ut hvordan vi bestemmer om vi skal lage nytt vedtak eller fortsette på et som finnes i sak - og i hvor stor grad vi trenger å løse det nå
- Opplese og vedta om vi sjekke alder, opphold og utestengt
- Opplese og vedta om vi trenger å sjekke tab av arbeidstid og inntekt når vi uansett bare tillater 1 forhold med 100% permittering
- Finne ut av rekkefølge på periode og sjekk/samordning av andre ytelser
- Få med sjekk av egen næring #420
- Finne ut hva vi gjør med lærling
- Gå gjennom og se om det er noe mer som må filtreres ut eller inn
- Lage en mekanisme som justerer rate vi automatiserer/skriver vedtak inn i Arena
- Fikse status av IARBS

Det er en del overlapp.
