### ISSUE TITLE
Sjekk at siste vedtak er minst 18 måneder gammelt

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#425]
Vi må bruke dp-oppslag-vedtak og sjekke at det siste vedtakets "til dato" er
minst 18 måneder eldre enn virkningstidspunktet.

Dette er (fakta #21 i lista)[https://confluence.adeo.no/display/TDP/Automatiske+vedtak+om+dagpenger]

**Comment by Bendreas** [comment]
erstattes av navikt/dagpenger#449
