### ISSUE TITLE
Filtrere ut alle sjømat basert register

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#430]
De som jobber i fiskeforedlingsbedrifter skal ha egen rettighetstype.

Vi bruker næringskoder fra brreg/ereg

Dette er [fakta #18 i lista](https://confluence.adeo.no/display/TDP/Automatiske+vedtak+om+dagpenger)

**Comment by tonjemjovik** [comment]
![Skjermbilde 2020-06-12 kl  10 57 24](https://user-images.githubusercontent.com/35685583/84484787-88029380-ac9b-11ea-88c0-9413d4ae3a0e.png)
