### ISSUE TITLE
Filtere ut alle som ikke oppfyller kravene til medlemskap

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#436]
- [x] Sjekke hva medlemskapstjenesten faktisk sjekker (#36)
- [x] Verifisere medlemskapstjenesten filtrerer ut de med EØS-saker (#39)
- [x] Legge ut behov om medlemskap i dp-saksbehandling
- [x] Filtrere bort alle som ikke er ja i dp-saksbehandling

Dette er (fakta #36 og #39 i lista)[https://confluence.adeo.no/display/TDP/Automatiske+vedtak+om+dagpenger]

**Comment by Bendreas** [comment]
**Søker er EØS-borger (fakta nr. 3)** 
Tjenesten sjekker at bruker både er [norsk statsborger](https://confluence.adeo.no/pages/viewpage.action?pageId=358576585) samt at [bruker er statsborger i et EØS-land. ](https://confluence.adeo.no/pages/viewpage.action?pageId=358576556) Overkill å sjekke begge deler, men gjør jo ingenting for oss.

**Utenlands bostedsadresse (fakta nr. 29)**
[Sjekker om bruker er folkeregistrert som bosatt i Norge og har vært dette i siste 12 måneder](https://confluence.adeo.no/pages/viewpage.action?pageId=358576589)

**Utenlands oppholdsadresse (fakta nr. 30)**
Ser ikke ut som dette nødvendigvis sjekkes, klarer ikke helt forstå om det dekkes av punktet over. Hva er relevansen av utenlands oppholdsadresse? 

**Medlemskap i folketrygden (fakta nr. 36)**
Ja.

**Bor i et annet EØS-land og arbeider eller har arbeidet i Norge (fakta nr. 39)**
Jeg mener dette dekkes implisitt av pkt om at bruker er folkergistrert som bosatt i Norge og har vært dette i siste 12 måneder.

**Comment by Bendreas** [comment]
dp-saksbehandling legger vel enda ikke ut behov om medlemskap, men det er kanskje egen lapp.

**Comment by magnefjeld** [comment]
Tenker at fakta 3 og fakta 39 ivaretas av medlemskapsfunksjonen til P3. Så da trenger vi ikke sjekke de to faktaene et annet sted.

Når det kommer til fakta 29 og 30, så tenker jeg at vi sjekker disse via PDL (helt/delvis overlappende med P3-funksjonen). Ser ikke ut som P3-funksjonen her er fullstendig utbygd ennå: ref: https://confluence.adeo.no/pages/viewpage.action?pageId=358576589

Har oppdatert på: https://confluence.adeo.no/display/TDP/Automatiske+vedtak+om+dagpenger

Ser det ut som en grei avklaring @Bendreas ?
