### ISSUE TITLE
Virtuelle køer for egne ansatte- dagpenger og AAP - Estimering

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#447]
Fra Tonje i Team Arena:
Prosjekt skjerming av egne ansatte vurderer å lage virtuelle køer for behandling av ytelser for egne ansatte/familie (dagpenger og AAP i Arena). Elin er tidligere informert om dette, men ba om ro pga. korona. Nå er vel situasjonen litt mer normalisert. 

Som du ser har Arena gjort en grovanalyse av hva som vil være nødvendige endringer i Arena. Det er nok også nødvendig at det gjøres endringer på deres side hvis dette skal gjennomføres. Jeg forstår det sånn at dette ikke er endelig bestemt ennå.

Ref.: https://trello.com/c/ryFsdbaf/94-virtuelle-k%C3%B8er-for-egne-ansatte-dagpenger-og-aap-estimering

**Comment by magnefjeld** [comment]
All nødvendig info ligger på trello-kortet. 
På https://jira.adeo.no/browse/ARENA-4240 ligger all nødvendig informasjon fra Team Arena (grovestimat + eventuell oppstart). Fint om noen i teamet vårt har mulighet til å se på denne i løpet av juni og tilbakemelde til team Arena ved Tonje

**Comment by Bendreas** [comment]
Grovestimat: to uker. 
Vi må skrive om til å bruke PDL i innløpet (gå vekk fra vår nåværende graphQl), deretter må vi legge inn logikk som ruter til riktig kø avhengig av hva PDL gir oss.

**Comment by tonjemjovik** [comment]
Slå opp i norg ?

**Comment by Bendreas** [comment]
Riktig! Vi må nok fortsatt skrive om til å bruke PDL, da. Estimatet består.

**Comment by magnefjeld** [comment]
så bra denne er løst:) men jeg forsøker å finne svaret dere har sendt til Tonje i Team arena. Hvor ligger det?
@Bendreas
