### ISSUE TITLE
Faktasjekk: Er innvilget lønnskompensasjon?

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#450]
Finner da siste dag med lønnskompensasjon og kan innvilge dagpenger under permittering fra virkedagen etter (mandag-fredag)

Dette er [fakta 42 og 44 i lista](https://confluence.adeo.no/display/TDP/Automatiske+vedtak+om+dagpenger)

**Comment by geiralund** [comment]
Lønnskompenasjonsordningen har vedtakene på kafka
- [x]  [https://github.com/navikt/permittering-refusjon-iac](https://github.com/navikt/permittering-refusjon-iac) == inneholder kafka topics for lønnskompensasjonsordningen
- [x]  [https://github.com/navikt/permittering-refusjon-api](https://github.com/navikt/permittering-refusjon-api) == appen som spruter ut topicene

notion møtereferat: https://www.notion.so/33bea576588e443991d52bbd8a4b8642?v=5c0e80f363974e93a9e81760f97ccd03&p=9ee0f0b21b9545a1a13300da784bc699

**Comment by magnefjeld** [comment]
@geiralund 
Snakket litt med Ingeborg (som er med fra fagsiden i lønnskompensasjonsordningen). Tror at for å finne riktig virkningstidspunkt for dagpenger under permittering, er det å finne ut når permitteringen er iverksatt (les: første lønnspliktdag), og telle 20 virkedager (mandag-fredag), for så å finne dag 21 (les: virkningstidspunktet for dagpenger) det som er "veien". 

I og med at lønnskompensasjonsordningen også er en en refusjonsordning for arbeidsgiver, så er det å bruke første lønnspliktdag som referansepunkt det sikreste.

Uansett kan vi sikkert få over flere datoen/fakta fra lønnskompensasjonsordningen, men første lønnspliktdag må være en av dem:)

**Comment by geiralund** [comment]
Ref  [fakta 44 i lista](https://confluence.adeo.no/display/TDP/Automatiske+vedtak+om+dagpenger)

> VI har informasjon om når bruker har sendt søknaden, når registrert seg og hva siste dag i lønnskompensasjonsordningen er. Dersom bruker fyller vilkårene fra et senere tidspunkt enn virkedagen etter utløpet av lønnskompensasjonsordningen, er ikke søknaden en kandidat for automatisering.
