### ISSUE TITLE
Tekstelement - Innvilgelse - skal sendes over til Arena

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#452]
Ved innvilgelse har vi behov for å begrunne hvorfor vi har innvilget bruker dagpenger nettopp fra det tidspunktet vi har valgt. Løsningen som Arena har utviklet i forbindelse med automatisering åpner opp for at digidag kan sende over tekstelement som skal med i vedtaket. Vil da legge seg i Arena, tilleggsbegrunnelse, under "fastsett utfall ..". (Espen sjekket opp 4. juni 2020)

@ChrisdeVriesEnger og @magnefjeld lager utkast til tekstelement og klarspråker og oversetter dette til nynorsk.

1. Dette betyr også at digidag må vite om det det skal sendes informasjon på bokmål eller på nynorsk. Har vi info om dette? Eget kort?

**Comment by ChrisdeVriesEnger** [comment]
@magnefjeld - Forslag fra Eva :

"Du får dagpenger fra dagen etter at lønnskompensasjonen din stanser. Du får ikke dagpenger lørdag og søndag.

Dette har vi gjort ut ifra opplysningene vi har fått fra arbeidsgiveren din. 

Vedtaket er gjort etter folketrygdlovens § 4-3 1.ledd."


Hvis det virker ok, så sender jeg det til Marianne for nynorskifsering.

**Comment by magnefjeld** [comment]
@ChrisdeVriesEnger ser greit ut. Send til Marianne for Nynorskversjonering:)

**Comment by ChrisdeVriesEnger** [comment]
Fra Marianne :

"Du får dagpengar frå og med dagen etter at du har fått lønnskompensasjon. Du får ikkje dagpenger laurdag og søndag.
 
Vi har tatt utgangspunkt i opplysningar frå arbeidsgivaren din.
 
Vedtaket er gjort etter folketrygdlova § 4-3 1.ledd."

**Comment by magnefjeld** [comment]
22. juni 2020 endringer i tekst i tekstelementet vi skal sende over:

**Bokmål:**

Du kan ikke få dagpenger for samme periode som du skal ha lønnskompensasjon. Du får derfor dagpenger fra dagen etter at perioden med lønnskompensasjon er avsluttet. 
Det er din arbeidsgiver som har gitt NAV informasjon om perioden du har rett til lønnskompensasjon. 
Du får ikke dagpenger for lørdager og søndager.

**Nynorsk:**
Du kan ikkje få dagpengar for same perioden som du skal ha lønnskompensasjon. Du får derfor dagpengar frå dagen etter at perioden med lønnskompensasjon er avslutta. 
Det er arbeidsgivaren din som har gitt NAV informasjon om perioden du har rett til lønnskompensasjon. 
Du får ikkje dagpengar for laurdagar og søndagar.
