### ISSUE TITLE
Innsikt - Hvor mange har i søknadsdialogen svart at de er permittert fra fiskeindustrien ?

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#454]
Vi har fått en bestilling fra ASD vedrørende permitterte fra fiskeforedling- og fiskeoljebedrifter. 

27. april leverte vi en endring i søknadsdialogen, hvor vi nettopp spør brukrer om de er permittert fra en slik type virksomhet.

**Behov: Er det mulighet for å få oversikt over totalt antall brukere som har krysset av på dette i søknaden, i perioden 27. april til 7. juni?**

![image](https://user-images.githubusercontent.com/61459197/84025028-2f758280-a98b-11ea-97b1-7ee9c675234d.png)

**Comment by gtcno** [comment]
Jeg fant 518 stk. 


select count(*) from v1_soknad where exists ( select 1 from jsonb_array_elements(data->'fakta') elem where elem->'key' @> '"arbeidsforhold"' and  elem->'properties'->'fangstogfiske' @> '"true"');
 count 
-------
   518

**Comment by magnefjeld** [comment]
@gtcno Oppfølgingsspørsmål, så jeg ikke blir forvirret. fangstogfiske er det det man har kalt det nye faktumet for "Jeg er permittert fra en fiskeforedlings- eller fiskeoljebedrift"?

**Comment by gtcno** [comment]
> @gtcno Oppfølgingsspørsmål, så jeg ikke blir forvirret. fangstogfiske er det det man har kalt det nye faktumet for "Jeg er permittert fra en fiskeforedlings- eller fiskeoljebedrift"?

Ja.
