### ISSUE TITLE
Sende over tekstelement om innvilgelse på riktig målform til Arena

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#455]
Ref. https://github.com/navikt/dagpenger/issues/452 (tekstelement på nynorsk og bokmål)

Ved innvilgelse av automatiske vedtak om dagpenger under permittering må vi sende over et tekstelement til Arena, som da kommer med i vedtaksbrevet, som begrunner virkningstidspunktet. 

Dette bør sendes over på brukers valgte målform.

**Comment by Bendreas** [comment]
Vi har foreløpig ingen oppslagstjeneste som gir oss målform. Er blitt laget en [jira-sak](https://jira.adeo.no/browse/REG-8616) for å eksponere dette fra KRR via DKIF

**Comment by magnefjeld** [comment]
ideelt sett vil vi gjerne ha riktig målform, men ikke noen showstopper om vi ikke klarer å få det til før vi går på lufta med en MVP. Da sender vi bare på bokmål. Men fint å gå opp og se om vi kan få riktig målform. Om det er noen hindre, så si ifra, så løfter vi det:)

**Comment by magnefjeld** [comment]
22. juni 2020 endringer i tekst i tekstelementet vi skal sende over. Kan @Bendreas du se på denne?

**Bokmål:**
Du kan ikke få dagpenger for samme periode som du skal ha lønnskompensasjon. Du får derfor dagpenger fra dagen etter at perioden med lønnskompensasjon er avsluttet.
Det er din arbeidsgiver som har gitt NAV informasjon om perioden du har rett til lønnskompensasjon.
Du får ikke dagpenger for lørdager og søndager.

**Nynorsk:**
Du kan ikkje få dagpengar for same perioden som du skal ha lønnskompensasjon. Du får derfor dagpengar frå dagen etter at perioden med lønnskompensasjon er avslutta.
Det er arbeidsgivaren din som har gitt NAV informasjon om perioden du har rett til lønnskompensasjon.
Du får ikkje dagpengar for laurdagar og søndagar.

**Comment by Bendreas** [comment]
@magnefjeld Kan du konkretisere litt hva jeg skal se på?

**Comment by magnefjeld** [comment]
hei. vi har bare endret til på innholdet i tekstelementet (begrunnelse for virkningstidspunktet), så da må dere vel oppdatere slik at det teksten oppdateres.

Var det oppklarende?

**Comment by Bendreas** [comment]
Ja, det var det
