### ISSUE TITLE
Sjekke at bruker ikke er sykemeldt

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#456]
Krav 46. Er bruker sykemeldt ?

Krav 28 fanger opp om bruker mottar en annen ytelse (Arena/Infotrygd), men den fanger ikke opp helt/delvis sykemeldte, som ennå ikke mottar noen ytelse.

Om bruker er sykemeldt, så er ikke søknaden en kandidat for automatisering pga samordning/skal ikke ha ytelse.

**Comment by androa** [comment]
Pratet med @tiafiring, de kan tilby et endepunkt hvor vi kan angi fnr + dato og få svar på om personen har en sykemelding for den datoen.

Det blir en RESTish-tjeneste i FSS med *Azure AD Auth* for en servicebruker hvor vi angir fnr + dato.

Vi sender en POST med body:
```json
{
  "fnr": 123,
  "dato": "dato"
}
```

**Comment by androa** [comment]
>Vi vet jo bare om hvilke sykmeldinger en person har fått og om brukeren har sendt den til arbeidsgiver, evt avbrutt den. Det er først når brukeren har fylt ut søknad om sykepenger at NAV vet hvilke dager brukeren var syk og om de jobbet noe i sykmeldingsperioden. Altså: En person kan ha en sykmelding, men likevel jobbe fullt.
>
>Og i motsatt tilfelle: NAV mottar fortsatt 400 000 sykmeldinger i året på papir fra sykehusene. Ca 40% av disse klarer vi å tolke maskinelt og få lagt inn i databasen vår, resten punches for tiden manuelt inn i Infotrygd og havner aldri i vårt register (vi jobber med en løsning som gjør at de havner i vårt register i tillegg til Infotrygd når de punches manuelt). Brukeren kan altså ha papirsykmeldinger som vi ikke vet om. Også når papirsykmeldingen lar seg tolke maskinelt vil det være noen dagers forsinkelse siden disse mottas via vanlig post (på papir).

Konklusjonen er at fram til det finnes et nytt mottak for sykepenger, så treffer vi bredest (men med fare for flere falske positive) om vi sjekker om det finnes noe journalført under tema `SYM`.

**Comment by magnefjeld** [comment]
Tenker at dette må vi sjekke både på virkningstidspunktet og på det automatiske sakbehandlingstidspunktet (les: dagen vi lager det automatiske vedtaket), om mulig.
