### ISSUE TITLE
Avvikling av beregningsregler relatert til covid-19-utbruddet

### ISSUE THREAD

**Issue by espenjohansen** [navikt/dagpenger#465]
Beregningsreglene som ble innført fra 20.03.2020 utgår senest 31.12.2020. Vi må da endre tilbake til opprinnelige beregningsregler fra en bestemt dato. 
Det gjelder følgende regler:
1. Midlertidig krav om minsteinntekt – 0,75 G siste 12 md/2,25 G siste 36 md 
2. Økt kompensasjonsgrad for inntekt inntil 3 G (80 prosent) 
3. Kompensasjonsgrad 100 prosent av lønnen inntil 1,5 G for lærlinger, samt unntak for minsteinntektskravet

Vi skal da tilbake til ordinære beregningsregler fra 1. januar 2021 (evnt fra 1. november 2020). De midlertidige beregningsreglene relatert til korona skal fortsatt gjelde dersom ny beregning utføres med beregningsdato i perioden for unntak (fra 20.03.2020 til 31.10.2020 / 31.12.2020)

**Comment by geiralund** [comment]
Det er allerede en sluttdato implementasjon for disse reglene (pt er det 31.12.2020). Det skal bare være å eventuelt endre sluttdato som må gjøres. 

Lærling vil da beregnes etter "ordinær" ikke sant?

**Comment by espenjohansen** [comment]
Lærling vil mest sannsynlig bli terminert når sluttdato nås. Så de skal kun mottat lærlingedagpenger i "koronaperioden". De må da eventuelt søke ordinære dagpenger etterpå

**Comment by geiralund** [comment]
Skrevet et svar her også https://www.notion.so/Avvikling-endring-av-koronas-rregler-for-minsteinntekt-dagsats-og-s-rregler-for-l-rlinger-i-Digidag-3d1fd5e315fb4018952388687c429662

**Comment by magnefjeld** [comment]
@geiralund 

hei:) Denne er gammel, så dette kortet kan vel lukkes ?

Vi har etter at dette kortet ble laget ivaretatt de fleste endringene på andre kort eller i form av til og med datoer i digidag.

Så da kan den vel lukkes ?

**Comment by magnefjeld** [comment]
@geiralund hei:) kan denne lukkes ?

**Comment by magnefjeld** [comment]
@geiralund hei:) denne kan vel lukkes ?
Ivaretas av andre kort som jeg har opprettet.

**Comment by geiralund** [comment]
Denne kan lukkes, ivaretas av andre kort.
