### ISSUE TITLE
La vedtak kobles mot søknadsid i dp-saksbehandling for å ha sporbarhet i hele verdikjeden

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#468]
Ny søknad bør føre til nytt vedtak, samme vedtak bør lenkes til søknad for sporbarhet. 

Akseptansetester må mulig gjøres noe med.

**Comment by geiralund** [comment]
i Vedtak i dp-saksbehandling

```
   internal fun håndter(søknad: Søknad): Boolean {
        // TODO: denne må faktisk sjekke om søknaden kan kobles på eksisterende vedtak
        kontekst(søknad)
        tilstand.håndter(this, søknad)
        return false
    }
```

bør returnere `true` hvis vedtak allerede finnes på søknad

**Comment by Bendreas** [comment]
For akseptansetestene må vi da generere søknadsId i dp-saksbehandling-funksjonelle-tester samt endre i dp-oppslag-soknadfakta. Nå legger den inn søknader i databasen med flyway. Det jeg tenker vi kan gjøre enten
* mocke vekk hele oppslaget i databasen eller
* bruke [denne funksjonen ](https://github.com/navikt/dp-oppslag-soknadfakta/blob/1a30eb043885f3eeda7f085778139ef9f75d0ec7/src/main/kotlin/no/nav/dagpenger/oppslag/soknadfakta/postgres/S%C3%B8knadStorePostgres.kt#L15) for testbrukerne i dev

Eller noe smart jeg ikke har tenkt på.

**Comment by androa** [comment]
navikt/dp-saksbehandling#47 vil kunne brukes til å tvinge gjennom en ny behandling på en allerede behandlet søknadsId.

Bare sett feltet `tvingNyBehandling` til `true` så skal'n fly gjennom.
