### ISSUE TITLE
Fullføre mapping fra løsning til Arena-format

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#469]
I `dp-arena-sink` gjøres det en mapping fra våre løsninger til en datamodell Arena forventer.

Det er gjort en tynn initiell implementasjon her: https://github.com/navikt/dp-arena-sink/blob/master/src/main/kotlin/no/nav/dagpenger/arena/sink/serder/RequestMapper.kt

Den må fylles ut med ALT Arena forventer :)

Felter som må mappes opp for Arena. For at dette skal funke så tror jeg vi må oppdatere litt underveis når vi tar et felt.

- [x] vedtaksperiode - kun FOM er nødvendig
  - @geiralund 
  - Status: Ferdig! ~I PR  https://github.com/navikt/dp-arena-sink/pull/4~
- [x] taptArbeidstid
  - @Bendreas 
  - Status: Ferdig! ~I PR https://github.com/navikt/dp-arena-sink/pull/6~
- [x] dagpengerperiode
- [x] reellArbeidssoker
  - @gtcno 
- [x] permittering
  - @androa 
- [x] vilkaar
- [x] saksbehandlersTilleggsbegrunnelseForVedtaket 
  - @androa 
  - Status: Ferdig

Felter som utgår i MVP:
- [x] barnListe
- [x] arbeidsforholdListe
- [x] andreOkonomiskeYtelserListe
- [x] beregningsdato
- [x] godkjenningerReellArbeidssoker
- [x] beregningsregler
- [x] arbeidsperiodeFraEosNorden
- [x] bruktInntektsperiode
- [x] saksbehandlersTilleggsbegrunnelseForVedtaket

**Comment by geiralund** [comment]
Avhengig av #472

**Comment by androa** [comment]
Da mangler vi vel å få trukket ut fastsatt arbeidstid fra #472. Men vi bør/kan nok begynne å teste dette opp mot Arena nå?
