### ISSUE TITLE
Validere om siste lønnskompensasjonsdato er etter kalkulert virkningstidspunkt.

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#470]
> Har vi en sjekk her (kanskje overkill gitt de andre faktane vi sjekker, herunder registrert som arbeidssøker) om at dag 20 (som i den ideelle verden er siste dag lønnskompensasjonen omfatter) alltid faktisk er siste dag med opplyst lønnskompensasjon?
> vi vet at det kan være tilfeller hvor permitteringen er over før "dag 21".

(I Virkningstidpunktfastsatt melding i dp-saksbehandling)

**Comment by magnefjeld** [comment]
https://github.com/navikt/dagpenger/issues/450 hva får vi informasjon om her fra lønnskompensasjonsordningen?

A.	Har vi føre dag permitteringen gjelder i fra? (Det vil si dag 1)
B.	Har vi første dag lønnskompensasjonen løper? (Det vil si dag 3)
C.	Har vi siste dag lønnskompensasjonen løper? (Det vil si dag 20)

Om vi regner oss fram til dag 21 (det vil si virkningstidspunktet for dagpenger under permittering), basert B, vil vi i de aller fleste tilfeller treffe slik vi skal, Men det kan være en ide å legge inn en sjekk om at siste dag med lønnskompensasjon (dag 20), stemmer overens med telling «vi gjør». Så vil alltid får laget vegg-i-vegg vedtak med lønnskompensasjonsordningens vedtak

Vedtaksbrev lønnskompensasjons – eksempel: 	
https://navno.sharepoint.com/sites/enhet-kontaktsenter/Delte%20dokumenter/Forms/Alle%20filer.aspx?id=%2Fsites%2Fenhet%2Dkontaktsenter%2FDelte%20dokumenter%2FVedtaksbrev%20personbruker%20innvilget%208%2E%20juni%20%281%29%2Epdf&parent=%2Fsites%2Fenhet%2Dkontaktsenter%2FDelte%20dokumenter&p=true&originalPath=aHR0cHM6Ly9uYXZuby5zaGFyZXBvaW50LmNvbS86Yjovcy9lbmhldC1rb250YWt0c2VudGVyL0VielVmOWVsWVFsSmlCbUlJS3pPaTZBQlZaYmRxTUE5NXVySTVNTTZGdUNGWGc_cnRpbWU9aHZwdzVNZ08yRWc

 
Startdato permittering (dag 1): 2020‑03‑30
Sluttdato periode (dag 20): 2020‑04‑24
