### ISSUE TITLE
Verifisere at avslag/avbrutt også er inkludert i sjekken om eksisterende vedtak

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#474]
Verifisere at vi også fanger opp avslag og avbrutte vedtak.

Siden deler av korona-bunken med søknader er blitt behandler, må vi passe på at vi ikke behandler en avslått/avbrutt søknad på nytt

**Comment by Bendreas** [comment]
Disse er egentlig ikke med i sjekken (grunnet buggy tjeneste), men tjenesten vi bruker for å spytte informasjon tilbake til arena håndterer behovet. Referer til slacktråd med arenagjengen:

> Dersom man forsøker å behandle en søknad som allerede er behandlet i Arena, vil ikke Arena finne noen oppgave å knytte vedtaket til, siden ferdigbehandlede oppgaver slettes i Arena. Man vil da får HTTP 422 Vedtak kan ikke opprettes. Dette basert på valideringen "Det finnes én og bare én oppgave av typen "Start vedtaksbehandling" for gitt fødselsnummer og sak-id."
Dersom man forsøker å opprette vedtak i en sak som allerede har et vedtak, vil man også få HTTP 422 Vedtak kan ikke opprettes. Men denne gangen basert på valideringen "Det finnes ingen vedtak på saken".
