### ISSUE TITLE
Akseptansetester: fjerne ferdige podder

### ISSUE THREAD

**Issue by Bendreas** [navikt/dagpenger#485]
Vi har satt på ttl på jobben, som egentlig skal slette poddene når jobben er ferdig, men dette fungerer ikke. 

Hvis ikke dette går må vi kanskje hive ut en cronjob som rensker opp innimellom

**Comment by androa** [comment]
Jeg har fått høre på øret av @gtcno at dette er løst og funker: https://nav-it.slack.com/archives/CCP6QNBSN/p1596045279108800?thread_ts=1596022105.103500&cid=CCP6QNBSN

Lukker denne til det motsatte er bevist :)
