### ISSUE TITLE
Kjøre automatiske User Acceptance Tester mot inntekts-reglene

### ISSUE THREAD

**Issue by nicokk** [navikt/dagpenger#49]
Vi skal ha integrasjonstester for flyten i innløpet. Vi må finne ut hvor og hvordan vi skal sette opp disse, og så faktisk lage dem.

**Comment by geiralund** [comment]
Problemer med å kalle dp-regel-api-arena-adapter fra iapp til preprod. Maa finne en løsning der først.

**Comment by androa** [comment]
Denne er jo fiksa!
