### ISSUE TITLE
Bugs som følge av test i prod

### ISSUE THREAD

**Issue by gtcno** [navikt/dagpenger#493]
- [x] Purge historikk til dp-oppslag-soknadsfakta

- [x] Virkningstidspunkt må beregnes fra hva som er oppgitt i aa-reg, ikke permitteringsdag i søknaden

**Comment by geiralund** [comment]
Fant også https://github.com/navikt/dp-saksbehandling/commit/1560858a867361b8f9e94e02a01a9fc255e1c08c
