### ISSUE TITLE
Telle antall vedtak og tilstandene

### ISSUE THREAD

**Issue by tonjemjovik** [navikt/dagpenger#498]
Få opp telling på antall vedtak og tilstandene (til Grafana)

**Comment by androa** [comment]
Lagt til telling i navikt/dp-doh@99332148a740c7449e6dc0ecb0950af2dbb0e153

**Comment by androa** [comment]
Begynt på en visualisering her i https://grafana.adeo.no/d/QGnD4iGGz/team-dagpenger-saksbehandling, men trenger mer data for å tune den. Tar det underveis.
