### ISSUE TITLE
dp-arena-sink: 422 mot Arena

### ISSUE THREAD

**Issue by gtcno** [navikt/dagpenger#500]
{"@timestamp":"2020-06-28T12:02:48.113+02:00","@version":"1","message":"Failed to create vedtak 01EBX5TJ6W25GCMY9JKQN5KXX5 for søknadsId 1000V3XMN","logger_name":"no.nav.dagpenger.arena.sink.ArenaVedtakHandler","thread_name":"main","level":"ERROR","level_value":40000,"stack_trace":"io.ktor.client.features.ClientRequestException: Client request(https://arena-ords.nais.adeo.no/arena/api/v1/dagpenger/vedtak) invalid: 422 Unprocessable Entity\n\tat io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:35)\n\tat io.ktor.client.features.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invoke(DefaultResponseValidation.kt)\n\tat io.ktor.client.features.HttpCallValidator.validateResponse(HttpCallValidator.kt:37)\n\tat io.ktor.client.features.HttpCallValidator$Companion$install$2.invokeSuspend(HttpCallValidator.kt:99)\n\tat io.ktor.client.features.HttpCallValidator$Companion$install$2.invoke(HttpCallVal

**Comment by Bendreas** [comment]
Dette er ikke nødvendigvis en bug forresten, 422 skal bety at person/sak/vedtak er i en tilstand som ikke lar seg endre. Kunne jo vært bra med en tydeligere feilmelding fra Arena

**Comment by gtcno** [comment]
> Dette er ikke nødvendigvis en bug forresten, 422 skal bety at person/sak/vedtak er i en tilstand som ikke lar seg endre. Kunne jo vært bra med en tydeligere feilmelding fra Arena

Det er godt mulig, men burde uansett se på hvorfor Arena gir 422.  Er dette et gyldig case? 
Kan være knyttet til en persom som  fikk gjennom 2 søknader til Arena  via dp-saksbehandling.   I Arena dukket det imidlertidig kun opp et vedtak. Hør med Magne om fnr.

**Comment by Bendreas** [comment]
Spurte arena-folket: "Ser at samme sak-id er kjørt to ganger rett etter hverandre. Andre gangen tjenesten kalles er oppgaven ferdigbehandlet, derfor gis det en feil." Hva kan ha gjort at vi gjorde to kall rett etter hverandre?

**Comment by geiralund** [comment]
Ser ut til at denne er sent to ganger gjennom for samme person
Først vedtakid 01EBX5THYVYAB0XPWFXXEA8APH
deretter  01EBX5TJ6W25GCMY9JKQN5KXX5

**Comment by Bendreas** [comment]
Da må vel tvingNyBehandling blitt satt til true? Mulig å sjekke dette noe sted?

**Comment by Bendreas** [comment]
https://github.com/navikt/dp-spill-av/blob/abd5a692f84d455ea1c38dde323b92da4a0572c9/src/main/kotlin/no/nav/helse/spillav/S%C3%B8knad.kt#L14

**Comment by Bendreas** [comment]
Ja, dp-spill-av har sendt søknaden to ganger. https://logs.adeo.no/goto/ea962b486dcc837e91655823f2ced506 

Årsaken til dette vet jeg ikke, men tenker denne kan lukkes. Det at arena gir denne feilmeldingen ser riktig ut i dette tilfellet.
