### ISSUE TITLE
Sjekke om søknaden behandles er søknad under permittering (Fastsette rettighetstype)

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#508]

**Comment by androa** [comment]
Det er vel strengt tatt noe sånt som å fastsette rettighetstype, men det er nok en større greie på sikt. Jeg tror det bør bli en egen tilstand. På sikt.

**Comment by geiralund** [comment]
Ja, enig. Er det er behov som `FastsettRettighetstype` først som sist?

**Comment by androa** [comment]
Yep! 👍

**Comment by geiralund** [comment]
reverterte i 
3 new commits pushed to master
b072111d - Revert "Logg resultat av fastsetting av rettighetstype"
3b957d62 - Revert "Legge til FastsettRettighetstypeLøsningService til appen :-|"
b8c697f8 - Revert "Finne rettighetstype fra søknad"
<https://github.com/navikt/dp-oppslag-soknadfakta|navikt/dp-oppslag-soknadfakta>navikt/dp-oppslag-soknadfakta

**Comment by geiralund** [comment]
og 


7dc476a1 - Revert "Behov FastsettRettighetstype for å bestemme rettighetstype for vedtaket"
<https://github.com/navikt/dp-saksbehandling|navikt/dp-saksbehandling>navikt/dp-saksbehandling

**Comment by geiralund** [comment]
Søknadsdata gir ikke riktig i forhold til type rettighet (nav skjemanummer på søknad er feil)
