### ISSUE TITLE
Åpne for automatisering av de som søker barnetillegg

### ISSUE THREAD

**Issue by tonjemjovik** [navikt/dagpenger#513]
Undersøke mulighetene for å kunne sjekke om den andre personen med foreldreansvar har også søkt dagpenger eller fått vedtak om dagpenger.

**Comment by androa** [comment]
Vi må huske å mappe opp barn inn til Arena her: https://github.com/navikt/dp-arena-sink/blob/master/src/main/kotlin/no/nav/dagpenger/arena/sink/serder/RequestMapper.kt#L61
