### ISSUE TITLE
Redusere perioden vi sjekker for flere søknader

### ISSUE THREAD

**Issue by androa** [navikt/dagpenger#526]
Se bort fra andre søknader om dagpenger som har kommet inn i inntil 14 dager etter at første digitale søknad har innkommet

Dette innebærer å åpne opp for at de som har satt fram flere søknader om dagpenger er kandidater for automatisering. Ved å bare utvide til inntil 14 dager vil det være en moderat risiko for at innsending av mer enn 1 søknad har noen praktisk betydning. Men er

**Comment by Bendreas** [comment]
Vi må på et vis fastsette **første** digitale søknad. Det innebærer at vi må lete både fremover og bakover i tid. Hvor går grensen for hvor langt tilbake i tid vi skal lete?
