### ISSUE TITLE
Flytte apper til gha fra jenkins

### ISSUE THREAD

**Issue by Bendreas** [navikt/dagpenger#531]
- [x] dagpenger-joark-mottak
- [x] dagpenger-journalforing-ferdigstill
- [x] dagpenger-regel-ui
- [x] dp-graphql
- [x] ~~dagpenger-oppslag (?)~~ https://github.com/navikt/dagpenger/issues/539
- [x] dp-datalaster-subsumsjonsbrukt
- [x] dp-reverse-proxy (Tarn -Geir A)
- [x] dp-kalkulator-api
- [x] dp-inntekt-innsyn-ui

Blokkes av avhengigheter mot repo.adeo.no
- [x] ~~dp-soknad-frontend~~
- [x] ~~dp-soknad-innsending~~
- [x] ~~dp-soknad-server~~

Apps som er en del av akseptansetestene og dermed krever litt mer jobb
- [x] dp-inntekt (Har'n - Geir A)
- [x] dp-inntekt-klassifiserer (Har'n - Geir A)
- [x] dp-regel-api
- [x] dp-regel-api-arena-adapter
- [x] dp-regel-grunnlag
- [x] dp-regel-minsteinntekt
- [x] dp-regel-periode
- [x] dp-regel-sats

**Comment by androa** [comment]
De gamle søknad-appene har alle avhengigheter på masse interne pakker på repo.adeo.no. Jeg tror ikke de er mulige å flytte ut på internettet.
