### ISSUE TITLE
Fant ikke søknad

### ISSUE THREAD

**Issue by Bendreas** [navikt/dagpenger#536]
Overraskenede mange søknader som vi ikke finner i dp-oppslag-soknadfakta (noe som er veldig rart). Se eksempel:
https://logs.adeo.no/goto/bca52aead5e4fefc8eb14ad0ef3ec8aa

**Comment by gtcno** [comment]
Akkurat for det eksemplet er det diff på FNR som ligger i V2_SOKNAD og fnr i saksbehandlingen som gjør at oppslaget feiler. 

Queryen er på fnr og søknadsId
