### ISSUE TITLE
Sjekk bor i annet EØS-land fra søknadsdialogen

### ISSUE THREAD

**Issue by tonjemjovik** [navikt/dagpenger#543]
Vi må sjekke om det er svart ja på bor i et annet EØS-land i søknadsdialogen. Skal behandles manuelt. 
Dette er krav 39 i lista

**Comment by magnefjeld** [comment]
https://confluence.adeo.no/display/TDP/Automatiske+vedtak+om+dagpenger satt krav 39 til rødt med forklaring. Så oppdaterer vi til grønt, når endringen er utviklet og levert:)
