### ISSUE TITLE
Lisens for bruk av Notion

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#548]
Vi har benyttet Notion for samhandlingsverktøy gjennom vår/sommer 2020. 

Vi bruker gratislisens enn så lenge.

Vi trenger en beslutning på om vi skal fortsette å bruke Notion og eventuell lisens.

**Comment by magnefjeld** [comment]
hva koster det i kroner og øre og trenger vi bare en lisens?

**Comment by geiralund** [comment]
Det koster $8 per bruker per måned for "Team versjonen". Lurer på om vi fort kommer bort i noen regler der dette må gå igjennom et innkjøpskontor elns.
