### ISSUE TITLE
ROS og PVK for å flytte til GCP (offentlig sky) for appene våre.

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#552]
ROS vurdering 
Se PVK for GCP https://doc.nais.io/clusters/migrating-to-gcp#ros-and-pvk 

https://doc.nais.io/clusters/migrating-to-gcp

**Comment by magnefjeld** [comment]
![image](https://user-images.githubusercontent.com/61459197/102615955-0e120200-4137-11eb-8402-caa4d9c8451a.png)

Da skal vel denne være i orden hva gjelder avklaringer knyttet til ROS og PVK.
