### ISSUE TITLE
Ny G er kjent - hvordan skal vi endre den i Dagpenger

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#562]
Ny G er kjent 

https://www.regjeringen.no/no/aktuelt/regulering-av-grunnbelopet-og-pensjonane-fra-1.-mai-2020/id2739885/

**Comment by geiralund** [comment]
DRAFT PR https://github.com/navikt/dp-biblioteker/pull/15

**Comment by magnefjeld** [comment]
https://www.nav.no/no/person/innhold-til-person-forside/nyheter/regulering-av-grunnbelopet-og-ytelser-fra-1.mai-2020 og https://jira.adeo.no/browse/ARENA-2818

**Comment by magnefjeld** [comment]
https://navno.sharepoint.com/sites/fag-og-ytelser-fagsystemer/SitePages/Regulering-av-ytelser-2020.aspx
