### ISSUE TITLE
Endre logikk for fastsettelse av dagpengegrunnlag for vernepliktige dersom det skal innvilges for tidsrom med gammel G

### ISSUE THREAD

**Issue by ChrisdeVriesEnger** [navikt/dagpenger#565]
Dersom det er huket av for "Verneplikt" i Arena, fastsetter Digidag dagpengegrunnlaget med gjeldende G. Dette også dersom det innvilges fra et tidsrom forut for dato G-en ble endret. 

Konsekvensen er at brukere med verneplikt får en litt for høy dagsats for innvilgelser tilbake i tid. Eksempelvis, dersom en saksbehandler i oktober 2020 (etter fullført G-justering) innvilger en bruker med verneplikt dagpenger med virkning fra den 1.3.20, så vil dagpengene for hele perioden bli fastsatt med ny G som grunnlag. Rett løsning ville være at dagpengegrunnlaget ble fastsatt med gammel G fra 1.3 til 30.4, og at det ble gjort en endring fra 1.5.

Samme problem oppstår også dersom brukeren har inntekt på mer enn 3 G, men det er hukt av for verneplikt.

**Comment by atleno** [comment]
duplikat: https://github.com/navikt/dagpenger/issues/566
