### ISSUE TITLE
Beregning av Grunnlag og sats når Verneplikt må ta hensyn til beregningsdato

### ISSUE THREAD

**Issue by espenjohansen** [navikt/dagpenger#566]
I test av G-justering ser vi at grunnlag og sats alltid bruker ny G når det er avhuket for verneplikt. Dette uten hensyn til beregningsdato. 
Dette blir korrekt i selve G-justeringen, da de med vernepliktgrunnlag skal ha ny 3G. Men i manuelt vedtak, når saksbehandler skal beregne, blir det feil når beregningsdato er før dato for ny G, altså før 1. mai. Problemet oppstår altså først etter at vi har kjørt G-justering og lagt inn ny sats.

For personer som kun har inntekt beregnes det korrekt i alle tilfeller, både før og etter 1. mai. Men dersom man også merker for Verneplikt blir inntekten også beregnet etter ny G , selv om beregningsdato er tidligere. Så de som har kombinasjon av inntekt og verneplikt  får da feil grunnlag og sats dersom beregningsdato er før 1. mai 2020.

**Comment by espenjohansen** [comment]
Det har kommet inn en sak nå https://jira.adeo.no/browse/FAGSYSTEM-135121, der person innvilges dagpenger med 3G pga verneplikt fra 20.03.2020. Feilen slår da til og gir for høyt grunnlag og sats, så de må tukle til med manuelt grunnlag og egen begrunnelse.

Har dere sett nærmere på hvordan og når dette kan rettes?

**Comment by androa** [comment]
Jeg tror ikke vi kan løse det på så veldig mange andre måter enn at Arena forteller oss om beregningen er G-justering eller ei. Som betyr en endring som må på plass gjennom hele stacken fra Arena til selve beregningen.

Vi kan nok defaulte til at det ikke er G-justering. Da kjøper vi litt tid for implementasjon i Arena.

**Comment by espenjohansen** [comment]
@androa - det skal være samme regel for bruk av G-sats som om det er kun inntekt som er lagt til grunn. Det er vel Grunnbeløpet på beregningsdato som gjelder? Når fra dato er før 01.05.2020 gjelder G = 99858, og da benyttes inntekter som er før mai 2020. Så skjønner ikke hva som er forskjellen på beregning med inntekter og beregning 3G ved avhuking for verneplikt, så lenge beregningsdato er den samme. 

Er du sikker på at vi trenger et nytt parameter fra Arena?

**Comment by atleno** [comment]
Se https://github.com/navikt/dagpenger/issues/565

**Comment by espenjohansen** [comment]
Har testet i Q0 med kun Verneplikt med fra dato før og etter 1. mai 2020.  Begge beregninger er korrekt.
Har også testet med verneplikt og inntekt 400.000, med fra dato før og etter 01.05.2020 - Begge beregninger er OK
Har også testet med verneplikt og inntekt 800.000, med fra dato før og etter 01.05.2020 - Begge beregninger er OK
Har også testet med kun inntekt 800.000, med fra dato før og etter 01.05.2020 - Begge beregninger er OK

Ønsker flere og litt bredere tester før vi deployer til produksjon
