### ISSUE TITLE
Merking og ruting av søknader med verneplikt

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#567]
Som saksbehandler ønsker jeg at søknader hvor bruker har krysset av for verneplikt, er merket med "verneplikt" når de kommer inn i arena. Dette vedder jeg på vil senke tiden jeg bruker på denne søknaden da jeg vet hva jeg skal se etter.

Før covid-19 var dette den desidert mest brukte særreglene knyttet til minsteinntekt/beregning. Ca 2000-3000 søknader i året.

Ruting: 4450 eller 4455. Avhengig av om søknaden er permittert eller ikke
Oppgavebeskrivelsen skal merkes med **"VERNEPLIKT"**
**Se https://github.com/navikt/dagpenger/issues/572 for regel om flere av merkingene slår til samtidig.**

**Comment by kmriise** [comment]
Er antakelsen at det er en annen saksbehandlingsflyt for verneplikt enn andre søknader, og at det derfor er veldig effektivt å få merket verneplikt?

**Comment by kmriise** [comment]
Innløp:
- Utvid rivers løsning til å også hente ut vernepliktsinformasjon fra søknad
- Send til 4451 (vanlig søknad, hvilken kø er dette?) og 4456 (permittering, hvilken kø er dette?)
- Legg på merking "verneplikt"

**Comment by magnefjeld** [comment]
https://confluence.adeo.no/pages/viewpage.action?pageId=377711140 - nr 2

**Comment by magnefjeld** [comment]
https://navno.sharepoint.com/:u:/r/sites/fag-og-ytelser-arbeid-dagpenger/SitePages/Roller-og-rutiner-for-dagpenger.aspx?csf=1&e=iLJZ0l 

4450 og 4455. Avhenging av om søknaden er permittert eller ikke

Det kan være NAY ønsker at disse skal rutes en annen kø/køer, men venter på svar fra dem på det på confluencesiden.
