### ISSUE TITLE
Merking og ruting av fiskepermittert

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#569]
Som saksbehandler ønsker jeg at søknader hvor bruker har oppgitt at de er permittert fra en fiskeforedling- eller fiskeoljebedrift, er merket med "Fisk" når de kommer inn i arena. 
Dette vedder jeg på vil senke tiden jeg bruker på denne søknaden da jeg vet hva jeg skal se etter.
Ved å merke disse søknadene kan bevisstheten rundt denne smale særregelen øke kvaliteten i saksbehandlingen.

https://confluence.adeo.no/pages/viewpage.action?pageId=377711140

> Søknader fra permitterte i i fiskeindustrien, både ny periode og gjenopptak, behandles etter reglene i dagpengeforskriften § 6-7 og skiller seg ut fra permitteringer med lønnsplikt. Ved å skille ut disse permitteringssøknadene, fra permittering med lønnsplikt (PERM), kan man raskere identifisere disse sakene.

Ruting: **4454**
Oppgavebeskrivelsen i Arena: **"FISK"**
**Se https://github.com/navikt/dagpenger/issues/572 for regel om flere av merkingene slår til samtidig.**

**Comment by magnefjeld** [comment]
Oppdatert ønske fra NAY, om å få denne type søknader rutet til 4454. Oppdatert bestillingen.
