### ISSUE TITLE
Merking og ruting av konkurs-oppgaver i Arena

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#571]
Som saksbehandler ønsker jeg at søker som oppgir under "Arbeidsgiver er konkurs": at de ønsker kun LONN eller LONN+DAGO, er merket med "Konkurs" når de kommer inn i arena.
Dette vedder jeg på vil senke tiden jeg bruker på denne søknaden da jeg vet hva jeg skal se etter.

https://confluence.adeo.no/pages/viewpage.action?pageId=377711140

> Ved å synliggjøre søknader hvor bruker ønsker forskuttering av lønnsgarantimidler i form av dagpenger (LONN), og rute dem til enheten som skal behandle dem, sikrer vi at denne type søknader raskest mulig blir identifisert og rutes enheten som skal behandle dem. I tillegg kan brukere som står i en vanskelig situasjon raskere få svar (konkurs kommer i hovedsak brått på).
> 
> Bidrar til "færre håndavtrykk", gitt spesialisering i spesialisering på dagpengeområde i NAY.

(Oppdatert ønske om ruting kommet 23. september, om å endre fra 4450 til 4401).

Ruting:  **4401**
Merking: **"KONKURS"**
**Se https://github.com/navikt/dagpenger/issues/572 for regel om flere av merkingene slår til samtidig.**

Vi må:
- [ ] Lage ny LøsningService i dp-oppslag-soknadfakta
- [ ] Legge til behov i ferdigstill
- [ ] Legge til merking og ruting

**Comment by urenhale** [comment]
hvis du ikke søker om dagpenger, er dette egentlig **bare** en søknad om forskudd på lønnsgarantimidler, og har ikke så mye med dagpenger å gjøre?

**Comment by magnefjeld** [comment]
I søknadsdialogen under konkurs, så spør vi søkeren hva slag type "dagpenger" de ønsker. Bruker kan velge å kun søke om DAGO, kun LONN eller DAGO+LONN. Spørsmålet "Nei, jeg søker kun om forskudd på lønmnsgarantimidler og ikke om dagpenger", betyr at søkeren kun søker om LONN.
![image](https://user-images.githubusercontent.com/61459197/93173115-52eb5e80-f72c-11ea-9068-5b9077b33447.png)
t.o presentasjon vi sendte ut om endringen i søknadsdialogen i sommer relatert til dette finnes på: https://teams.microsoft.com/l/file/02A1A8CE-B0F2-4982-A673-FF319C73A3C9?tenantId=62366534-1ec3-4962-8869-9b5535279d0b&fileType=pptx&objectUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FDagpengermedvenner%2FShared%20Documents%2FGeneral%2FNy%20l%C3%B8sning%20konkurs%20-%20to%20til%20en%20s%C3%B8knad.pptx&baseUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FDagpengermedvenner&serviceName=teams&threadId=19:ab83de09c67241348f1893e4c7f30105@thread.skype&groupId=f9b8f156-20b2-4394-b4ab-42e3201054eb

**Comment by atleno** [comment]
Dette er datapunktet som trengs:
```
{ 
"key": "arbeidsforhold",
      "type": "BRUKERREGISTRERT",
      "value": null,
      "faktumId": 805458,
      "soknadId": 10636,
      "properties": {
        "konkurs_ytelse": "begge",
     }
```
verdier: [begge,dago,lonn]

**Comment by magnefjeld** [comment]
https://confluence.adeo.no/pages/viewpage.action?pageId=377711140 har oppdatert kravet:

4401 - er "spesialisert på konkurssaker". Ved å merke søknader via innløpet, og rute dem til kø 4450, så kan enheten som er spesialisert raskt plukke opp disse søknadene basert på merkingen i Arena fra 4450-benken. Hvor hoveddelen av søknadene trenger en spesialhåndtering.

Vi sikrer da raskere identifisering. I tillegg kan brukere som står i en vanskelig situasjon raskere få svar (konkurs kommer i hovedsak brått på).

Bidrar til "færre håndavtrykk", gitt spesialisering i spesialisering på dagpengeområde i NAY.

Noen av søknadene, som sendes inn, som også tallmaterialet viser, vil ikke lede til et LONN-vedtak, f.eks. fordi hendelsen bruker oppgir vedrørende konkurs er gammel eller fordi bruker ikke fyller vilkårene/ikke skal ha lønnsgarantimidler, og derfor heller ikke skal ha forskuttering.

Dette vil både gjelde søknader om ny periode og søknader om gjenopptak.

![image](https://user-images.githubusercontent.com/61459197/93433213-ccb74f80-f8c6-11ea-8274-0b9735419d5d.png)

Ruting: 4450
Oppgavebeskrivelsen i Arena: "Konkurs"

**Comment by magnefjeld** [comment]
ønske fra NAY at dette skal rutes 4401, som er spesialisert på konkurs. Oppdatert bestillingen.
