### ISSUE TITLE
Merking og ruting av EØS-pendler i Arena

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#572]
Som saksbehandler ønsker jeg at søknad som oppgir at søker er EØS-pendler (f.eks. grensearbeider), er merket med "EØS" når de kommer inn i arena.
Dette vedder jeg på vil senke tiden jeg bruker på denne søknaden da jeg vet hva jeg skal se etter.
Ved å merke disse søknadene kan bevisstheten rundt denne smale særregelen øke kvaliteten i saksbehandlingen.

https://confluence.adeo.no/pages/viewpage.action?pageId=377711140

> Ved å synliggjøre søknader hvor brukere oppgir at de arbeider i Norge, men bor i annet EØS-land, og rute dem til enheten som skal behandle dem, sikrer vi at denne type søknader raskest mulig blir identifisert og rutes enheten som skal behandle dem. Bidrar til "færre håndavtrykk", gitt spesialisering i spesialisering på dagpengeområde i NAY.

Avklart med NAY:
Alle søknader rutes: **4465**
Oppgavebeskrivelsen i Arena: **"EØS"**
**_Regel:  Følgende hierarki:_**
1. **"67 ÅR**" (https://github.com/navikt/dagpenger/issues/570)
2. **"VERNEPLIKT"** (https://github.com/navikt/dagpenger/issues/567)
3. **"FANGST OG FISKE"** (https://github.com/navikt/dagpenger/issues/568)
4. **"EØS"** (https://github.com/navikt/dagpenger/issues/572)
5. **"KONKURS"** (https://github.com/navikt/dagpenger/issues/571)
6. **"MINSTEINNTEKT - MULIG AVSLAG"** 
7. "**FISK"** (https://github.com/navikt/dagpenger/issues/569)

**Comment by magnefjeld** [comment]
**NAY ønsker følgende ruting og navn:**
Fra: Dalflyen, Erik <Erik.Dalflyen@nav.no> 
Sendt: mandag 21. september 2020 09:26
Til: Fjeld, Magne <Magne.Fjeld@nav.no>
Kopi: Østli, Torunn <Torunn.Ostli@nav.no>
Emne: VS: neste leveranse i innløpet - dagpenger - EØS rutes 4465

Vi foretrekker at alle søknader fra brukere som opplyser om arbeids- og forsikringsperioder fra et annet EØS-land rutes direkte til 4470. Vi kan behandle slike saker, om de er bosatt i Norge eller ikke. Vi har behandlet mange sammenleggingssaker fra 4465, men 4465 kan ikke behandle sammenleggingssaker.
Innløpet-merking av saker; Sammenleggingssaker

**Comment by magnefjeld** [comment]
Fra: Dalflyen, Erik <Erik.Dalflyen@nav.no> 
Sendt: tirsdag 22. september 2020 09:41
Til: Fjeld, Magne <Magne.Fjeld@nav.no>
Emne: SV: neste leveranse i innløpet - dagpenger - EØS rutes 4465

Da skal disse sakene rutes til 4465 

Erik
