### ISSUE TITLE
Vernepliktige får ulike satser i G-reguleringen.

### ISSUE THREAD

**Issue by espenjohansen** [navikt/dagpenger#573]
Alle som har grunnlag pga Verneplikt skal etter G-justering i 2020 ha 936 kr. som ny dagsats.

3G tilsvarer 304053, og skal da gi en dagsats på 936,- (304053 * 0,8 / 260).  
Etter G-justering i Q0 ser vi at 830 vedtak har fått 936 kr. og 974 vedtak har fått 933 som dagsats, bl.a. 29019934924
 
De som får for lav dagsats er innvilget mellom 20. mars og 30. april, så det er kun de som er innvilget fra 1. mai 2020 og senere som blir korrekt oppjustert. 

Feilen må rettes for å unngå feilutbetaling og mye manuelt etterarbeid.

**Comment by geiralund** [comment]
For å tenke litt høyt
Grunnlaget blir beregnet ved å bruke dagens dato G for verneplikt (hvis det ikke er verneplikt blir G ved beregningsdato brukt)
For sats blir G ved beregningsdato brukt uansett om det er verneplikt eller ei.  Dette må, slik jeg tolker det, være feil?
