### ISSUE TITLE
Før 1. oktober 2021: Behov for å skille mellom virkningstidspunkt og beregningsdato 

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#575]
Behov for at Arena sender med virkningstidspunktet til vedtaket når satser skal beregnes, siden det er behov for å skille på dato for regelverk (virkningstidspunkt) og dato for inntekt (i dag kalt beregningsdato) 

For å kunne skille mellom virkningstidspunkt og beregningsdato trenger grensesnittet mellom DigiDag og Arena et nytt felt virkningstidspunkt. 

- [x] Spesifisere og dokumentere nytt felt i OpenApi spekken (https://navikt.github.io/dp-regel-api-arena-adapter/) Se https://github.com/navikt/dp-regel-api-arena-adapter/#working-on-open-api-specification
- [x] Implementere nytt felt i  dp-regel-api-arena-adapter 
- [x] Implementere nytt felt i  dp-regel-api
- [x] Legge nytt felt på behov (packet)
- [x] Logikk i  dp-regel-minsteinntekt
- [x] Logikk i  dp-regel-periode
- [x] Logikk i  dp-regel-sats
- [x] Logikk i  dp-regel-grunnlag

ref https://confluence.adeo.no/display/TEAMARENA/ARENA-4582+01+-+Dokumentinformasjon

Avklaringer:
Oppjustering av grunnlag pga g og beregningsdato

**Comment by magnefjeld** [comment]
vi må gå igjennom løsningsbeskrivelsen på denne https://confluence.adeo.no/pages/viewpage.action?pageId=377185785 og og godkjenne den på https://confluence.adeo.no/display/TEAMARENA/ARENA-4582+01+-+Dokumentinformasjon 

t.o @androa

**Comment by magnefjeld** [comment]
https://jira.adeo.no/browse/ARENA-4921 - ref samtale om denne idag

**Comment by magnefjeld** [comment]
https://www.regjeringen.no/no/aktuelt/forhoyet-dagpengesats-ut-juni/id2828268/?utm_source=www.regjeringen.no&utm_medium=epost&utm_campaign=nyhetsvarsel%201/13/2021-9:19%20AM&utm_content=Arbeidsliv forhøyet dagsats er foreløpig foreslått forlenget til og med 30. juni 2021.
