### ISSUE TITLE
Ettersending til dagpengesøknader - vurdere å gjøre tilsvarende endringer som Team Søknad har gjort for de andre søknadene

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#580]
Bakgrunn i fagsystemsak. Se https://jira.adeo.no/browse/FAGSYSTEM-132105

Team søknad har allerede utført endringen for de andre søknadene (AAP, bil mv)

Vi bør vurdere å gjøre det samme.

**Comment by geiralund** [comment]
@magnefjeld Vi endret de norske tekstene her, ser at Team søknad ikke har en engelsk versjon. Hva skal den være?
