### ISSUE TITLE
Registreringsløsningen vært nede i deler av helgen - kjøre ut lister på hvem som har søkt, når nede

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#582]
Arena har kjørt planlagte oppdateringer i deler av helgen, og da har registreringsløsningen ikke vært tilgjengelige i deler av helgen.
Tidligere har Knut hentet ut lister, på de som i perioden registreringsløsningen var nede, har søkt dagpenger. Så får vi en av saksbehandlerne/testerne til å sjekke om noen av dem har fått avslag pga ikke registrert/påminne dem om å registrere seg

Listen legges på https://teams.microsoft.com/_#/files/Diverse?threadId=19%3A80ac0d040afd445faa0f8dce1bf9b389%40thread.skype&ctx=channel&context=Diverse&rootfolder=%252Fsites%252FKorona-dagpenger-uttrekk%252FShared%2520Documents%252FDiverse

Arena hadde leveranse, fra lørdag 3. oktober kl 23 til søndag 4. oktober kl. 11.
https://nav-it.slack.com/archives/CEE8ZNS81/p1601628975017200

**Comment by magnefjeld** [comment]
Johan opplyser om nedetiden: Ja. Eller det ser ut som at perioden ble litt forkortet. Vi fikk ikke inn noen registreringer etter 00.10 og før 09.20

**Comment by geiralund** [comment]
@magnefjeld La ut resultatet her https://teams.microsoft.com/_#/files/Diverse?threadId=19:80ac0d040afd445faa0f8dce1bf9b389@thread.skype&ctx=channel&context=Diverse&rootfolder=%252Fsites%252FKorona-dagpenger-uttrekk%252FShared%2520Documents%252FDiverse%252FS%25C3%25B8knader%2520-%2520Registreringsl%25C3%25B8sning%2520nede
