### ISSUE TITLE
Søknadsdialogen - Gjenopptak - Permittert - Legg til arbeidsforhold - PD U1 påkrevd

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#583]
Ved gjenopptak - legg til arbeidsforhold - permittert - så kommer det opp 2 stk "Du må legge ved følgende":

en som kun ber om permitteringsvarsel, og en som ber om permitteringsvarsel + PDU1. 

Når man trykker ok, så står bare permitteringsvarsel som påkrevd vedlegg (det er riktig), så det er nok selve visningsbildet som viser feil. Oppsummeringen viser også riktig.

På ny søknad, så vises bare permitteringsvarsel

![image](https://user-images.githubusercontent.com/61459197/95093181-c7605e80-0728-11eb-870c-d822accf1f9b.png)
![image](https://user-images.githubusercontent.com/61459197/95093403-08f10980-0729-11eb-9e4f-6f7ed8770e17.png)

**Comment by magnefjeld** [comment]
Opprettet kort etter avtale med Knut, så kan den ses på når man får tid.

**Comment by geiralund** [comment]
Vi mistenker en bug i frontenden, her har ikke vi kjennskap nok til å endre.

**Comment by kmriise** [comment]
forsøkt løst ved commit: https://github.com/navikt/dp-soknad-frontend/commit/01c4cf87c88254001132f5928d4b38aff2403de9
