### ISSUE TITLE
Statsbudsjettet - Søknadsdialogen - Utdanning - Endringer pga forlenget unntaksregel

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#584]
Regjeringen planlegger å utvide adgangen til å kombinere dagpenger og utdanning fram til og med 30. juni 2021. Dette i forbindelse med statsbudsjettet: https://www.regjeringen.no/no/statsbudsjett/2021/statsbudsjettet-2021-a-til-a/id2765698/?expand=2767506:

**_"Som et midlertidig tiltak i en situasjon med mange ledige og permitterte, har regjeringen fra 20. april 2020 og ut året innført en midlertidig ordning som gjør det lettere å kombinere dagpenger og opplæring. Regjeringen foreslår å videreføre den midlertidige ordningen til 1. juli 2021. Videreføring av ordningen er på usikkert grunnlag anslått å øke utgiftene til dagpenger med 100 millioner kroner."_**

Det er tidligere gjort tilpasninger i den digitale søknadsdialogen (se skjemdump under). Teksten i spørsmålet og i veiledningen, 3 steder det står, må oppdateres fra 31.12.2020 til 30. juni 2021. 

![image](https://user-images.githubusercontent.com/61459197/95711249-a9cc5100-0c62-11eb-81a1-7ec1ac599256.png)

Informasjon på https://www.nav.no/arbeid/no/student/

**Comment by magnefjeld** [comment]
laget trellokort til team innhold for å komme med forslag til oppdatert tekst: https://trello.com/c/lqsaqaUr/144-utdanning-statsbudsjettet-forlenge-tekst-til-digital-s%C3%B8knadsdialog-sjekke-ut-hva-som-st%C3%A5r-innlogget-p%C3%A5-meldekortsidene-om-dette

**Comment by androa** [comment]
Når landes dette? I slutten av november?

**Comment by magnefjeld** [comment]
skjer nok i løpet av november, om vi er heldige. men er mindretallsregjering, så kan ta litt tid.

**Comment by magnefjeld** [comment]
da kan denne implementeres i søknadsdialogen når det er ledig tid. Fint om det kan sies i fra når den er klar til test i Q miljø.
