### ISSUE TITLE
Uke 46/2020: Søknadsdialog - informere generelt om automatiske vedtak

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#585]
Det er et behov at vi informerer om automatiske vedtak i den digitale søknadsdialogen.

Hvorfor?
- Dette er en merknad som har kommet i forbindelse med PVK på automatisering av dagpenger. I tillegg, så er planen hva gjelder Arbeidsgiverperiode 2, fra og med 1.1.2021, at Arena skal lage automatiske stans og gjenopptak. 

Vi ønsker derfor både å informere generelt på nav.no om dette og i søknadsdialogen.

I søknadsdialogen burde den sannsynligvis plasseres under "Viktig informasjon":
![image](https://user-images.githubusercontent.com/61459197/96011133-dc34a480-0e42-11eb-87d6-b5059d4bcc11.png)

Innholdsteamet må lage utkast til tekst vi skal bruke, på bokmål og engelsk. opprettet kort: https://trello.com/c/5SfJCBw5/147-informere-om-at-vi-automatiserer-vedtak-m%C3%A5-vurdere-om-vi-gir-generell-info-eller-ifbm-ag2-informasjon-om-at-vi-kan-automatisere 

**Hvor skal tekst plasseres? Se pil i skjermutklipp, skal inn som nytt avsnitt her:**
![image](https://user-images.githubusercontent.com/61459197/98119735-51791f80-1ead-11eb-9725-df0966b487aa.png)

**Tekst Bokmål:**
NAV vil i noen tilfeller fatte helautomatiske vedtak når du søker om stønad eller underveis i stønadsforholdet. Det automatiske vedtaket baserer seg på informasjon du gir til NAV i søknad eller på meldekort, eller fra offentlige registre.

**Tekst Engelsk:** 
NAV will in some cases make fully automatic decisions when you apply for benefits or while you recive benefits from NAV. The automatic decision is based on information you provide to NAV in the application or on the employment status form, or from public registers.

**Comment by magnefjeld** [comment]
denne må man se på igjen. er ok i ny søknad, men ikke gjenopptak. der ser det fortsatt slik ut: 
![image](https://user-images.githubusercontent.com/61459197/101356843-f3b76900-3898-11eb-8d01-43e6b17b29ab.png)

Si ifra når klar til test i Q miljø

**Comment by magnefjeld** [comment]
i ny søknad er det ok. ref: 
![image](https://user-images.githubusercontent.com/61459197/101356952-16e21880-3899-11eb-95d4-50597cd41531.png)

**Comment by Bendreas** [comment]
Linka feil commit
