### ISSUE TITLE
Ettersending - Vurdere å øke fra 180 dager til 365 dager

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#586]
Vi har tidligere i 2020 oppdatert fra 70 dager til 180. I denne prosessen fant vi også ut at endringene kun kunne gjøres for dagpenger. Team personbruker må også gjøre tilpasninger hos seg.
Ref: https://github.com/navikt/dp-soknad-server/issues/71 og https://confluence.adeo.no/pages/viewpage.action?pageId=371919047

Men jevne mellomrom får vi nå inn fagsystemsaker på brukere (ref: https://confluence.adeo.no/pages/viewpage.action?pageId=371919047), som har passert 180 dagersfristen.

Vi burde vurdere å utvide denne ytterligere, spesielt siden permitteringsperioden nå er utvidet til 49 uker. Men hvor lenge er spørsmålet. Ønsker vi f.eks. å ha en konkret ytre frist eller ønsker vi å ha det åpent.? Hva er konsekvensene av å ha det åpnet, spesielt med tanke på fremtidig utvikling?

**Comment by magnefjeld** [comment]
https://nav-it.slack.com/archives/C9CJ794PP/p1591348928083700 finner dere mer info om hva som Team personbruker gjorde, slik at vi fikk det til å fungere sist gang:) t.o @atleno

**Comment by magnefjeld** [comment]
![image](https://user-images.githubusercontent.com/61459197/96420060-49ef2080-11f5-11eb-92e2-d00a22641653.png)
fra dagpenger med venner i teams. t.o

**Comment by magnefjeld** [comment]
Om vi tenker at vi skal gå for å utvide fristen, så er 365 dager en mulighet. Med mindre man tenker at det ikke er behov for noen frist.

**Comment by atleno** [comment]
Har oppdatert vår grense til 365 dager, har spurt team personbruker i tråden ovenfor om å gjøre det samme hos de

**Comment by magnefjeld** [comment]
@atleno da er vel denne løst og i produksjon, så da underretter jeg ROene om endringen.
