### ISSUE TITLE
Registreringssløsingen nede 19. oktober 2020 - 23.00 til 23:59 - Kjøre ut lister på hvem som har søkt, når nede

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#587]
For mal, ref: https://github.com/navikt/dagpenger/issues/582 

Arena har kjørt koronaleveranse 15 den 19. oktober 2020, og da har registreringsløsningen ikke vært tilgjengelig mellom 23.00 til 23.59. ref.: https://nav-it.slack.com/archives/CEE8ZNS81/p1603110906085900 

Tidligere har Knut hentet ut lister, på de som i perioden registreringsløsningen var nede, har søkt dagpenger. Så får vi en av saksbehandlerne/testerne til å sjekke om noen av dem har fått avslag pga ikke registrert/påminne dem om å registrere seg

Listen legges på https://teams.microsoft.com/_#/files/Diverse?threadId=19%3A80ac0d040afd445faa0f8dce1bf9b389%40thread.skype&ctx=channel&context=Diverse&rootfolder=%252Fsites%252FKorona-dagpenger-uttrekk%252FShared%2520Documents%252FDiverse

**Comment by androa** [comment]
@kmriise @geiralund Har dere noe oppskrift på hva og hvor ting skal hentes ut?

**Comment by kmriise** [comment]
Jeg har logget inn på dp-soknad-mottak i prod, og bare hentet ut søknader i dette tidsrommet +- 2 timer, skal være koblet mot fnr i den tabellen hvis jeg husker riktig. @androa

**Comment by geiralund** [comment]
Fikk ikke eposten |-) Skal sjekke github pluginen i slack. 
jeg kjørte sist gang 

`
select fnr, soknads_id from v2_soknad where created between '2020-10-03 23:00:00'::date and '2020-10-03 11:00:00'::date;
`
i dp-soknad 

Lastet opp resultatet i excel

**Comment by magnefjeld** [comment]
Maria sjekket ut og lastet opp på lukket teamsgruppe: https://teams.microsoft.com/l/file/436E68EA-9C2F-4833-861A-DFE60CA22825?tenantId=62366534-1ec3-4962-8869-9b5535279d0b&fileType=xlsx&objectUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FKorona-dagpenger-uttrekk%2FShared%20Documents%2FDiverse%2FS%C3%B8knader%20-%20Registreringsl%C3%B8sning%20nede%2Fdpsoknader_20201019_kl23-2359.xlsx&baseUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FKorona-dagpenger-uttrekk&serviceName=teams&threadId=19:80ac0d040afd445faa0f8dce1bf9b389@thread.skype&groupId=3da29b59-dff5-4a3b-8ad4-661df303532d kun 1 person som har søkt og personen hadde registrert seg 19.10.2020, så ok.
