### ISSUE TITLE
Statsbudsjettet - Søknadsdialogen - Informasjon om sanksjon - 1. januar 2021 + Informere om ventetid på 3 dager om gjeninnføres.

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#589]
Det er foreslått i statsbudsjettet 2021: https://www.regjeringen.no/no/statsbudsjett/2021/statsbudsjettet-2021-a-til-a/id2765698/?expand=2767506 :

"Regjeringen foreslår å skjerpe sanksjonene i dagpengeordningen fra 1. januar 2021, ved å øke varigheten på forlenget ventetid og tidsbegrenset bortfall av dagpenger ved selvforskyldt ledighet og for dem som takker nei til arbeid eller arbeidsmarkedstiltak. Forslaget er på usikkert grunnlag anslått å redusere utgiftene i dagpengeordningen med om lag 180 millioner kroner."

Legges inn fra 1. januar 2021, om vedtas.

Det må gjøres oppdateringer i den digitale søknadsdialogen, hvor det økes fra tolv til 18 uker, under arbeidsforhold. I tillegg må det legges inn igjen informasjon om ordinær ventetid på tre dager (som gjeninnføres fra 1.1.2021): Se info hvordan vi skrev dette pre-covid-19 i søknadsdialogen: https://confluence.adeo.no/pages/viewpage.action?pageId=333622126. 

Gjenbruker tekster fra pre-covid-19, men bytte ut "tolv" med "18". I tillegg til å påse at vi skriver tallet "3" som tall. 

Hva gjelder på engelsk, skal det bare være å se på pre-covid-19 versjonen og bytte ut "tolv" med "18". I tillegg til å påse at vi skriver tallet "3" som tall. 

Ser slik ut idag:
![image](https://user-images.githubusercontent.com/61459197/96474091-b6d4db80-1232-11eb-83c6-a166d9ca8407.png)
![image](https://user-images.githubusercontent.com/61459197/96474141-c7855180-1232-11eb-946d-2ddd742e970c.png)
![image](https://user-images.githubusercontent.com/61459197/96474209-db30b800-1232-11eb-9382-7012ba78ab16.png)

**_Må endres til, bare endret fra tolv til 18:_**

Under: "Arbeidsgiver har sagt meg opp"
**Dersom du har blitt sagt opp av arbeidsgiveren din vil du ikke få dagpenger de 3 første dagene. Disse dagene kalles ventedager. Dersom du selv har skyld i at du ble oppsagt vil du normalt ikke få dagpenger de første 18 ukene. Perioden løper først fra den datoen dagpengeperioden starter. Det er viktig at du ikke venter med å søke om dagpenger. Du må sende søknaden din nå, selv om du kan få en ventetid på 18 uker. I tillegg må du være registrert som reell arbeidssøker og sende meldekort i ventetiden.**

Under: "Jeg har sagt opp selv":
**Dersom du har sagt opp selv vil du vanligvis ikke få dagpenger de første 18 ukene. Har du sagt opp selv som følge av innskrenkninger, vil du vanligvis ikke få dagpenger de første 3 dagene. Denne løper først fra den datoen dagpengeperioden starter. Det er viktig at du ikke venter med å søke om dagpenger. I tillegg må du være registrert som reell arbeidssøker hos NAV og sende meldekort i ventetiden.**

Under: "Jeg er avskjediget":
**Dersom du er avskjediget, vil du vanligvis ikke få dagpenger de første 18 ukene. Perioden løper først fra den datoen dagpengeperioden starter. Det er viktig at du ikke venter med å søke om dagpenger. I tillegg må du være registrert som reell arbeidssøker hos NAV og sende meldekort i ventetiden.**

**Comment by magnefjeld** [comment]
vi skriver også tall under 12, som tall: https://design.nav.no/resources/language/units/

**Comment by magnefjeld** [comment]
Endringen er til 1. januar, men fordi vi ikke har vakt i julen/nyttår, er vurderingen min at denne kan leveres mandag 4. januar 2021. Så tar vi ned risikoen om det er feil for bruker.

**Comment by geiralund** [comment]
Kan ikke deployes før 4. januar - se PR
