### ISSUE TITLE
Lærlinger - opphører for nye tilfeller f.o.m 1.11.2020, men de som har vært inne på ordningen kan gjenoppta/endre t.o.m 31.12.2021 (foreløpig antagelse)

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#591]
Lærlinger har egne regler for beregning av dagpengegrunnlaget. Ordningen oppheves for nye tilfeller fra 1. november 2020 eller senere. Dette ivaretas i Arena av at Ny rettighet (O), i kombinasjon med avhuking for lærlinger ikke er teknisk mulig med virkningstidspunkt fra 1. november 2020 eller senere. 

Imidlertid, vil det være overgangsregler, sannsynligvis til og med 31.12.2021, hvor brukere som går på dagpenger som lærling, samt har mulighet til å gjenopptak, fortsatt skal få lov til dette ut 2021. I noen tilfeller vil det være slik at det bes om reberegning ved gjenopptak eller det samordnes mot andre ytelser. I disse tilfellene må det være mulig, ved Gjenopptak (G) og Endring (E), å beregne dagpengene på nytt, fram til og med 31.12.2021.

En mulig løsning, som vi har diskutert, er å flytte til og med datoen fra 31.10.2020 til ny til og med dato 31.12.2021. Dette innebærer, som du påpeker @geiralund at vi ikke har full kontroll på det som kommer fra Arena, og må stole på det som kommer derfra. Foreløpig har ikke digidag mulighet til å skille på vedtakstyper.

Vi tror imidlertid dette gjelder ganske få brukere (som skal ha reberegning eller beregning endret pga samordning).Fint om det er mulig å få opp en måling på dette, om det er mulig.

Verdt å merke seg at lærlinger ikke G-justeres, eller skal justeres 1.1.2021 hva gjelder dagpengegrunnlag.

**Comment by geiralund** [comment]
Denne blir deployet nå. For grunnlag og sats blir er ny sluttdato for lærlingberegning 31.12.2021 for å kunne reberegne.. For inngangsvilkår minste arbeidsinntekt er sluttdato for særregel for lærling 01.11.2020.  cc  @magnefjeld

**Comment by magnefjeld** [comment]
takk:) @geiralund
