### ISSUE TITLE
Endringer i Loginservice i selvbetjening - Må gjøres før 16. november i prod

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#593]
Sjekk https://nav-it.slack.com/files/T5LNAMWNA/F01D73VH5HN 

Når skjer endringene?
Etter at Loginservice har byttet vil vi oppdatere LOGINSERVICE_IDPORTEN_DISCOVERY_URL i ConfigMap’et nevnt tidligere, og så langt det lar seg gjøre restarte alle applikasjoner som bruker dette.

Om dere opplever feil så bør en restart av applikasjonen deres løse problemet.

Loginservice begynner å utstede tokens med ny URL på følgende datoer:

Dev - Mandag 26. oktober - kl. 09:00
Prod - Mandag 9. november - TBA

**Comment by kmriise** [comment]
":warning: Så langt vi har oversikt har folk nå kontroll på de systemene som berøres av URL-endringen i Loginservice. Vi kommer derfor til å gjøre den samme endringen i prod mandag 16. november ved midnatt (altså natt til tirsdag). Vi legger ut en melding om mulig ustabilitet på nav.no i forkant."

**Comment by androa** [comment]
For å unngå å måtte endre på noe her selv når det faktisk skjer, så flipper vi nå hvilke verdier vi bruker avhenging av hva ConfigMappet inneholder:

https://github.com/navikt/dp-kalkulator-api/blob/master/src/main/kotlin/no/nav/dagpenger/kalkulator/KalkulatorApp.kt#L47-L48

Vi bruker JWK og ikke JWT og må derfor hente ut keys-urlene fra openid-configuration og hardkode de.
