### ISSUE TITLE
Før 1. januar: Anmodningsvedtak 2 - forhøyet dagsats er foreløpig foreslått forlenget til og med 31. mars 2021

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#597]
Har også sammenheng med https://github.com/navikt/dagpenger/issues/575

https://www.regjeringen.no/no/dokumenter/prop.-1-s-tillegg-1-20202021/id2784443/ :
![image](https://user-images.githubusercontent.com/61459197/98701755-ebdbd600-2379-11eb-95fc-36258af19843.png)

Vi regner med at denne er forholdsvis bankers og at DD kan oppdatere slik at datoen kan oppdateres til og med 31.mars.2021

**Comment by androa** [comment]
Yep, vi har vel dette to steder; i grunnlag og sats.

Grunnlag: https://github.com/navikt/dp-regel-grunnlag/blob/9034bcfb00c2054522d8e9aad38788665f6c89af/src/main/kotlin/no/nav/dagpenger/regel/grunnlag/beregning/GrunnlagBeregning.kt#L43

Sats: https://github.com/navikt/dp-regel-sats/blob/b629608509bdf94d13e0273bcfb03fcc9a60b481/src/main/kotlin/no/nav/dagpenger/regel/sats/versjoner/KoronaPeriode.kt#L8

Dette er vel bare en videreføring, så det er bare snakk om å endre sluttdatoen til 31. mars 2021?

**Comment by magnefjeld** [comment]
det stemmer.

**Comment by tonjemjovik** [comment]
fikse test 
https://github.com/navikt/dp-regel-sats/commit/cb0064d7c2a79e5c26446d8ecc9e98cb0625ca34
