### ISSUE TITLE
Søknadsdialogen - Fjerne spørsmål om lærling - 1. februar 2022

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#599]
Som dagpengesøker
ønsker jeg ikke å ta stilling til om jeg er lærling i den digitale søknadsdialogen
da dette ikke er relevant for søknaden min

Regjeringen har forlenget muligheten for lærlinger til å motta dagpenger ut desember 2021

**Fjerne spørsmål om lærlinger i søknadsdialogen fra 1. februar 2022, så fremt ordningen ikke forlenges.**

Presentasjon av endringene knyttet til lærlinger - 27. april 2020 .
https://teams.microsoft.com/l/file/AD08148E-7A32-4432-8408-24BB4CAFC50D?tenantId=62366534-1ec3-4962-8869-9b5535279d0b&fileType=pptx&objectUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FDagpengermedvenner%2FShared%20Documents%2FGeneral%2FLeveranse%20-%20S%C3%B8knadsdialogen%20-%20Team%20Dagpenger%20-%2027.%20april%202020.pptx&baseUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FDagpengermedvenner&serviceName=teams&threadId=19:ab83de09c67241348f1893e4c7f30105@thread.skype&groupId=f9b8f156-20b2-4394-b4ab-42e3201054eb

**Comment by magnefjeld** [comment]
https://www.regjeringen.no/no/aktuelt/forlenger-ordning-med-dagpenger-til-larlinger/id2828458/?utm_source=www.regjeringen.no&utm_medium=epost&utm_campaign=nyhetsvarsel%201/13/2021-3:19%20PM&utm_content=Arbeidsliv lærlingeordningen foreslått forlenger til og med juni 2021 for nye tilfeller. Løpende tilfeller er foreslått å kunne motta, og gjenoppta, ut desember 2021.

**Comment by magnefjeld** [comment]
![image](https://user-images.githubusercontent.com/61459197/120456648-192fb600-c396-11eb-8fe3-e6ec4478e335.png)

**Comment by magnefjeld** [comment]
Når ordningen avvikles i sin helhet fra 1.1.2021 må vi ta stilling til om det er noe vi må foreta oss hva gjelder det som er laget i rundt beregninger knyttet til lærlinger. Det skal naturligvis fortsatt være mulig framover å innvilge med tilbakevirkende kraft (f.eks. ved omgjøring etter klage med videre). Ivaretas av eksisterende funksjonalitet i Arena.

**Comment by geiralund** [comment]
Håndteres av https://jira.adeo.no/browse/DAG-148
