### ISSUE TITLE
Oppdatere jenkins

### ISSUE THREAD

**Issue by kmriise** [navikt/dagpenger#604]
https://nav-it.slack.com/archives/CN8N938K1/p1607356235397400

det er oppdaget flere sårbarheter i en del jenkins plugins, og vi bør oppgradere jenkinsen enn så lenge vi fortsatt bruker den.

**Comment by gtcno** [comment]
Burde vi gjøre et forsøk på å flytte alt over til GHA?

**Comment by gtcno** [comment]
Det er vel "bare"

- dp-søknad-* igjen?

**Comment by gtcno** [comment]
@androa Fikk du oppdatert?

**Comment by androa** [comment]
Jobber med å få SSH tilgang til den. Gode muligheter for er at det ordner seg i dag.

**Comment by androa** [comment]
Da er det gjort :)
