### ISSUE TITLE
Før 1. januar 2021 - UU- dagpengekalkulatoren - utbedre

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#605]
ref. https://confluence.adeo.no/display/TDP/UU og https://teams.microsoft.com/_#/files/Generelt?groupId=6ea183cf-34eb-4e47-b76f-14f20ce7590e&threadId=19%3A78080dcbfa6d4d449642aa7c64f02a72%40thread.tacv2&ctx=channel&context=UU-Vurderinger&rootfolder=%252Fsites%252FTeamDagpenger%252FShared%2520Documents%252FGeneral%252FUU-Vurderinger 

I forbindelse med UU-disp, så er det noen avvik som vi anser nødvendige å utbedre innen 1. januar 2021:

Resultat: endre semantisk overskriftstruktur

Rette opp dobbel bruk av <header> element

Gjør om div “content” til landmark “main”

**Comment by kmriise** [comment]
Endringer gjort i commit: https://github.com/navikt/dp-kalkulator-frontend/commit/4f1adddf0c89b2145b5f7fb13d1d6e1a935aa55a

**Comment by kmriise** [comment]
Endringer også gjort i commit: https://github.com/navikt/dp-kalkulator-frontend/commit/d17f4ae66657043bf4c8194d5aeeb07a37db0822
