### ISSUE TITLE
Søknad og ettersendelse - Kvitteringen - Vurdere behov for tilpasninger

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#606]
Bakgrunn i innmeldt fagsystemsak: https://jira.adeo.no/browse/FAGSYSTEM-144632# se den og https://nav-it.slack.com/archives/CU268M1AQ/p1607677165006900  for mer informasjon.

Om løsningen skaper forvirring, slik at bruker ikke forstår at dokumenter ikke er ettersendt, må vi vurdere å gjøre tilpasninger her.

**Comment by kmriise** [comment]
Gjort endringer i visuell utforming gjennom commitsene:
https://github.com/navikt/dp-soknad-innsending/commit/169efe1a405351f4011003f5f19fab3834af20d3
https://github.com/navikt/dp-soknad-innsending/commit/faa06619e48ec1b6e24b79c820b895beacdc7c60
https://github.com/navikt/dp-soknad-innsending/commit/77c4f8416fed37143dcacfbf30c4ef937968e9bc
https://github.com/navikt/dp-soknad-server/commit/3e2bbb5c60104dc5fd3121a84bc79d09953ce403
