### ISSUE TITLE
Ta imot digitale klager om dagpenger via eksisterende innløp.

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#607]
Team klager i P3 har laget en fellesløsning hva gjelder klager. Foreldrepenger har tatt den i bruk allerede, og i løpet av desember vil løsningen bli oppdatert med funksjonalitetene vi har avtalt med NAY (se demo hvordan den vil se ut). Oppdatert demo finnes på: https://nav-brukertesting.webflow.io/person/tilbakemeldinger   

Før team klager kan slå på løsningen for dagpenger, så må team dagpenger legge til rette for å motta klagene via vårt innløp og håndtere dem på lignende måte som for papirklagene som kommer inn via vårt innløp. Men vi må naturlig nok kunne skille dem fra papirklagene:

- Automatisk journalføre (når mulig iht våre forretningsregler)
- Rutes Arenabenk:  
4450
- Beskrivelse: 
Klage
- Kommentar*:  
*Må avklares hva vi ønsker å skrives her.

Utklipp hvordan det ser ut idag:
![image](https://user-images.githubusercontent.com/61459197/101919731-35168400-3bcb-11eb-879e-a38640c3c8ae.png)

For mer informasjon, se https://confluence.adeo.no/pages/viewpage.action?pageId=385066018

AAP og tiltakspenger har bestemt at løsningen skal tas i bruk på deres områder.

- [ ] Målinger

**Comment by atleno** [comment]
Det her virker ganske greit, tar sikkert litt tid å teste. Hvis det bare er å rute klage til benk 4450, med informasjonen som står i confluence, så er det bare et par dagers jobb å kode det. Så et par uker totalt for å være sikker

**Comment by magnefjeld** [comment]
oppdatert: https://confluence.adeo.no/pages/viewpage.action?pageId=385066018

**Comment by Bendreas** [comment]
Etter undersøkelser viser det seg at digitale klager vil håndtederes av innløpet slik det er, på grunn av at det brukes samme skjemaid/brevkode som papirklager. Trenger dermed ikke mer kode. Eneste vi ikke får til er å skille digitale og papir-klager, for å gi forskjellige beskrivelser i Arena.

**Comment by Bendreas** [comment]
Vi må:

- [ ] oppdatere PVK

- [ ]  lenke til digitalt skjema når det er klart

- [ ] teste en digital klage for å se at den flyter gjennom som forventet

**Comment by magnefjeld** [comment]
25.1.21: sent e-post til NAY med svarfrist onsdag 27.1.21, om endringene vi ser for oss.
