### ISSUE TITLE
Arena nede 31. 12 og 1. 1 i forbindelse med Leveranse.

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#608]
![image](https://user-images.githubusercontent.com/61459197/102319511-4bca2b80-3f7b-11eb-9181-9704ce52c0e4.png)

Slack-tråd (team-dagpenger-vakt): https://nav-it.slack.com/archives/CU268M1AQ/p1608102909015700 

Registreringsløsningen vil også være nede, så vi må kjøre ut lister på hvem som har søkt. Ref. tidligere uttrekk: #596

Listen legges i et eget excel-ark på https://teams.microsoft.com/_#/files/Diverse?threadId=19%3A80ac0d040afd445faa0f8dce1bf9b389%40thread.skype&ctx=channel&context=S%25C3%25B8knader%2520-%2520Registreringsl%25C3%25B8sning%2520nede&rootfolder=%252Fsites%252FKorona-dagpenger-uttrekk%252FShared%2520Documents%252FDiverse%252FS%25C3%25B8knader%2520-%2520Registreringsl%25C3%25B8sning%2520nede

Så får vi en av saksbehandlerne/testerne til å sjekke om noen av dem har fått avslag pga ikke registrert/påminne dem om å registrere seg

**Comment by gtcno** [comment]
###  Onsdag 30.12.2020 Klokken 24.00
- [x] Slå på (enable) feature flag  [dagpenger.soknad-iarbs](https://unleash.nais.io/#/features/strategies/dagpenger.soknad-iarbs)
- [x] Ta ned dp-journalføring-ferdigstill 

###  Torsdag  31.12.2020 Ca Klokken 07.00
- [x] Slå av (disable) feature flag  [dagpenger.soknad-iarbs](https://unleash.nais.io/#/features/strategies/dagpenger.soknad-iarbs)
- [x] Ta opp dp-journalføring-ferdigstill 

 ###  Fredag 01.01.2022 Klokken 11.00
- [x] Slå på (enable) feature flag  [dagpenger.soknad-iarbs](https://unleash.nais.io/#/features/strategies/dagpenger.soknad-iarbs)
- [x] Ta ned dp-journalføring-ferdigstill 

###  Fredag 01.01.2022 Ca Klokken 18.00
- [x] Slå av (disable) feature flag  [dagpenger.soknad-iarbs](https://unleash.nais.io/#/features/strategies/dagpenger.soknad-iarbs)
- [x] Ta opp dp-journalføring-ferdigstill 

Ta uttrekk av eventuelle søknader i nedetid: 

`SELECT  s.fnr fnr_soknad
FROM    v2_soknad s
WHERE   s.created >= to_timestamp('2020-10-31 17:00', 'yyyy-mm-dd hh24:mi')
AND     s.created <= to_timestamp('2020-11-01 06:00', 'yyyy-mm-dd hh24:mi')`
