### ISSUE TITLE
Feil i beregning - Bakgrunn fagsystemsak til team Arena

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#609]
Den opprinnelig meldte feilen skyldes at Arena sender uavkortet grunnlag som input til beregning av grunnlag og sats. Dette blir feil i de tilfeller bruker har tjent mer enn 6 G i én eller to av inntektsperiodene. Ved uttrekk av vedtak for å se på omfanget av saken er det også oppdaget tilfeller der reberegningsfunksjonaliteten gir for høy dagsats. Uttrekket lastes opp i jira. Der reg_user = GRENSESN er det utført en maskinell reberegning.

Fagsystemsak: https://jira.adeo.no/browse/FAGSYSTEM-145003# 
Slack-kanal: https://nav-it.slack.com/archives/G01GY48F606

**Comment by magnefjeld** [comment]
Andree startet på denne torsdag 17.12. se slack-kanalen.

**Comment by gtcno** [comment]
Vi har sett på denne og greier ikke å reprodusere. Vi får riktig sats når vi gjør reberegningen pt. På bakgrunn av dette og sjekken som Arena nevner setter vi denne til done.

**Comment by magnefjeld** [comment]
t.o
ref. slack.
bestilt opp logging fra team arena: https://jira.adeo.no/browse/ARENA-5238
