### ISSUE TITLE
Som en søker som har hatt inntekt/trygdeperioder fra EØS, er jeg ikke kandidat for automatisk avslag

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#614]
Krever endringer i søknadsdialogen.

**Comment by gtcno** [comment]
Endring i søknadsdialogen: 

- [x] Fjerne PDU1 Skjema
- [x] Nytt spørsmål. Har du jobbet i Sveits/Eøs de siste 3 årene som et Ja/Nei.
- [x] Hvis Ja: Sprørsmål om hvilket eller hvilke land der snakk om. Nedtrekksliste. Og hvilke perioder


Data brukes til å vurdere om Eøs er relevant. 

Ny løsning: 

Hvis ja, ikke kandidat for automatisert saksbehandling.

**Comment by kmriise** [comment]
Søknadsdialogen:

- [ ] HVIS: Legg-til-Arbeidsforhold har blitt lagret med EØS-land/sveits. Automagisk flagg nytt spørsmål i arbeidsforhold med "ja" og legg til landet i listen på oppfølgingspørsmål om hvilke land det er snakk om. I tillegg skal man sjekke hvilken type arbeidsforhold det er, og basert på det velge hvilket fakta som skal hentes ut og omgjøres til en periode, som så skal legges inn automatisk i underspørsmålet for hvilket land det er snakk om.

**Comment by kmriise** [comment]
- [x]  fjerne pdu skjema

- [x] legge til ny bolk: "arbeid i eøs"

- [x] 2. legge til nytt fakta for eøs

- [x] 3. legge til nytt fakta for hvilke land eøs gjelder (flere fakta? streng med concat fakta?)

- [x] 4. legge til nytt fakta for hvilke perioder i hvilket land eøs gjelder (flere fakta)

- [x] 5. migrere mellomlagrede søknader til å støtte disse nye faktaene

- [ ] 6. bonus: prøve å automagisk fylle ut spørsmålene basert på svarene i arbeidsforhold, merk at dette kan være tricky, hva skjer når det er flere arbeidsforhold? overskriver vi eller legger vi på? hva skjer når bruker har fylt ut eøs spm før arbeidsforhold? overskriver vi eller legger vi på? hva skjer når bruker fyller ut flere arbeidsforhold? overskriver vi eller legger vi på? hva skjer når bruker sletter ett arbeidsforhold? fjerner vi fra gamle spm eller overskriver vi eller gjør vi ingenting?

**Comment by ChrisdeVriesEnger** [comment]
Må eventuelt også se på rutingen av saker hvor brukere svarer "Ja" på arbeid i EØS - bør sendes Innlandet.

**Comment by kmriise** [comment]
- [x]  Legge til hjelpetekst (med hode-advarsel) i eøs bolk:
arbeid i eøs området kan både hjelpe til med å nå minsteinntektskravet og å hjelpe til med å få mer i utbetaling

Endre navn i eøs bolk:

- [x]  legg til EØS-arbeidsgiver

i oppsummering av arbeidsforhold-eøs:

- [x] en grå boks per arbeidsforhold

- [x] skjul oppsummering av arbeidsforhold-eøs hvis bruker har svart nei etter å fylle inn arbeidsforhold.

**Comment by kmriise** [comment]
venstrejuster knapp legg til arbeidsforhold - fikset

**Comment by kmriise** [comment]
bugs:
landlisten validerer ikke, kan sende inn tomt land - fikset
landlisten har et tomt valg i dropdownlisten i starten - ignoreres, siden validering nå er fikset

**Comment by kmriise** [comment]
legg til eos arbeidsforhold funker ikke i gjenopptak - fikset

**Comment by kmriise** [comment]
- [x] Legge på ekstra fritekstfelt i nytt eos arbeidsforhold, hvor bruker må skrive inn personnummeret sitt for det landet, for hvert eos arbeidsforhold

**Comment by ChrisdeVriesEnger** [comment]
"Oppgi personnummeret (PIN) som du hadde i dette landet."

**Comment by magnefjeld** [comment]
Oppdatert: https://confluence.adeo.no/pages/viewpage.action?pageId=377711140 etter tilbakemelding fra NAY vedrørende:
**Ruting**: 4470
**Merking**: MULIG SAMMENLEGGING – EØS
**Hierarki**: 
"MULIG SAMMENLEGGING - EØS" (#614)
"VERNEPLIKT" (#567)
"FANGST OG FISKE" (#568)
"EØS" (#572)
"KONKURS" (#571)
"MINSTEINNTEKT - MULIG AVSLAG"
"FISK" (#569)

**Comment by magnefjeld** [comment]
på sjekklisten burde man også sette opp "målinger". Maria kan ta dette inn i en av datapakkene våre. Således får vi oversikt over hvor mange brukere som søker om sammenlegging av perioder. Fordi vi ikke har hatt spørsmål om det tidligere, så er det en hypotese at det er underforbruk her.

**Comment by kmriise** [comment]
- [x] bolk må verifisere at det finnes minst ett eøs-arbeidsforhold for å gå videre, gitt at bruker har svart ja

**Comment by kmriise** [comment]
- [ ] utviklere må teste at en søknad går gjennom hele løpet, og at modellen skiller ut søknaden til automatisk beregning/manuell

**Comment by kmriise** [comment]
- [x] utviklere må rute til riktig benk

**Comment by kmriise** [comment]
- [ ] Vi har en minimumslengde på 2 tegn i PIN, trenger vi dette, burde vi forklare? trenger vi det?

- [x] Viser ikke PIN i oppsummering/søknadspdf om PIN er tom (optional field)
