### ISSUE TITLE
Som NAV ønsker å være sikker på at foreldrepenger er med i prøving av krav til minste arbeidsinntekt

### ISSUE THREAD

**Issue by tonjemjovik** [navikt/dagpenger#617]
Dersom bruker har foreldrepenger skal denne inntekten med i beregningen av minsteinntekt

sjekke at dette kommer med i dag??

**Comment by Bendreas** [comment]
Ja, blir lagt til som arbeidsinntekt her: https://github.com/navikt/dp-inntekt/blob/4352387d1aafcb03c3d96ec027ffce934a569569/dp-inntekt-api/src/main/kotlin/no/nav/dagpenger/inntekt/klassifiserer/KlassifisertPostering.kt#L26-L101
