### ISSUE TITLE
Som søker med lottinntekt, er jeg ikke kandidat for automatisk avslag av minste arbeidsinntekt 

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#636]
Søker har lottinntekt hvis hen har inntekt med inntektsklasse FANGST_FISKE. FANGST_FISKE inneholder posteringstypene N_LOTT_KUN_TRYGDEAVGIFT og N_VEDERLAG (Vederlag lott).

**Comment by atleno** [comment]
Løses av https://github.com/navikt/dagpenger/issues/613. Når vi sender søkere som har huket av fangst og fiske i søknaden til manuell behandling, så vil vi heller ikke hente lott-inntekt.
