### ISSUE TITLE
Måleparametre 2021 - Revurdere de som er meldt inn

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#637]
POA har fått penger i porteføljen, vi har i LVT beskrevet parametere vi ønsker å bli målt på. Det var gjort tidlig i prosessen, så vi må nå raskt finne ut av om dette er hensiktsmessige parametere eller om noen bør erstattes med andre. Vi har et eiermøte 20 januar, og på dette møte bør informere om evt endringer av måleparametere med begrunnelse, og lansere evt nye parametere. 

--
Innholdsteamet ser på måleparametre som treffer dem (nav.no) og Maria er i gang med å se på noen av dem som treffer oss (komplette/behandlingsklare), men vi må i løpet av uke 2 bestemme oss for hvilke måleparametre vi anser som hensiktsmessige for 2021.

Eira holder i dette fra POA sin side.

https://confluence.adeo.no/display/TDP/LVT+-+Dagpenger 

![image](https://user-images.githubusercontent.com/61459197/103863207-b9700000-50c0-11eb-930b-25b1b2560c42.png)

**Comment by geiralund** [comment]
1. Ventetiden hos bruker går ned: Dette måles ved at saksbehandlingstiden mellom innsendt søknad og vedtak reduseres med 10 (xx) % for innsendte søknader ✅
> Definisjon av behandlingsklar*
> 12.01.21 - Endret fra behandlingsklar til innsendte.
> Skille mellom reell behandlingsklar og ikke. Saksbehandler kan "vite" dette og være et målepunkt. 
> Andel saker der det ikke skjer noe etter at saksbehandler har "tatt" i den
> Hvor mange sender ikke inn søknad pga avslag på dagpengekalkulator? 

2. Øke andelen behandlingsklare søknader med 5 %.  
> Definisjon av behandlingsklar*. Gir denne oss noe? 
>  12.01.21 - Avventer denne. Må måles i ny løsning

3. Redusere andelen henvendelser med 10 % knyttet til behandlingsklare søknader. 
> Denne er veldig vanskelig å måle. Vi har ikke noen måte å knytte søknad med henvendelse pt.
>  12.01.21 - Avventer denne. 

4. Automatisering av Arbeidsgiverperiode 2 med 90 %
> Hvordan måler vi dette?  
>  12.01.21 - Det må avklares hvordan denne skal måles (regelverksgjengen)

5. En andel brukere får hjelp til å fylle ut søknaden fra en digital veileder som eksponerer registerdata (forberedende 
aktiviteter til store satsinger, dette inkluderer forbedringer i regelverk og datakvalitet)
> En andel er ikke lett å måle. Skal vi begynne med digital veileder? Eksponere registerdata til brukere?  Måleparameter for ny søknadsdialog.
> Kan denne vinkles til feks Antall søknader der registrerdata er verifisert ok elns.
> Inngå i brukerferden på tvers (arbeidssøkerregistrering, dagpenger, 14a, etc)? 
> Er dette en måling eller noe vi skal gjøre? 
> Hvordan måler vi trygghet? 

6.  Bruker opplever informasjonen på dagpenger på nav.no som lettere tilgjengelig (brukerundersøkelse - trend) 
> Hvordan måler vi opplevelser? 

Mulige andre forslag til parametre: 
- Måle "Klare seg selv" -> Antall henvendelser som har med Dagpenger, arbeidssøkerregistrering  / Antall brukere på Dagpenger, arbeidssøkere osv
  - Hva er en henvendelse?
  - Hvordan kan de måles 


*Behandlingsklare - se figur [Raskere og riktig behandling av søknader om dagpenger: Hvordan legge til rette for å øke andelen "Behandlingsklare søknader" ?](https://confluence.adeo.no/display/TDP/Korona+-+Videre#KoronaVidere-Raskereogriktigbehandlingavs%C3%B8knaderomdagpenger:Hvordanleggetilrettefor%C3%A5%C3%B8keandelen%22Behandlingsklares%C3%B8knader%22?)

**Comment by mariacabrol** [comment]
Oppdatert https://confluence.adeo.no/pages/viewpage.action?pageId=395311159 med målinger av ventetid og behandlingsklare søknader
