### ISSUE TITLE
Som NAV ønsker vi å vise riktig signatur og retur- og postadresse i vedtaket

### ISSUE THREAD

**Issue by tonjemjovik** [navikt/dagpenger#640]
- [x] Hvem blir med på møte fredag 29. januar 2021 11:15-11:45 med team arena og team ccm

**Comment by magnefjeld** [comment]
https://jira.adeo.no/browse/ARENA-5261 opprettet bestilling til leverandør for endring i rest-tjenesten.

**Comment by magnefjeld** [comment]
Vi må se hvilke tilpasninger vi må gjøre på vår side.

**Comment by atleno** [comment]
Fortsetter når rest-tjenesten er fiksa. Kanskje innen første helga i februar, usikkert

**Comment by rannveigskjerve** [comment]
- I delautomatiske avslag skal det kun være signatur fra  _**en**_ fysisk saksbehandler i vedtaksbrevet (i rollen som beslutter) 
- Brevhodet skal, som ved manuelle vedtak, vise enheten beslutter tilhører:

**Comment by magnefjeld** [comment]
Analyse klar: https://confluence.adeo.no/pages/viewpage.action?pageId=402005508

**Comment by magnefjeld** [comment]
da er løsningsbeskrivelse klar til godkjenning. https://confluence.adeo.no/pages/viewpage.action?pageId=402005508 
Kan dere se over denne i løpet av dagen og gi meg en tilbakemelding, så godkjenner jeg den.

Skiller seg ikke så mye fra analysen, bare mer detaljert.

**Comment by magnefjeld** [comment]
da er denne klar til testing:)

**Comment by magnefjeld** [comment]
https://nav-it.slack.com/archives/C01J0AWRK1C er slackkanal for EL01.

**Comment by tonjemjovik** [comment]
Ting å fikse:

- [ ] JWT-token og navIdent
- [ ] Endre ukjent besvarer til null
- [x] Få saksbehandlerident (både Arenaident og NAVident) i dp-arena-sink

**Comment by magnefjeld** [comment]
https://eur.delve.office.com/?u=fa82d11c-054a-4c83-adb3-8b3fbcacb487&v=profiledetails 
Røyrvik, Eivind Havnelid
Arena:  ERB4405
NAV-ident: R152835

**Comment by tonjemjovik** [comment]
Denne er vel ferdig utviklet og må testes ved at Eivind godkjenner noe så vi kan sjekke at det kommer riktig inn i Arena og brev?

**Comment by Elinvethe** [comment]
Denne kan vel lukkes @magnefjeld  og @Eivind833 ?

**Comment by magnefjeld** [comment]
tenker vi kan lukke denne. Når vi på et tidspunkt lander på at andre signaturer enn kun helautomatisk skal benyttes, så får vi se på det på nytt.
t.o team Arena har allerede lagt til rette for både helautomatiske og delautomatiske signaturer.
@Elinvethe @Eivind833
