### ISSUE TITLE
Anmodningsvedtak 540 - Lærlingeordningen forlenges

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#643]
19.02.21: https://lovdata.no/dokument/LTI/forskrift/2021-02-19-473 :

**§ 2-6 tredje ledd skal lyde:

Hele eller graderte dagpenger etter denne bestemmelsen gis frem til og med 30. september 2021. Lærlinger som er innvilget dagpenger før 1. oktober 2021, kan fortsette å motta dagpenger etter denne bestemmelsen i inntil 52 uker, men ikke lenger enn til og med 31. desember 2021. Folketrygdloven § 4-15 første ledd gjelder ikke.**

-----
Forlenges:
Ny til og med dato for nye tilfeller blir: 30.09.2021

https://www.stortinget.no/no/Saker-og-publikasjoner/Saker/Sak/Voteringsoversikt/?p=82907&dnid=1 Fra voteringsoversikten:

**_Stortinget ber regjeringen umiddelbart gjøre nødvendige endringer i midlertidig forskrift 20. mars 2020 nr. 368 om unntak fra folketrygdloven og arbeidsmiljøloven i forbindelse med covid-19-pandemien, for å forlenge ordningen med inntektssikring for lærlinger (også for nye tilfeller) frem til 1. oktober 2021._**

-----
https://jira.adeo.no/browse/ARENA-5304  - Vedtak 540
Stortinget ber regjeringen forlenge ordningen med inntektssikring for lærlinger (også for nye tilfeller) frem til 01.10.2021
https://www.stortinget.no/no/Saker-og-publikasjoner/Vedtak/Vedtak/Sak/?p=82780

Skal kunne innvilge ny rettighet til og med 30.september 2021, men skal kunne gå på dagpenger ut året som lærling.
--------
https://www.regjeringen.no/no/aktuelt/forlenger-ordning-med-dagpenger-til-larlinger/id2828458/?utm_source=www.regjeringen.no&utm_medium=epost&utm_campaign=nyhetsvarsel%201/13/2021-3:19%20PM&utm_content=Arbeidsliv 

Forlenger ordning med dagpenger til lærlinger
Pressemelding | Dato: 13.01.2021
Regjeringen foreslår å videreføre de særlige vilkårene for dagpenger til lærlinger som blir permittert eller mister jobben.

Etter 31. mars skulle nye tilfeller ikke lenger komme inn i ordningen. Nå foreslår regjeringen at lærlinger som blir oppsagt eller permitterte til og med 30. juni 2021 kan innvilges stønad. De som allerede er innvilget dagpenger eller som blir innvilget dagpenger kan motta disse i 52 uker, men ikke lenger enn ut året.

– Dette gjør vi for å sikre at lærlinger som permitteres eller mister lærlingeplassen sin ikke skal stå på bar bakke, sier arbeids- og sosialminister Henrik Asheim og legger til:

– Lærlingvilkårene er lite benyttet, men likevel viktige for de det gjelder.

---

ref: https://github.com/navikt/dagpenger/issues/600

**Comment by magnefjeld** [comment]
vedrørende @geiralund requested review from @navikt/teamdagpenger on: #35 Anmodningsvedtak 540 - Lærlingeordningen forlenges til 30.6.2021 as a code owner.

så ny til og med dato skal være 30. september 2021:)

**Comment by geiralund** [comment]
@magnefjeld Takk 😅

**Comment by tonjemjovik** [comment]
Datoen for lærling er lagt inn til 31.mars i minsteinntekt og i sats. Dette holder for testen sin del, og kan enkelt endres når eventuell forlengelse blir bestemt. 
Endring i PERIODE er laget men ikke merget? så den ligger foreløpig inne uten tidsbegrensning? @geiralund

**Comment by geiralund** [comment]
Oppdatert minsteinntekt og perioder med forlengelse av lærlingperiode til 30.9.2021
