### ISSUE TITLE
Anmodningsvedtak 535 - Forhøyet kompensasjonsgrad forlenges

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#644]
https://www.stortinget.no/no/Saker-og-publikasjoner/Saker/Sak/Voteringsoversikt/?p=82907&dnid=1 Fra voteringsoversikten: 

**_Stortinget ber regjeringen umiddelbart gjøre nødvendige endringer i midlertidig forskrift 20. mars 2020 nr. 368 om unntak fra folketrygdloven og arbeidsmiljøloven i forbindelse med covid-19-pandemien, for å forlenge forhøyet sats på dagpenger, 80 pst. av dagpengegrunnlag opp til 3 G, til 1. oktober 2021_**

**Ny til og med dato: 30.09.2021**
-----

Når denne blir vedtatt.

Må oppdatere datoer vedrørende sluttdatoer fra 31. mars 2021 til 30. september 2021 

ref: https://github.com/navikt/dagpenger/issues/597 
------

https://jira.adeo.no/browse/ARENA-5304 - Vedtak 535 - Stortinget ber regjeringen forlenge forhøyet sats på dagpenger, 80 % av dagpengegrunnlag opp til 3 G, til 01.10.2021. 
https://www.stortinget.no/no/Saker-og-publikasjoner/Vedtak/Vedtak/Sak/?p=82780

-----

https://www.regjeringen.no/no/aktuelt/forhoyet-dagpengesats-ut-juni/id2828268/?utm_source=www.regjeringen.no&utm_medium=epost&utm_campaign=nyhetsvarsel%201/13/2021-9:19%20AM&utm_content=Arbeidsliv 

Forhøyet dagpengesats ut juni
Pressemelding | Dato: 13.01.2021
Regjeringen foreslår å forlenge den forhøyede dagpengesatsen for permitterte og arbeidsledige til 1. juli.

– Smittesituasjonen og koronatiltakene gjør at arbeidsmarkedet sannsynligvis vil være vanskelig for mange en stund til. For å gjøre situasjonen mer håndterbar for de koronaledige mener vi det er fornuftig å forlenge den midlertidige ordningen med forhøyet dagpengesats, sier arbeids- og sosialminister Henrik Asheim.

I går ble det kjent at regjeringen også forlenger permitteringsperioden og retten til dagpenger til 1. juli.

– Etter hvert som vaksineringen av befolkningen gjennomføres, og smitteverntiltak kan reduseres, vil mange av de som i dag er permitterte eller arbeidsledige komme tilbake i jobb. I mellomtiden vil situasjonen være mer usikker. Med disse forlengelsene gir vi både arbeidstakere og arbeidsgivere mer forutsigbarhet i en vanskelig tid, sier arbeids- og sosialministeren.

Satsen for dagpenger er midlertidig forhøyet til 80 prosent av inntekt under 3 ganger grunnbeløpet. For inntekt mellom 3 og 6 ganger grunnbeløpet er satsen fremdeles 62,4 prosent.

Ordningen med forhøyet sats gjelder for alle som har fått innvilget dagpenger siden 20. mars 2020.
--------------

**Comment by tonjemjovik** [comment]
Til datoen her er satt til 31.03. Dette holder for testen sin del. Datoen kan enkelt endres når forlengelse eventuelt blir bestemt
