### ISSUE TITLE
Analyse - Avvikling av BRUT og innløpet

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#645]
Team intern samhandling som har ansvar for BRUT ønsker et møte for å avklare planene våre for å ta over resten av innløpet, siden BRUT skal avvikles:

**Hei og godt nyttår, Team DP!
Som dere vet ønsker Intern samhandling å skru av Brut001.
Se oversikt her: https://confluence.adeo.no/display/TIS/Modernisering+av+ruting
Vi vil gjerne ha en prat med dere nå for å høre om planer for DAG og ruting som gjenstår i Brut001.**

Jeg har satt opp et møte med Elisabeth (som er PE i team intern samhandling) torsdag 21. januar 2021 fra kl. 13. til 14. men det er greit vi før dette møtet har gjort oss opp noen meninger om hva vi tenker om veien videre.

Arbeidsside på confluence: https://confluence.adeo.no/pages/viewpage.action?pageId=395299663

**Comment by magnefjeld** [comment]
- [ ] Utviklere som skal være med på møtet torsdag 21. januar 2021

**Comment by gtcno** [comment]
- [ ] Finne ut hva som er dagpenger ansvar i Brut.

**Comment by gtcno** [comment]
| Skjemanummer | Vedleggsid | Tittel                                                                      | Tittel_en                                                                                           | Tittel_nn                                                                     | Tema | Gosysid | Beskrivelse (ID) | dekket |
| ------------ | ---------- | --------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------------------- | ---- | ------- | ---------------- | ------ |
| NAV 04-03.07 | A2         | Egenerklæring - overdragelse av lønnskrav                                   |                                                                                                     | Eigenerklæring - overdraging av lønnskrav                                     | DAG  | 196862  | 000000           |        |
| NAV 04-02.03 | D6         | Bekreftelse på ansettelsesforhold                                           |                                                                                                     | Stadfesting av tilsetjingsforhold                                             | DAG  | 196216  | 000000           |        |
| M1           |            | Lønns- og trekkoppgave                                                      | Wage and tax deduction statement                                                                    |                                                                               | DAG  | 458875  | 000000           |        |
| O2           |            | Arbeidsavtale                                                               | Work contract                                                                                       |                                                                               | DAG  | 465304  | 000000           |        |
| M6           |            | Timelister                                                                  | Timesheets                                                                                          |                                                                               | DAG  | 461664  | 000000           |        |
| M7           |            | Brev fra bobestyrer/konkursforvalter                                        | Letter from the trustee/insolvency manager                                                          |                                                                               | DAG  | 461854  | 000000           |        |
| NAV 04-02.05 |            | Søknad om attest PD U1/N-301 til bruk ved overføring av dagpengerettigheter | Application for certificate PD U1/N-301 for coordination of social security rights in EEA countries | Søknad om attest PD U1 - til bruk ved overføring av opptjente dagpengerettar. | DAG  | 196256  | 000000           |        |
| NAV 04-08.03 | G1         | Bekreftelse på sluttårsak/nedsatt arbeidstid (ikke permittert)              |                                                                                                     | Stadfesting på sluttårsak/nedsett arbeidstid (ikkje permittert)               | DAG  | 200365  | 000000           |        |
| S7           |            | Kopi av arbeidsavtale/sluttårsak                                            | Copy of Employment contract / notice or certificate of termination of employment                    |                                                                               | DAG  | 480136  | 000000           |        |
| T3           |            | Tjenestebevis                                                               | Service certificate                                                                                 |                                                                               | DAG  | 480999  | 000000           |        |
| S6           |            | Dokumentasjon av sluttårsak                                                 | Documentation of termination cause                                                                  |                                                                               | DAG  | 480088  | 000000           |        |
| NAV 04-16.04 |            | Søknad om gjenopptak av dagpenger ved permittering                          |                                                                                                     | Søknad om å ta opp igjen dagpengar ved permittering                           | DAG  | 221659  | 000000           |        |
| NAV 04-02.01 |            | Søknad om utstedelse av attest PD U2                                        |                                                                                                     | Søknad om utferding av attest PD U2                                           | DAG  | 196076  | 000000           |        |
| NAV 04-06.05 | BE         | Søknad om godkjenning av utdanning med rett til dagpenger                   |                                                                                                     | Søknad om godkjenning av utdanning med rett til dagpengar                     | DAG  | 197391  | 000000           |        |
| N2           |            | Kopi av søknad                                                              | Copy of the application                                                                             |                                                                               | DAG  | 462447  | 000000           |        |
| N5           |            | Kopi av undersøkelsesresultat                                               | Copy of examination result                                                                          |                                                                               | DAG  | 463518  | 000000           |        |
| NAV 04-06.08 |            | Søknad om dagpenger under etablering av egen virksomhet (utviklingsfase)    |                                                                                                     |                                                                               | DAG  | 197897  | 000000           |        |
| NAV 04-16.03 |            | Søknad om gjenopptak av dagpenger                                           |                                                                                                     | Søknad om å ta opp dagpengar igjen (ikkje permittert)                         | DAG  | 200899  | 000000           |        |
| NAV 04-13.01 | AF         | Egenerklæringsskjema for fastsettelse av grensearbeiderstatus               | Personal statement regarding cross border worker status                                             |                                                                               | DAG  | 263651  | 000000           |        |
| NAV 04-03.08 | G4         | Oversikt over arbeidstimer                                                  |                                                                                                     | Oversikt over arbeidstimar                                                    | DAG  | 287483  | 000000           |        |
| T5           |            | SED U006 Familieinformasjon                                                 | SED U006 Information about your family                                                              |                                                                               | DAG  | 481386  | 000000           |        |
| T2           |            | Dokumentasjon av sluttdato                                                  | Documentation of termination date                                                                   |                                                                               | DAG  | 480989  | 000000           |        |
| T1           |            | Elevdokumentasjon fra lærested                                              | Student documentation from the school/university                                                    |                                                                               | DAG  | 480826  | 000000           |        |
| V6           |            | Kopi av sluttavtale                                                         | Copy of end agreement                                                                               |                                                                               | DAG  | 485836  | 000000           |        |
| U1           |            | U1 Perioder av betydning for retten til dagpenger                           | U1 Periods which are relevant for the right to unemployment benefit                                 |                                                                               | DAG  | 480803  | 000000           |        |
| S8           |            | Sjøfartsbok/hyreavregning                                                   | Sea service / wage settlement                                                                       |                                                                               | DAG  | 480610  | 000000           |        |
| NAV 04-01.03 |            | Søknad om dagpenger (ikke permittert)                                       | Application for unemployment benefits                                                               | Søknad om å ta opp dagpengar igjen (ikkje permittert)                         | DAG  | 196002  | 000000           |        |
| NAV 04-01.04 |            | Søknad om dagpenger ved permittering                                        | Claim for unemployment benefits in the event of temporary lay-off                                   | Søknad om dagpengar ved permittering                                          | DAG  | 273034  | 000000           |        |

**Comment by atleno** [comment]
Ettersendinger:
NAVe 04-01.04
NAVe 04-01.03
NAVe 04-16.03
NAVe 04-16.04

**Comment by Bendreas** [comment]
Ettersendinger på klage også?
NAVe 90-00.08
