### ISSUE TITLE
Finne ut hvorfor det sendes så mange seksjoner

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#653]
Kommer logginnslag på samme seksjon mange manger - f. eks kan en av manuell-seksjonene logges 10 ganger

**Comment by atleno** [comment]
Teori: Har noe med fordelingen av fakta i seksjoner. Hvis en seksjon blir besvart av flere forskjellige oppslag-tjenester, så vil det sendes ekstra seksjoner. Hver seksjon burde bare bli besvart av én tjeneste

**Comment by atleno** [comment]
Fikset nesten problemet ved å dele opp nav-seksjoner etter hvilken tjeneste de blir besvart av.
Spesialtilfelle som fortsatt skjer: Avhengige fakta som er blir besvart senere i treet, blir sendt med seksjonen og besvar, før det egentlige faktumet blir besvart. Derfor kommer samme seksjon to ganger.

Eksempel:
`dato(virkningstidspunkt) førEllerLik dato(senesteMuligeVirkningstidspunkt) `

senesteMuligeVirkningstidspunkt er avhengig av behandlingdato, som ikke blir brukt før senere i treet.
Seksjonen 

`
        Seksjon(
            "senesteMuligeVirkningstidspunkt",
            Rolle.nav,
            dato(senesteMuligeVirkningstidspunkt)
        )
  `

Blir sendt to ganger, én gang med behandlingsdato ubesvart, og én gang med behandlingsdato besvart.

**Comment by rannveigskjerve** [comment]
![meldingsflyt avhengigeFakta](https://user-images.githubusercontent.com/55136985/105825034-66061900-5fbf-11eb-9799-510b9737b48d.jpeg)
