### ISSUE TITLE
Anmodningsvedtak 537 - Søknadsdialogen - Fjerne informasjon om ventetid ( 3 dager).

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#654]
19.02.21 https://lovdata.no/dokument/LTI/forskrift/2021-02-19-473 :

**§ 2-4.Midlertidig opphevelse av kravet om ventetid – unntak fra folketrygdloven § 4-9
Folketrygdloven § 4-9 om ventetid gjelder ikke ved beregning av dagpenger etter dette kapittelet.**

----
https://www.stortinget.no/no/Saker-og-publikasjoner/Saker/Sak/Voteringsoversikt/?p=82907&dnid=1 fra voteringsoversikten

_**Stortinget ber regjeringen umiddelbart gjøre nødvendige endringer i midlertidig forskrift 20. mars 2020 nr. 368 om unntak fra folketrygdloven og arbeidsmiljøloven i forbindelse med covid-19-pandemien, for å oppheve ventetid på tre dager for å motta dagpenger til 1. oktober 2021.**_ 

----------------
https://www.stortinget.no/no/Saker-og-publikasjoner/Vedtak/Vedtak/Sak/?p=82780 
Vedtak 537 Stortinget ber regjeringen oppheve ventetid på tre dager for å motta dagpenger til 01.10.2021.

Vi må gjøre tilpasninger i den digitale søknadsdialogen. Ref: https://github.com/navikt/dagpenger/issues/589

Forslag til endre tekster, se vedlegg for info. Her kan man gjenbruke pre 1.1.21 versjon, ved å bare oppdatere fra 12 til uker om forlenget ventetid, de 2 stedene som det skal gjøres endringer.
[ventedager_SD_fjerne_AV537.docx](https://github.com/navikt/dagpenger/files/5854840/ventedager_SD_fjerne_AV537.docx)

Kommer tilbake til mer detaljer når vi vet mer om implementeringen.

**Comment by magnefjeld** [comment]
https://jira.adeo.no/browse/ARENA-5304

**Comment by magnefjeld** [comment]
regner med at når det gjøres oppdateringer, så gjelder det både for ny søknad og gjenopptak?

**Comment by magnefjeld** [comment]
Må ses i sammenheng med, som er andre tilpasninger i SD relatert til annet anmodningsvedtak. https://github.com/navikt/dagpenger/issues/655

**Comment by kmriise** [comment]
Dette er klart til deploy på branch: https://github.com/navikt/dp-soknad-server/compare/fjern-ventedager
