### ISSUE TITLE
Anmodningsvedtak 538 - Søknadsdialogen - Nytt spørsmål 

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#655]
https://www.stortinget.no/no/Saker-og-publikasjoner/Vedtak/Vedtak/Sak/?p=82780
Vedtak 538 - Stortinget ber regjeringen forlenge maksimal periode for mottak av dagpenger til 01.10.2021, også for de tilfeller som gikk ut over maksimal periode fra 1. november til datoen endringen er implementert.

1.
Vi må gjøre tilpasninger i den digitale søknadsdialogen. 

Innholdsteamet og Kamile holder i dette. Utformingen av spørsmålet, samt informasjonsbrevet som skal ut https://jira.adeo.no/browse/DOK-1901 for disse, samt informasjon på nav.no må ses i sammenheng. Opprettet: https://trello.com/c/5fRNbLYv/164-dagpenger-anmodningsvedtak-av-19-januar-2021-knyttet-til-covid-19 https://jira.adeo.no/browse/ARENA-5304

Utkast til spørsmål mv finner man på (må også oversettes til engelsk): https://navno.sharepoint.com/:w:/s/Teamregelverkdagpenger/EVLwT6QFhnVKowIFOanYS0oBJgx7NkkBtQ2a3y9rZ-WPXg?CID=1ECB9DC9-41BF-4D66-9593-603935142127&wdLOR=cD3D68DF3-45EF-4E39-891E-C9167CD0A5C0

**### _Forslag til spørsmål i søknadsdialogen - Fornyet rett til dagpenger 

Det foreslås at det lages egen spørsmålsdel før tilleggsopplysninger i søknadsdialogen.  
 
Overskrift: Fornyet rett til dagpenger ifm koronatiltak  
Spørsmålsformulering: - Ble dagpengeperioden din avsluttet etter 31. oktober 2020? 
Svaralternavtiver: Ja/Nei/(vet ikke) 
  

Veiledningstekst: 
Dette spørsmålet gjelder for deg som har nådd maksimal dagpengeperioden etter 31 oktober frem til 1 februar. Du kan søke om å få dagpenger igjen og fortsette på dagpengene som ble avsluttet. Hvis du er berørt av dette har du mottatt et eget brev med informasjon._** 

Forretningsregler, når bruker svarer JA på det nye spørsmålet (Avklart, se kommentar fra 25.1.21):
- Ruting: **Følge eksisterende logikk med 4450 eller 4455 avhengig av om søknad er permittert eller ikke, samt gjenopptak eller ikke.**
- Merking (oppgavebeskrivelse) i Arena: Anmodningsvedtak 538
- Hierarki: **Skal ha 1. prioritert i hierarkiet, så om flere merking slår til skal denne type søknader ha forrang.**

2.
https://jira.adeo.no/browse/ARENA-5269
Behov for endringer/tilpasninger i REST-tjenesten mot DD, slik at Arena kan opprette vedtak og kjøre arbeidsprosessen automatisk til Forbered vedtak, hvor vedtaket arver nødvendige opplysninger. Dette basert på det nye spørsmålet i søknadsdialogen. Dette vil spare saksbehandler for betydelig tid. Ca. 8000 brukere er kandidater (ytterpunktet).

Team Arena (Hatlevoll) kommer med mer info hva som trengs av informasjon, sannsynligvis mandag 25.januar 2021.

**Comment by magnefjeld** [comment]
Må ses i sammenheng med, som er andre tilpasninger i SD relatert til annet anmodningsvedtak. 
https://github.com/navikt/dagpenger/issues/654

**Comment by magnefjeld** [comment]
Husk å sette opp metrikker her, på samme måte som vi gjorde for https://github.com/navikt/dagpenger/issues/614. Skal også inn de samme stedene i datapakken: Produktområde arbeid - nøkkeltall dagpenger , under overskriftene: 
- Gjennomsnittlig antall dager mellom søknad og fattet vedtak
- Svar oppgitt i digitale søknader etter 12. mars 2020

**Comment by magnefjeld** [comment]
https://navno.sharepoint.com/:w:/s/Teamregelverkdagpenger/EVLwT6QFhnVKowIFOanYS0oBJgx7NkkBtQ2a3y9rZ-WPXg?CID=A99C8DC4-5724-492F-ABC8-A1AADF9812F9&wdLOR=cCF49338C-AB2F-4DBD-A24B-9B3231F9F02F 
Laget utkast til spørsmål mv, som er godkjent av KOM v/ellen hov

**Comment by magnefjeld** [comment]
Fra: Dalflyen, Erik <Erik.Dalflyen@nav.no> 
Sendt: mandag 25. januar 2021 07:36
Til: (PK) NAV Produktområde Arbeid <nav.produktomrade.arbeid@nav.no>
Kopi: Fjeld, Magne <Magne.Fjeld@nav.no>; Thomassen, Bente <Bente.Thomassen2@nav.no>; Østli, Torunn <Torunn.Ostli@nav.no>
Emne: VS: Dagpenger - Anmodningsvedtak 538 - Behov for innspill til eventuell merking og ruting.

Dagpenger - Anmodningsvedtak 538 - Behov for innspill til eventuell merking og ruting.

Med den informasjonen NAV Arbeid og ytelser per i dag har rundt denne problemstillingen er vår tilbakemelding at vi ønsker merking av aktuelle oppgaver/saker i Arena. 

Det vil si at det i oppgavebeskrivelsen til de aktuelle oppgavene i Arena tydelig fremkommer at dette gjelder «Anmodningsvedtak 538» Vi foreslår derfor at oppgavebeskrivelsen til de aktuelle oppgavene settes til «Søknad Anmodningsvedtak 538» Eventuelt bare «Anmodningsvedtak 538». Dette for at det eventuelt på en senere tidspunkt skal bli enkelt å kunne identifisere og sortere ut disse sakene hvis det skulle bli nødvendig.

 
![image](https://user-images.githubusercontent.com/61459197/105673951-105e3d80-5ee7-11eb-9062-2e6a559b95fd.png)


Rutingen for disse oppgavene skal følge de ordinære rutingreglene for dagpengesøknader (ny rettighet og gjenopptak).

Ovennevnte anbefaling/ønske er fremsatt på bakgrunn av den informasjonen vi har om saken per i dag.  Fremkommer den nye informasjon som tilsier at  anmodningsvedtak 538 skal håndteres vesentlig annerledes enn vi tror i dag, kan det oppstå andre behov for merking/ruting.

Med vennlig hilsen
Erik Dalflyen
Seniorrådgiver // Prosess og utvikling 
NAV Arbeid og ytelser styringsenhet
 959 92 136    
www.nav.no

**Comment by kmriise** [comment]
Søknadsdialog:

- [x] Opprette en ny bolk
- [x] Opprette nytt spørsmål i bolk
- [x] Legge til fakta i server
- [x] Legge på en constraint slik at fakta ikke prøver å gå til oppsummering hvis det ikke finnes fra tidligere søknad
- [x] Migrere til ny søknadsversjon?
- [x] Endre nesteknapp til å ikke vise lagre endring, da endring lagres automatisk uanz
--------Dette er pga legacy, nesteknappen vises hele tiden, men hvis man går fra oppsummering tilbake til søknad så vil "lagre endring" vises, selv om faktaene autolagres.----------
- [x] Legge på tekster --kopiere over engelske placeholdere--
- [x] Legge på logikk for spørsmål -- trengs ikke, simpelt spørsmål gikk automagisk --
- [x] Legge på validering -- trengs ikke, simpelt spørsmål gikk automagisk --
- [x] Opprette enda et spørsmål i bolk, for å sjekke om de faktisk ønsker å bruke seg av den nye retten
- [x] Sjekke at oppsummering også er på stell

Ruting:

- [x] Legge til en sjekk for det nye flagget

- [x]  Innløpet identifiserer svarene og ruter “ja”ene til spørsmålet over til oppgavebenk “4455COR”  med oppgavetype “Behandle henvendelse - Person” og med søknadsregistrertdato som fristdato  samt setter oppgavebeskrivelsen til “Anmodningsvedtak 538"

~Tilpasning REST tjenesten?:~
~Gjøre noe i innløpet for å kalle på en annen tjeneste~

**Comment by magnefjeld** [comment]
slack-kanal for samhandling med team arena: https://nav-it.slack.com/archives/GVDG8RAP5 (arena_dagpenger)

**Comment by geiralund** [comment]
Commit 
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/1fa8c60073e5a0e116a9bfef5ebb2430b66f9e0b
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/8dfa74b48aa67b133bcae93db674e80541adbbdc
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/06adf75e34a4e512c31f9c4f2a1492bc0c466708
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/446ac53e0eca36554a74b928e46800fe666c8b10 

Tilhører denne - ble commitet på feil sak.

**Comment by magnefjeld** [comment]
https://jira.adeo.no/browse/FAGSYSTEM-154461 automatisk test som ikke funket, hva gjelder oppsummeringen.
Feilen rettet i produksjon og og testen rettet så den ikke feiler igjen.
