### ISSUE TITLE
Gjeninnføre kravet til redusert minsteinntekt

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#657]
Forskriften: https://lovdata.no/dokument/LTI/forskrift/2021-02-19-473:

![image](https://user-images.githubusercontent.com/61459197/108523240-f806f600-72cd-11eb-8a3d-78f11ba91610.png)

---------------

https://www.stortinget.no/no/Saker-og-publikasjoner/Saker/Sak/Voteringsoversikt/?p=82907&dnid=1 Fra voteringsoversikten:

**_Stortinget ber regjeringen umiddelbart forlenge ordningen med lavere inntektsvilkår for å motta dagpenger (0,75 G de siste 12 månedene eller 2,25 G de siste 36 månedene) for nye tilfeller så lenge krisen varer, nå til 1. oktober 2021._**

- [x] Mangler forskrift som sier noe om fra hvilken dato dette skal gjelde i fra. Fått beskjed fra ASD at det endringene trer i kraft fra idag (19.02.21). 

**Fra og med 19.02.2021"
Til og med dato blir : 30.09.2021**

-----

Redusert krav til minsteinntekt er foreslått gjeninnført. Vi vet ikke fra hvilken dato enn, men det står 29.1.21: Reglene skal gjelde så snart Stortinget har gjort vedtak om økt bevilgning til dagpenger og det praktisk er tilrettelagt for nye regler i Navs systemer.

Vil bli, som sist gang:
0,75 ganger grunnbeløpet siste 12 måneder, eller
2,25 ganger grunnbeløpet siste 36 måneder før kravdato

På https://github.com/navikt/dagpenger/issues/564 avviklet vi kravet til redusert minsteinntekt fra 1.11.20:

**Comment by magnefjeld** [comment]
kan vente litt med denne. Kommer ikke til 1.2.21, men sannsynligvis senere. legges tilbake på hold

**Comment by magnefjeld** [comment]
https://www.regjeringen.no/no/aktuelt/foreslar-senkede-krav-for-rett-til-dagpenger/id2830663/?utm_source=www.regjeringen.no&utm_medium=epost&utm_campaign=nyhetsvarsel%201/29/2021-12:20%20PM&utm_content=Arbeidsliv 

**Foreslår senkede krav for rett til dagpenger**
Pressemelding | Dato: 29.01.2021
Regjeringen foreslår å lempe midlertidig på inngangskravene for dagpenger, slik at flere av de som nå blir ledige eller permitterte kan få dagpenger. Kravet til tidligere inntekt for å kvalifisere for dagpenger senkes. I tillegg reduseres kravet til tapt arbeidstid, slik at folk som kun er permittert 40 prosent også kan få dagpenger.

– Med disse endringene vil flere av dem som tjener minst, for eksempel fordi de jobber deltid, kunne få dagpenger. I tillegg blir det enklere å kombinere jobb og dagpenger ved at folk som er minst 40 prosent ledig eller permittert, får dagpenger samtidig som de jobber og beholder lønnen for den delen de jobber. Det gir mer fleksibilitet i denne krevende situasjonen, sier arbeids- og sosialminister Torbjørn Røe Isaksen.

### **Senker kravet til tidligere inntekt og til tapt arbeidstid**
Konkret foreslår regjeringen at den nedre inntektsgrensen for rett til dagpenger senkes fra 1,5 G til 0,75 G siste 12 måneder eller 2,25 G siste 36 måneder. Dette gjelder både permitterte og arbeidsledige.

I tillegg foreslår regjeringen at kravet til redusert arbeidstid for rett til dagpenger senkes fra minimum 50 prosent til minimum 40 prosent. Dagpengene faller dermed først bort når en permittert jobber mer enn 60 prosent av tidligere arbeidstid.

– Nå kan for eksempel en fulltidsansatt som permitteres to arbeidsdager i uka få rett til dagpenger. Da kan man ha mer «rullerende permitteringer» slik at færre permitteres helt. Det gjør den økonomiske situasjonen bedre for den enkelte arbeidstaker, samtidig som det gir mer fleksibilitet for arbeidsgiverne, sier statsråden.

Reglene skal gjelde så snart Stortinget har gjort vedtak om økt bevilgning til dagpenger og det praktisk er tilrettelagt for nye regler i Navs systemer.

### **Følger situasjonen tett**
De samme særreglene gjaldt også i en periode i 2020, men ble avviklet 1. november 2020 fordi det var bedring i arbeidsmarkedet. Nå gjeninnføres de for en periode frem til og med 30. juni 2021.

– Vi har hele tiden vært tydelige på at vi følger situasjonen tett og foreslår nødvendige tiltak og justeringer fortløpende. Det har vi gjort gang på gang gjennom disse krevende tidene, og det vil vi fortsette med også i tiden fremover, sier statsråden.

**Comment by tonjemjovik** [comment]
Vi har lagt inn periode 2 fra 01.02.2021 til 30.06.21. 
Har laget PR, så kan merges når det er behov for endringen i Q.
t.o.
@magnefjeld

**Comment by ChrisdeVriesEnger** [comment]
Testet ok i Q0 (Se https://jira.adeo.no/browse/ARENA-5317# )

**Comment by kmriise** [comment]
produksjonssatt
