### ISSUE TITLE
Fagsystemsak 151012 - Mld til Arena fra Gosys på feil fnr

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#661]
Ref: https://jira.adeo.no/browse/FAGSYSTEM-151012

Ser mer informasjon i jira.

**Comment by magnefjeld** [comment]
Mona oppdatert kommentar på fagsystemsaken.

**Comment by atleno** [comment]
Ikke noe vi kan gjøre uten bedre feilmelding fra arena, har kommentert det samme i saken @magnefjeld
