### ISSUE TITLE
ROS for å få tilgang til databaser via naisdevice

### ISSUE THREAD

**Issue by Bendreas** [navikt/dagpenger#681]
Vi kan nå få tilgang til databasene våre i prod. Kopiert fra slack: 
> For å få tilgang til databasen fra naisdevice, må man whiteliste den i database-iac, og det gjør man ved å legge til

```  
naisdevice:
    enabled: true
```

> Før man legger til det på databasen sin, må man kjøre en liten risikovurdering sammen med @leif.tore.lovmo.

https://nav-it.slack.com/archives/C010WR3ALNR/p1611051372002600

**Comment by gtcno** [comment]
Dette er jo gjort..

**Comment by Bendreas** [comment]
Lol allerede gjort, ja
