### ISSUE TITLE
Møte fredag 19. februar 2020 - 10.00 til 11.00 - Økt dagpengesats til de med vedtak fra før 20. mars 2020

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#682]
Det er satt opp et møte fredag 19. februar 2020 - 10.00 til 11.00, om hvordan løse forhøyet dagpengesats til de som har vedtak fra før 20.mars 2020.

Sendt innkalling til alle utviklerne, så bestemmer dere hvem som møter. Mer info står i innkallingen.

Viktig at man setter seg inn i saken før møtet:

**Viktige lenker:**

- https://confluence.adeo.no/pages/viewpage.action?pageId=402012060 (løsningsbeskrivelse/analyse Arena-5370)
- https://jira.adeo.no/browse/ARENA-5370 
- https://jira.adeo.no/browse/ARENA-4582 (hører til https://github.com/navikt/dagpenger/issues/575)

**Comment by magnefjeld** [comment]
**Tema:**

Hei

Blitt bedt om å flytte møtet 1 time frem – håper dere fortsatt kan delta

Innstillingen fra komiteen:
Stortinget ber regjeringen endre dagpengereglene slik at personer som fikk innvilget dagpenger før 20. mars 2020, fra 1. februar 2021 får økte satser lik den midlertidig forhøyede dagpengesatsen

https://jira.adeo.no/browse/ARENA-5370

Tonje, Magne, Chris og jeg hadde et møte i dag der vi diskuterte ulike muligheter. Vår hypotese er foreløpig at endringsvedtak bør gjøres maskinelt. Videre er noen av de objektene vi trenger for å løse denne saken, det samme vi trenger for korrekt å avvikle særregelen for satsberegning 1. oktober.
Ut over dette, har vi en hypotese om at det øvrige må gjøres manuelt – det vil si samordning av et antall av 24.000 saker og manuell etterbetaling av meldekort som allerede er beregnet med gammel sats.

Har vi noen geniale ideer til en annen måte å nå målet på?

Innkaller med denne bakgrunn til møte for å diskutere mulige løsninger. Dere videresender innkallingen til andre som bør delta

Her er tilbakemeldingen vi ga i slutten av forrige uke
Vi viser til e-post under og spørsmålet om vurdering av gjennomføringstidspunkt/administrative konsekvenser av forslaget.
 
NAV har gjennomgått ønsket om å gi midlertidig bedre dekning også til dagpengemottakere som hadde fått innvilget dagpenger før 20. mars 2020. Saken reiser to problemstillinger;

1.	Tid og kapasitet til utvikling av nødvendig minimumsløsning
2.	Virkning tilbake i tid med eventuell etterbetaling av allerede utbetalte meldekort eller virkning frem i tid
 
1	Utviklingstid og kapasitet
 
Denne endringen kan ikke gjennomføres på kort varsel. 
 
Hovedårsaken er at det kreves nye opplysninger i kommunikasjonen mellom flere systemer for å få gitt beskjed om å regne ut bedre dekning basert på regler som skal gjelde fra en bestemt dato, men uten å hente nye inntekter eller fastsette dagpengegrunnlaget på nytt. Dette ble ikke utviklet da høyere sats ble innført med virkning fra 20. mars 2020. 
 
Det må videre gjøres endringer i håndteringen når forsørgede barn fyller 18 år og i beregninger som følge av endringer i folketrygdens Grunnbeløp.
 
Endringen omfatter betydelige endringer i grunnleggende funksjonalitet for regelhåndtering, datohåndtering og informasjonsutveksling og må derfor testes godt. Endringen kan ikke implementeres på kort varsel uten høy risiko for feil i kommunikasjon mellom systemer som er i kritisk linje for innvilgelse og utbetaling av dagpenger, samt risiko feil i utregning av dagpengesats og dermed feil vedtak og feil utbetaling. 
 
Ny dagpengesats betyr at samordning med andre ytelser må gjøres på nytt. Det legges til grunn av all samordning med andre ytelser skal foretas manuelt. Dette antas å være håndterbart.
 
Det antas videre at personer i målgruppen som i øyeblikket ikke har løpende dagpenger f.eks fordi de har ferie, er syke, skal gis bedre dekning dersom de på et senere tidspunkt gjenopptar dagpengene. det må derfor finnes en løsning for denne gruppen.
 
2	Virkning tilbake i tid med eventuell etterbetaling av allerede utbetalte meldekort
 
Det legges videre til grunn at endringen automatisk kun kan gjennomføres frem i tid. 
 
Dersom endringen skal gjelde tilbake i tid fra et tidspunkt der NAV ikke har hatt tid til å implementere en løsning, vil det også måtte beregnes en etterbetaling for de periodene dagpenger allerede er utbetalt.
 
NAV har i dag ingen løsning for maskinell etterbetaling av dagpenger. Et unntak er etterbetaling som følge av justering av folketrygdens grunnbeløp som er en helt egen operasjon som er planlagt i slutten av mai. 
 
Dersom endringen skal gis med tilbakevirkende kraft for perioder som allerede er beregnet, vil NAV enten måtte
1	lage helt ny funksjonalitet for maskinell beregning og utbetaling. Dette vil være omfattende utvikling som ikke kan gjennomføres uten at flere andre utviklingsbehov stilles i bero 
2	eller beregne og etterbetale alle utbetalte meldekort manuelt. Det siste vil ta dagpengesaksbehandlere vekk fra behandlingen av nye dagpengesaker.
 
Det enkleste for NAV ville være om endringen vedtas med virkning fra et tidspunkt som gjør at NAV rekker å utvikle funksjonaliteten i forkant av virkningsdato.
 
Vi vil komme tilbake med tall for hvor mange saker dette antas å omfatte. 
 
Vi vil imidlertid allerede nå understreke at det bare for en enkelt bruker kan dreie seg om et betydelig antall meldekort der NAV må vurdere å etterbetale dagpenger manuelt. Dette vil være en krevende oppgave selv med et lite antall personer i målgruppen. Antall meldekort som må vurderes på nytt avhenger av hvor lang tid det går mellom fastsatt virkningsdato for endringen og det tidspunkt NAV kan få på plass endringen.

**Comment by atleno** [comment]
Referat:
Arena sender oss regelverksdato - se https://github.com/navikt/dagpenger/issues/575 
Kun endring i sats-regelen
Lansering 1. mai, hvis det er mulig for arena å bli ferdige innen da.

**Comment by atleno** [comment]
Spørsmål som dukket opp:
Burde vi ha et endepunkt som arena skal spørre for å vite hvilke regel som gjelder ved meldekortberegning
