### ISSUE TITLE
Utvidelse av søknadsdialog - EØS_pendler

### ISSUE THREAD

**Issue by 80IngeborgA80** [navikt/dagpenger#683]
Gi tydelig informasjon i søknadsdialogen til ikke-grensearbeidere at de har en valgmulighet med hensyn til hvilke land de vil søke dagpenger i, at de ved å søke anses for å utøve dette valget, og at det at de velger Norge forutsetter at de blir værende her. De bør også få informasjon om at dersom de på et senere tidspunkt skulle ønske å vende tilbake til bostedslandet og i stedet få ytelser derfra så har de mulighet for det. Om de med bakgrunn i å ha fått denne informasjonen, fortsetter søknadsprosessen, bør man kunne legge til grunn at de også har valgt å bli værende her.

**Comment by 80IngeborgA80** [comment]
En ikke-grensearbeider er en EØS-pendler som sjeldnere enn én gang i uken har reist tilbake til bosettingslandet. EØS-pendleren kan være norsk statsborger eller statsborger i et annet EØS land. Et eksempel er de som jobber off-shore, og drar tilbake til Polen når de har friperioder. Websaknr: 20/1020

**Comment by magnefjeld** [comment]
Må koordineres med innholdsteamet. Vil også kreve at det skrives informasjon om dette på nav.no. 
I tillegg, er behovet veiledning alene eller nytt spørsmål + veiledning (?)
Må avklares sammen med innholdsteamet, samt NAY, KAN og NKS (som er representert innholdsteamet)

**Comment by SynnevaAasbrenn** [comment]
Vi tenker dette er et større arbeid som det er naturlig å se på i en helhet når nytt rundskriv om dagpenger og EØS kommer. Arbeid med nytt rundskriv er i gang.

**Comment by magnefjeld** [comment]
Kan være vi må vurdere hvordan det "nye behovet" treffer eksisterende spørsmål i søknadsdialogen (som for øvrig ikke vises alle, kun ikke norske ? Burde vises til alle som søker.): 
![image](https://user-images.githubusercontent.com/61459197/112820335-cbd95480-9085-11eb-9ed3-b316aa531eeb.png)

NB, vær oppmerksom på merking og rutingregler knyttet til dette spørsmålet:
https://confluence.adeo.no/pages/viewpage.action?pageId=377711140

**Comment by Elinvethe** [comment]
Avventer rundsrkrivsarbeidet  - hør med Magne

**Comment by EivindRoyrvik** [comment]
Vi arbeider med en hypotese om å redusere krav til vedlegg, som kan kreve endringer i søknadsdialogen, se [Confluence](https://confluence.adeo.no/display/TDP/INI+Hypotese+vedlegg+O2T6T8)

**Comment by magnefjeld** [comment]
@Eivind833 Hei. snakket litt med Kjetil Woldmo. Rundskrivet her er vistnok snart klart for oversending til godkjenning. Vi burde her vurdere hvilke endringer vi tenker å gjøre for å møte behovet. Vi må tilpasse søknadsdialogen her, slik jeg har forstått.


Mine tanker: 
1. Alle dagpengesøkere får vist spørsmålet "Bor du i et annet EØS-land og arbeider eller har arbeidet i Norge"". Dette er også relevant for norske statsborgere, og merkelig at vi ikke allerede idag gjør. 
2. Hva gjelder dette med å velge, nytt spørsmål med veiledning som alle må svare på eller bare veiledning ? Det må vi diskutere, hvordan vi best ser for oss at vi møter behovet.

@Eivind833 hva tenker du ?

t.o @Elinvethe

**Comment by magnefjeld** [comment]
@Eivind833 hei igjen:)
jeg snakket tilfeldigvis med Hege Haugen, og da kom vi inn på denne (siden rundskrivene er rett rundt hjørnet).
Så her er det egentlig bare å koble seg på synneva og innholdsteamet  (samt hege), så kan man se hvordan man løser behovet best. Da får man også tilgang til vidar håland på KA (via Hege), som holder i det meste hva gjelder EØS.
Så får vi den gode sammenhengen mellom informasjon på nav.no, hva som står i rundskrivene, samt hvordan behovet løses best faglig sett i søknadsdialogen .

**Comment by magnefjeld** [comment]
Når du skal se på denne @Eivind833 , og vi skal inn å gjøre endringer i søknadsdialogen, så burde vi vurdere å samtidig å gjøre endringer med bakgrunn i 2 andre endringsforslag fra NAY:

- [ ] https://github.com/navikt/dagpenger/issues/727 
- [ ] https://github.com/navikt/dagpenger/issues/726

Så kan du ta det med innholdsteamet samtidig, og forankre :)

Deretter:

- [ ] Lage bestilling på endring av søknadsdialogen på bokmål/engelsk, ny og gjenopptak til "inn fra siden
- [ ] Lage fagmelding med presentasjon i seg av endringene (henni-karine godkjenner språket i fagmeldingen + publiserer på NAVET på sidene til POA og Dagpenger)
- [ ] Sende ut presentasjon til ROer/YA m.fl iht rutine
- [ ] Arkivere i websak (20/16174
- [ ] Dele lenke til fagmelding med presentasjon på teams "dagpenger med venner"


t.o @Elinvethe 


Bare å spørre om det er noe , og oppdager du flere ting som du tenker at det er hensiktsmessig å gjøre i søknadsdialogen, så er det bare å ta det med elin/magne:)

**Comment by EivindRoyrvik** [comment]
@magnefjeld 

Jeg er enig i at dette gjelder alle. Lovvalgsreglene gjelder for norske statsborgere som alle andre EØS-borgere.  
Regelen om at en person kan velge hvor hen vil søke ved å velge å reise til bosettingslandet eller ikke kan vi informere tydeligere om. Jeg tenker det viktigste i normale tilfeller er informasjon på nav.no, ser det er informasjon [her](https://www.nav.no/no/person/arbeid/dagpenger-ved-arbeidsloshet-og-permittering/relatert-informasjon/hvordan-s%C3%B8ker-du-arbeidsledighetstrygd-etter-jobb-i-E%C3%98S-land) og [her](https://www.nav.no/arbeid/en/dagpenger-og-eos). Vi bør emm. prøve å sikre at brukere kan ta et informert valg om de ønsker å vende hjem eller ikke. 

Også enig i at vi bør innarbeide informasjon i selve søknaden. Praksisen på dette området har beveget seg mot å blant annet vektlegge hensikt med hjemreise mer enn før, og det moment at en ønsker å bli i Norge og søke arbeid her, selv om en har hatt et opphold i annet EØS-land. Midlertidig praksis er at en alltid godtar opphold i inntil fire uker, men oppholdet kan også være lengre ved spesielle omstendigheter uten at lovvalget har skiftet. Hva endelig praksis blir tenker jeg vi vet mer sikkert når EØS-rundskrivet kommer. 

Jeg tenker en løsning kan være å innarbeide en informasjonsside i starten av søknaden, hvor bruker kan krysse av for at informasjonen er lest og forstått, og ved å gå videre bekrefter bruker at hen ønsker å søke arbeid i Norge og som hovedregel oppholde seg i Norge. Mulig vi også må ha spørsmål om de har reist hjem eller ikke? Hvis ja, hvor lenge og hvorfor?

Videre utarbeider jeg tekstforslag på denne #683 og #727 #726 som vi så kan forankre hos innholdsteamet. T. o @Elinvethe

**Comment by magnefjeld** [comment]
Hatt et kort møte med Kjetil og Ingeborg.
Viktig at det synkes samtidig her (publisering av endringene i rundskrivet, fagmelding, nav.no og søknadsdialog.) Lite trolig vi rekker det nå, kanskje tidligst i august 2021.
Hypotesen er nytt spørsmål i søknadsdialogen, om JA/NEI så er det også et spørsmål om de som svarer JA (og sender inn søknaden, om den skal rutes spesielt, f.eks. 4470 eller 4465). Men litt tidlig ennå å ta stilling til dette. 

kun tekstlig veiledning i søknadsdialogen er sannsynligvis ikke tilstrekkelig.

**Comment by Elinvethe** [comment]
fra møte 8.7. med kjetil,  Ingeborg og @ingridhaland . Endringen haster ikke, men forventning vi kan endre på søknadsdialogen i  august. Det vikigste blir derfor å se på hvordan dette kan løses i søknaden, og så må selve prodsettingen synkes med alt det andre som skal oppdateres samtdig. Ta kontakt med Kjetil eller Ingeborg for å avklare hvilken dato vi skal prodsette endringen
 
Hensikten med endringen i søknadsdialgen er at bruker skal ta et bevisst valg på hvor man søker dagpenger i fra. 
Ingeborg skal ettersende rundskriv for klarhet i ny regeltolkning/praksis.
 @Eivind833  fint om du ser på denne når du er tilbake fra ferie, og kan også sparre med Ingrid og utivkler på hvordan dette bør løses i søknaden. Det vil bli en slags erklæring på lovvalg i søknaden og da må det formuleres på en slik måte at bruker kan forstå konsekvensen av valg. For endringer underveis i dagpengeløpet (som søkandsdialogen ikke kan dekke) bør det ses på om det må gi noe mer infomasjon rundt melding av endringer som får konsekvens for ytelsen

**Comment by EivindRoyrvik** [comment]
Her er det forskjellige mulige løsninger. En generell "egenerklæring" som skal treffe alle tror jeg blir veldig lang, om vi skal klare å informere om de fleste mulige scenarier. 

Det vi imidlertid mangler i dag i søknadsdialogen er spørsmål om bosted og om bruker har vendt hjem. Status på arbeidsforhold og arbeid i EØS har vi egne spørsmål for. En mulig løsning er å ta med spørsmål om bostedsland for alle, for å gjøre søknaden så komplett som mulig. Men samtidig unngå for mye tekst/informasjon til flertallet av brukerne hvor dette ikke er et aktuelt tema. Reglene kan oppfattes litt kompliserte, og definisjonen av bostedsland er heller ikke helt intuitiv. 

Tekstforslag vi kan diskutere ligger [her](https://navno.sharepoint.com/sites/TeamDagpenger/Shared%20Documents/Forms/AllItems.aspx?viewid=4304c417%2D4e1d%2D42b3%2D8031%2D5a175d764c78&id=%2Fsites%2FTeamDagpenger%2FShared%20Documents%2FGeneral%2FTekstforslag%20til%20s%C3%B8knadsdialogen)

Tredjeland og Storbritannia er også en egen issue #888

**Comment by EivindRoyrvik** [comment]
- [x] Oversendt innholdsteamet for gjennomgang
- [x] Rette feilmeldinger under bostedsland-valgt EØS-land
- [x] Bestille oversettelse til engelsk
- [x] Gjøre samme endring for gjenopptak og engelske søknader
- [x] Fjerne nåværende grensearbeiderspørsmål som gis til ikke-norske statsborgere - kontroller at rutingen går riktig
- [x] Sjekke og legge inn lenker til informasjonssider på nav.no. Valg bostedsland Storbritannia, [informasjon om Brexit](https://www.nav.no/no/nav-og-samfunn/innhold-til-nav-og-samfunn-forside/nyheter/brexit-og-informasjon-pa-regjeringen.no) og denne under [bostedsland](https://www.nav.no/no/person/arbeid/dagpenger-ved-arbeidsloshet-og-permittering/relatert-informasjon/hvordan-s%C3%B8ker-du-arbeidsledighetstrygd-etter-jobb-i-E%C3%98S-land). Har bestilt noen mindre endringer på nav.no, som er levert. Ønskelig med større revisjon, men det må vente grunnet kapasitet hos innholdsteamet
- [x] Fjerne grensearbeid fra faktum (ETTER DEPLOY)

**Comment by EivindRoyrvik** [comment]
Klar for prod - venter på publisering av rundskriv og fagmelding

**Comment by EivindRoyrvik** [comment]
Prodsatt endringen 30. august 2021
