### ISSUE TITLE
Søknadsdialog - Slette tekst i spørsmål og slette infoboks - spørsmål om fortsatt rett

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#684]
Ref https://github.com/navikt/dagpenger/issues/655 

Det er et behov for å slette tekst i spørsmål og slette infoboks.

norsk/engelsk og ny/gjenopptak

Årsaken til dette er at det foreløpig er uklart om brukere som har nådd max-periode i perioden 1. februar til og med 18. februar, skal ha "fortsatt rett" eller "forlengelse.

**Comment by magnefjeld** [comment]
Kamile tar det med innholdsteamet og kommer tilbake med oppdatert forslag til tekst på bokmål og engelsk

**Comment by magnefjeld** [comment]
står idag:

![image](https://user-images.githubusercontent.com/61459197/108962639-57bc2300-7679-11eb-8d19-fc43fc378f5c.png)
![image](https://user-images.githubusercontent.com/61459197/108962668-60acf480-7679-11eb-9252-a2449b5c14f8.png)

**Comment by SynnevaAasbrenn** [comment]
Vi i innholdsteamet foreslår å fjerne informasjon om brev, det første spørsmålstegnet og 1. februar:
----
**Fortsatt rett til dagpenger på grunn av koronasituasjonen**
Dersom du har brukt opp dagpengeperioden etter 31. oktober 2020 kan du søke om å fortsette på dagpengene som ble avsluttet. Dette er en midlertidig særregel på grunn av koronasituasjonen.

Har du mottatt dagpenger som ble avsluttet fordi dagpengeperioden din ble brukt opp etter 31. oktober 2020?
----
<img width="801" alt="Screenshot 2021-02-24 at 11 33 47" src="https://user-images.githubusercontent.com/57761592/108988059-4f251600-7694-11eb-9b5c-f3ae866595b1.png">

**Comment by magnefjeld** [comment]
er den klar til test i Q?

**Comment by atleno** [comment]
nei, ikke enda, men får det ut i morgen

**Comment by magnefjeld** [comment]
![image](https://user-images.githubusercontent.com/61459197/109129332-d33cd380-7750-11eb-94d2-aa8b35e87ebd.png)
![image](https://user-images.githubusercontent.com/61459197/109129363-dd5ed200-7750-11eb-9eaf-45bb0f337797.png)
![image](https://user-images.githubusercontent.com/61459197/109129607-1a2ac900-7751-11eb-8460-7ce55aeda398.png)

![image](https://user-images.githubusercontent.com/61459197/109129769-49d9d100-7751-11eb-83ab-322943b65947.png)
![image](https://user-images.githubusercontent.com/61459197/109129796-52caa280-7751-11eb-9418-dd00b7757b23.png)
![image](https://user-images.githubusercontent.com/61459197/109129989-85749b00-7751-11eb-85b6-c46d54ea3c3a.png)

**Comment by magnefjeld** [comment]
da ser denne grei ut. Sett på både ny periode/gjenopptak, samt norsk og engelsk. Oppsummering ser ok ut. Ikke testet å sende inn søknad i test. Da er denne godkjent for produksjonsetting.
t.o @atleno @urenhale @rannveigskjerve

**Comment by atleno** [comment]
Deployet i prod nå
