### ISSUE TITLE
Feriepengekompensasjon til dagpenger - juni 2021

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#687]
Stortinget har vedtatt at det skal etableres en "feriepengekompensasjon" for dagpengemottakere for ferieårene 2020 og 2021. Løsningen er midlertidig og tenkt å gjelde for 2 år, kanskje noe avhengig av videre utvikling av pandemien.

Produktområde arbeidsgiver, i samarbeid med teamene i digitale dagpenger og team Arena skal utvikle en relativt enkel løsning som benyttes i en midlertidig periode.

Følgende forutsetninger er lagt til grunn;

- Det legges avgjørende vekt på å finne en løsning som kan levere utbetaling i begynnelsen av juni 2021. 
- Det bør ikke utvikles omfattende funksjonalitet i legacy-systemer – det blir dobbeltarbeid når det må migreres ut.
- Ordningen tilhører dagpengedomenet. 
- Fagansvaret utøves av team regelverk dagpenger. Ansvaret for den utviklede løsningen bør på sikt kunne overføres team digitale dagpenger

Se arbeidsside på confluence: https://confluence.adeo.no/display/POArbeid/Feriepengekompensasjon+til+dagpenger

På møte 11. februar 2021 er følgende arbeidsdeling landet:

**Det var enighet på møtet om at beste løsning vil være et samarbeid mellom de tre partene der team lønnskompensasjon tar hovedansvaret for utviklingen slik at løsninger gått opp i lønnskompensasjonssaken kan gjenbrukes, der en utvikler fra digitale dagpenger deltar slik at teamet blir fortrolig med løsningen og Team Arena bidrar med uttrekk av data og kompetanse på dagens løsning i Arena.**

**Avklaringspunkt:** Vi må avklare hvilken utvikler som skal jobbe med dette fra team dagpenger, sammen med PO arbeidsgiver og team Arena.

**Comment by magnefjeld** [comment]
Oppstartsmøte torsdag 4. mars 2021. Videresendt innkalling til @urenhale @rannveigskjerve @atleno

**Comment by atleno** [comment]
Foreløpig skisse av løsning:
1. Uttrekk av fnr fra Arena
2. Hente inntekt fra inntektskomponenten - for å finne ut hvor mye dagpenger de har fått
3. Regne ut feriepengekompensasjonen
4. Sende til utbetaling

Møte neste uke for å avklare bekymringer og sånn

**Comment by rannveigskjerve** [comment]
Det er bestemt at arena skal løse feripengekompensasjon intill videre
