### ISSUE TITLE
Oppdatere biblioteker og fikse Snyk/ReviewDog/Nodeetellerannet

### ISSUE THREAD

**Issue by gtcno** [navikt/dagpenger#689]
todo: 
Førstemann legger inn noen oppskrifter på hvordan man kan gjøre dette,
f.eks verktøy som brukes for å finne ut at JVM deps har nye releaser. 

Dette er en recurring oppgave som vi setter av 2 timer per uke til 
å gjøre. 

Presenter på Show and Tell framgan.

**Comment by kmriise** [comment]
Tok for oss dagpenger-journalforing-ferdigstill:
Prøvde oss på å patche avhengigheter i commit, dette fungerte ikke og vi måtte rulle tilbake:

https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/aad52876eb861551152e80cbf7549ed79436f996
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/5a083fba7f2aca9a3262f7a07ee1faf62edffef7
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/6c3e77b465335b2e9a020850498df321b0e240a6
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/8adf8ce7c3b74eb0cdef3a0a71d8c0296e91c3aa
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/23b04bbe36070148836385ff571207a0fdad3165
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/1215453c4420739b454b0894e7b1e55bf24192d5
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/cf848859f1cbc03402e5669e71147a437c20e36e
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/57ef2c39d16ec0484f256bc01518ef8468c8b159

Giao greide til slutt å finne ut av hvilke avhengigheter som greide å leke sammen på nyere versjonering av avhengighetene som måtte patches:
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/1954c168dc31448204b2e17b832484bc69f5bf23
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/64ff8b036534f9a6c9198616abf5ebe510bcc023
https://github.com/navikt/dagpenger-journalforing-ferdigstill/commit/26e72f9573c43d4980b20c23d417e9cd53a403ad

PS: Daniel tok også ansvar på eget insj og ryddet opp i avhengigheter for kalkulatoren i en samlepatch, samt fjernet overflødige individuelle PR fra snyk 🥳
