### ISSUE TITLE
Regelmotor - skille ut vedtaksID mellom arena/kalkulator/forskudd

### ISSUE THREAD

**Issue by gtcno** [navikt/dagpenger#691]
Vi har ingen god måte å skille hvilket system som bruker regelmotoren vår.

Regelmotor - skille ut vedtaksID mellom arena/kalkulator/forskudd for å spore hvilken tjeneste som etterspurte hvilken regelberegning.

Det finnes en del kode som kanskje kan brukes allerede. Hør med @geiralund 

[Lenke til mural visualisering over problemet](https://app.mural.co/t/navdesign3580/m/navdesign3580/1614169783770/f62557a0a8489fce130228558d911e456440037e)

- [x] Kalkulator-frontend må sende regelkontekst til kalkulator-api slik kalkulator-api kan skille mellom veiledning og forskudd, og slik sett kan sende riktig regelkontekst til dp-regel-api
- [x] Sende med regelkontekst fra arena-adapter i behovet
- [x] Rename vedtakId i inntekt_V1_person_mapping til nullable kontekstid -> legge til enum-felt for kontekst. Migrere slik at gammelt ræl får riktig regelkontekst
- [x] Håndtere at vedtakId ikke alltids sendes på pakken i dp-inntekt-klassifiserer
- [x] Sørge for at resten av mikrotjenestene klarer seg med nullable vedtakid
- [x] Legge til kontekst-id på pakken
- [x] gjøre en analyse av inntekt-ui (saksbehandlerløsning)
- [x] dp-oppslag-inntekt: sende med regelkontekst mot dp-inntekt
- [x] Fikse todos: kalkulator-api
- [x] Fikse todos: kalkulator-frontend
- [x] Fikse todos: regel-api
- [x] Fikse todos: dp-inntekt
- [x] Fikse todos: dp-inntekt-klassifiserer
- [x] Vi takler ikke at vedtakId er String.
- [x] Arena forventer at vedtakId er en INT
- [x] Refaktorere dagpenger-journalforing-ferdigstill til å sende regelkontekst, og legge til en ny konteksttype i enum?
- [x] Endre dp-regel-arena-adapter og dp-inntekt-api sin inntjeningsperiode route til å ikke bruke vedtakId (dp-regel-arena-adapter må over på inntekt sin nye route)

**Comment by kmriise** [comment]
VedtakID gjennomsyrer regelmotoren

Kontekst er begynt på, bør kunne være mulig å åpne for å sende med kontekst som optional parameter i dp-regel-api, hvor kalkulator setter enten kontekst veiledning eller soknad, basert på om det er kalkulator eller forskudd som sender inn.

Problemet er at vi fortsatt "må"? mappe en id til konteksten, som igjen sendes videre i regelmotoren?

dp-regel-inntekt har en del ruter som er tett knyttet opp mot vedtakid, hovedsakelig for redigering av inntekt fra dp-regel-ui (saksbehandler som redigerer inntekt for vedtak i arena)

**Comment by kmriise** [comment]
dagpenger-journforing-ferdigstill jukser også ved å sende -12345 vedtakId inn når den sjekker om søknad skal merkes som potensielt avslag minsteinntekt 😱

**Comment by kmriise** [comment]
dp-inntekt: Finne ut av hvordan vi ønsker endepunktet utvidet med regelkontekst. hvordan skal flyten være.

**Comment by kmriise** [comment]
Done! For now... 😱
