### ISSUE TITLE
Oversikt over hvem vi deler personopplysninger med - Gjør noen av applikasjonene våre det?

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#698]
Vi holder på å redegjøre (som mange andre), hvem vi deler personopplysninger med. 

Vi må undersøke om vi har løsninger hvor vi deler informasjon direkte med eksterne utenfor NAV (eks arbeidsgivere). 

**Våre applikasjoner/løsninger, som vi i digidag forvalter, deler de personopplysninger direkte med 3. part?**

**Comment by magnefjeld** [comment]
Hypotesen er at svaret er NEI, men vi må sjekke det ut.

**Comment by atleno** [comment]
Det er ingen eksterne som spørr oss om ting.
Vi spør ingen eksterne direkte med personopplysninger.
Disse går gjennom nav-komponenter før de eksterne blir spurt. For eksempel sender vi fødelsnummer til skatt, med dette går gjennom nav sin inntektskomponent.

**Comment by atleno** [comment]
@magnefjeld
