### ISSUE TITLE
Registreringsløsningen var nede 2.3.21 fra kl. 23:00 til 06:00 og 3.3.21 fra 23.00 til 23:59 -  Kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#705]
![image](https://user-images.githubusercontent.com/61459197/109771516-2dc8aa80-7bfd-11eb-8167-e21592bfc49c.png)

![image](https://user-images.githubusercontent.com/61459197/109925139-a7c26780-7cc1-11eb-94f1-4427448e462a.png)

Listen legges i et eget excel-ark på https://teams.microsoft.com/l/file/2DA8EC00-B4C6-496D-B9A2-9A6E68F33C16?tenantId=62366534-1ec3-4962-8869-9b5535279d0b&fileType=xlsx&objectUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FKorona-dagpenger-uttrekk%2FShared%20Documents%2FDiverse%2FS%C3%B8knader%20-%20Registreringsl%C3%B8sning%20nede%2FReg%20l%C3%B8sning%20nede%201.%20mars%202021.xlsx&baseUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FKorona-dagpenger-uttrekk&serviceName=teams&threadId=19:80ac0d040afd445faa0f8dce1bf9b389@thread.skype&groupId=3da29b59-dff5-4a3b-8ad4-661df303532d 

Så får vi en av saksbehandlerne/testerne til å sjekke om noen av dem har fått avslag pga ikke registrert/påminne dem om å registrere seg

Ref. tidligere uttrekk: https://github.com/navikt/dagpenger/issues/686

**Comment by magnefjeld** [comment]
leveransen 1.3.21 ble utsatt

**Comment by atleno** [comment]
@magnefjeld oppdatert excelark

**Comment by magnefjeld** [comment]
lista sjekket. ivaretatt. lukker historien.
