### ISSUE TITLE
Avklaringsmøte angående reberegning av satser når barn fyller 18 år - med team Arena

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#706]
**Fra: Mona Kjeldsrud
Dato: tirsdag 2. mars 2021 08:45-09:00** 

Hei, kaller inn til et kjapt avklaringsmøte angående reberegning av satser når barn fyller 18 år.

Kalte inn Geir Andé, siden jeg husker han jobbet med reberegningsendepunktet, men videresend gjerne til noen andre, dersom det er behov for det. Men noen fra DigiDag bør være med å avklare dette.

I forbindelse med ARENA-5370, ser jeg på endringsbehovene i denne batchen. Kom over kode som jeg selv har laget i forbindelse med en feilretting av https://jira.adeo.no/browse/ARENA-3707. Der har vi gått over til å benytte endepunktet for reberegning av grunnlag og satser i stedet for å sende grunnlag som input til det ordinære beregningsendepunktet.

Det jeg stusser litt på er følgnede "kode" (oversatt til norsk) som jeg har lagt til:

-- Kommentar: Lagrer oppdatert informasjon om beregningsregel og beregningsid dersom grunnlag er reberegnet
HVIS grunnlag-subsumsjonsid som vi fikk i responsen fra reberegningen har en verdi SÅ
  oppdater Arenas vedtaksfakta for grunnlag-subsumsjonsid
  oppdater Arenas vedtaksfakta for beregningsregel benyttet for grunnlagsberegning
SLUTT HVIS

Det jeg ønsker å avklare er om vi virkelig skal oppdatere dette når det egentlig bare er satser som skal reberegnes. På den annen side - hvis vi ikke oppdaterer, vil Arena og DigiDag ikke ha samme informasjon. Det kan problematisere feilsøking dersom feil skulle meldes.

PS: Dersom vi skal oppdatere dette i Arena, bør vi også oppdatere beskrivelsen av beregningsregelkoden. Det er litt "tåpelig" at beskrivelsen lagres per vedtak (den burde man ved visning i skjermbilde heller slå opp i en kodeverkstabell, på bakgrunn av beregningsregelkoden), men vedtaksfakta BERBESKR ble nok innført for veeeeldig mange år siden og ingen har vurdert å fjerne det.

**Comment by atleno** [comment]
Ikke helt ferdig avklart, vi og mona må snakke om det underveis.
Men ligger an til at arena oppdaterer alt, for at det i arena skal henge mer sammen med infoen vi i dagpenger har
