### ISSUE TITLE
Dagpenger og utdanning - reform til 1.7.21 -Videre prosess

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#708]
Det er planlagt en større "reform" knyttet til dagpenger og utdanning fra 1.7.21. Vi har startet på arbeidssider på https://confluence.adeo.no/display/TDP/Utdanning+og+dagpenger+-+reform. Se mer informasjon der.

Det er fortsatt mange uavklarte problemstillinger, men deler av dette treffer digidag (redusert dagpengesats). I tillegg vil det måtte gjøres tilpasninger i den digitale søknadsdialogen.

Andre veivalg som gjøres underveis i arbeidet, kan også treffe digidag. Behov for at en eller flere utviklere er med på den videre prosessen.

**Comment by magnefjeld** [comment]
Arbeidsgruppen har et uformelt og enkelt oppstartmøte 4.3.21. Her er det ikke behov for at for mange er med, men det vil bli landet flere møtedatoer framover etter dette. Kommer tilbake til det.

**Comment by atleno** [comment]
Nytt regelverk trer ikke i kraft 1.7 - kanskje 1.10 (eller enda senere)

Alt er fortsatt veldig uklart
Helst burde vi redusere satsen utifra hvor mye de får i lån. Denne kan endre seg ofte, og vil være tidkrevende å løse.

Enkleste løsning som kom opp: 
satsen reduseres med en viss prosent

**Comment by magnefjeld** [comment]
Geir Andre blir med på møtet 15.3.21 kl. 13-14 om utdanning.

**Comment by magnefjeld** [comment]
analyse utføres på https://jira.adeo.no/browse/ARENA-5580 : team arena +dd sammen. Geir Andre med fra DD

**Comment by atleno** [comment]
Møte 24. mars:
1.10 er litt vanskelig for oss, har spurt om 1.1.2022 eller senere. Lånekassen har meldt inn samme problem

Ting vi lurer på:
Når den trer i kraft
Hva inngår i vilkårsvurderingen?
Hva er det minste vi kan levere
Hvor mange brukere vil løsningen ha - hvor tidkrevende er det med mye manuell saksbehandling

**Comment by rannveigskjerve** [comment]
Notat fra utvikler diskusjon 25.03 om mulighet for behandling av søknad gjennom dp-quiz
Utdanning og dagpenger spørsmål;

**Antagelser og spørsmål:** 
To løyper;
1. Søker om dagpenger og utdanning samtdig
2. Søker om utdanning løpet av dagpengeperiodene

I tilfelle 1;
- Skal bruker kunne få avslag på utdanning men innvilges dagpenger likevel, eller må bruker sende inn ny søknad uten utdanning?
I tilfelle to;
- Skal dette føre til et nytt vedtak? (Hva gjør saksbehandler? )
- Skal bruker kunne fortsette på dagpenger om hen får avslag på utdaningsøknad (hvordan blir utbetaling avbrutt), eller søke om gjennopptak?

![utdanning](https://user-images.githubusercontent.com/55136985/112610787-5d925900-8e1d-11eb-8bb0-a6b5a0d3e477.png)

**Comment by Elinvethe** [comment]
Avklart at innhold løser denne
