### ISSUE TITLE
Endre tekst i veiledning i søknadsdialogen om forlenget ventetid

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#714]
https://jira.adeo.no/browse/FAGSYSTEM-158427 

Ser ut som en av veiledningstekstene må oppdateres, både i ny/gjenopptak og norsk/engelsk

Endres fra **tolv/twelve** til **18** 

![image](https://user-images.githubusercontent.com/61459197/110638538-fafb5500-81ae-11eb-8c83-41dd7cc9c6bc.png)
![image](https://user-images.githubusercontent.com/61459197/110638751-3a29a600-81af-11eb-94e0-0a71b925f718.png)

**Comment by atleno** [comment]
Ute i prod nå. 
Også endret tolv til 18 i spørmålet under Arbeidstiden er redusert -> Har du fått tilbud om å fortsette hos din arbeidsgiver?
Slik så det ut før:
![Screen Shot 2021-03-12 at 13 21 01](https://user-images.githubusercontent.com/660550/110941564-daf79d00-8338-11eb-9f48-fab3b7f23a2c.png)

**Comment by magnefjeld** [comment]
så bra:)
