### ISSUE TITLE
Registreringsløsningen var nede 11.3.21 fra kl. 23:00 til 23:59, og fredag 12.3.21 fra 23:00 til kl. 04:00 - Kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#717]
11.3.21
![image](https://user-images.githubusercontent.com/61459197/110823274-3d499280-8292-11eb-9664-e02c9a5244d8.png)

12.3.21
![image](https://user-images.githubusercontent.com/61459197/110950628-5e6abb80-8344-11eb-8ddb-c98fea27b013.png)

Har lagget to flipper på excelarket.

Listen legges i et eget excel-ark på https://teams.microsoft.com/l/file/4E543971-35AE-4F58-8B1E-244FA4CE06B4?tenantId=62366534-1ec3-4962-8869-9b5535279d0b&fileType=xlsx&objectUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FKorona-dagpenger-uttrekk%2FShared%20Documents%2FDiverse%2FS%C3%B8knader%20-%20Registreringsl%C3%B8sning%20nede%2FReg%20l%C3%B8sning%20nede%2011.%20mars%202021.xlsx&baseUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FKorona-dagpenger-uttrekk&serviceName=teams&threadId=19:80ac0d040afd445faa0f8dce1bf9b389@thread.skype&groupId=3da29b59-dff5-4a3b-8ad4-661df303532d 

Så får vi en av saksbehandlerne/testerne til å sjekke om noen av dem har fått avslag pga ikke registrert/påminne dem om å registrere seg

Ref. tidligere uttrekk: #686

**Comment by rannveigskjerve** [comment]
har lagt inn i exel arket @magnefjeld

**Comment by magnefjeld** [comment]
takk. bedt eivind sjekke sakene
