### ISSUE TITLE
Søknadsdialogen - EØS-spørsmål - sammenlegging av perioder

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#726]
Endringsønske fra NAY sendt inn iht rutine via Porten: https://jira.adeo.no/browse/FAGSYSTEM-156246

"Siden 22. januar 2021 er søknadsdialogen endret slik at medlemmer kan svare på spørsmål om de har hatt arbeidsperioder fra andre EØS-land. NAV Arbeid og ytelser Innlandet er positiv til denne utvikling som gjør at søknaden fra medlemmer som har arbeids-og likestilte perioder fra andre EØS-land rutes direkte til riktig enhet, 4470.

Samtidig ser vi behov for at disse arbeidsforholdene og øvrige forsikringsperioder dokumenteres av medlemmene.

Det er to grunner til at vi trenger dokumentasjon fra arbeids- og trygdeperioder fra andre EØS-land:
1) I tilfeller vi sender forespørsel om arbeids- og trygdeperioder til myndigheter i andre EØS-land, må vi ofte legge ved dokumentasjon på disse arbeidsperioder.
2) Videre er det ikke alltid nødvendig til å sende forespørsel til andre myndigheter dersom arbeidsperioder er dokumentert av medlemmer. Etter rundskriv Hovednummer 45- kapittel 4, art. 4.3.4 må arbeidsperioder i andre EØS-land være tilstrekkelig dokumentert før disse kan overføres og medregnes for å oppfylle vilkårene for rett til dagpenger. I Norge er det ikke et eget krav til spesifikk forsikring mot arbeidsløshet slik en del andre EØS-land har. Dette betyr i praksis at alle arbeidsperioder hvor vedkommende kan dokumentere at vedkommende har vært i arbeid i andre EØS-land skal medregnes for å oppfylle kravet til minsteinntekt og periodene skal også inngå i dagpengegrunnlaget Det betyr at NAV ikke alltid trenger en bekreftelse fra myndigheter i andre EØS-land om vedkommende var forsikret som arbeidstaker men kan disse perioder bekreftes med for eksempel arbeidsavtale, lønnsslipper og likningsopplysninger som dokumenterer omfanget av arbeidet og at det har vært betalt skatt av arbeidet i det andre EØS-landet.

Om dagpengesøkere allerede bes i søknadsdialogen om å dokumentere arbeidsperioder fra andre EØS-land, kan vi unngå å sende et mangelbrev og blir saksbehandlingstid kortere.

Vi ber om at søknadsdialogen oppdateres slik at brukere må dokumentere arbeidsforholdene fra andre EØS-land, akkurat som de gjør for de norske arbeidsforholdene med arbeidsavtaler og dokumentasjon på arbeidsforhold. Vi trenger opplysninger om start- og sluttdato, stillingsprosent eller arbeidede timer for arbeidsforholdene."

- [x] Løse ut fagsystemsak med midlertidig informasjon at vi vil se mer på behovet

**Comment by magnefjeld** [comment]
ref https://github.com/navikt/dagpenger/issues/614 hvor vi implementerte endringen

**Comment by magnefjeld** [comment]
@Eivind833 du kan jo ta en titt på denne også?

**Comment by EivindRoyrvik** [comment]
@magnefjeld @Elinvethe  Hei :) Her er et forslag for denne, tar gjerne imot innspill. Kan vi deploye en slik endring selv? Tenker det er liten risiko for å gjøre noe galt med en slik løsning og dette er ønsket av NAY/4470.

1.	Legg til funksjon for å laste opp vedlegg når bruker svarer ja på å ha jobbet i et annet EØS-land eller Sveits med teksten «Dokumentasjon av arbeidsforhold innenfor EØS-området og Sveits» 

2.	Legg til veiledningstekst:

"Perioder du har arbeidet eller vært forsikret i land innenfor EØS-området eller Sveits de siste 36 månedene, kan påvirke din rett til dagpenger. De kan også påvirke hvor mye du kan få i dagpenger. For å inkludere arbeidsforhold fra andre EØS-land enn Norge i vurderingen, trenger vi opplysninger om arbeidsforholdene dine.  

Hvis du har fått attest PD U1 fra landet du jobbet i, må du legge denne med søknaden. Har du ikke attest PD U1, må du dokumentere arbeidsforholdene dine de siste 36 månedene. 

Dokumentasjonen må vise start- og sluttdato for arbeidsforholdet og årsaken til at arbeidsforholdet er opphørt. Du må dokumentere stillingsprosenten din eller arbeidede timer og inntekt per måned. Du kan dokumentere dette med arbeidsavtaler, oppsigelse, lønnsslipper og eventuell sluttattest fra arbeidsgiver."
