### ISSUE TITLE
Søknadsdialogen - Rotasjon - Veiledning

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#727]
Endringsønske fra NAY sendt inn via Porten iht rutine: https://jira.adeo.no/browse/FAGSYSTEM-160510 

Fikk beskjed om å registrere ønske om endring i søknadsdialogen i Porten under Fagsystem. Så her kommer det en forespørsel.

Vi opplever at det sjelden kommer inn tilstrekkelig dokumentasjon fra arbeidssøkere som jobber rotasjon. De sender med lønns-slipper eller timelister, men det er ikke tilstrekkelig for å avklare når siste arbeid- og avspaseringsperiode løp. Det medfører at vi må sende unødvendig mange mangelbrev.

Er det mulig å "spisse" dette enda mer i informasjonsteksten i søknadsdialogen? (se skjermbilde under vedlegg)

Her er forslag til infomelding:

I dag står det følgende:
«Du må dokumentere den siste rotasjonen du hadde med timeliste eller lignende»

Men, ønsker en presisering som lyder som følger:
"Du må dokumentere rotasjonsordningen din, og legge ved en bekreftelse på siste periode med arbeid og avspasering du hadde."

Med vennlig hilsen
Lene Eggen Mo
Nettverksdriver // Fagnettverk Dagpenger
NAV Arbeid og ytelser Styringsenhet
413 05 322

![image](https://user-images.githubusercontent.com/61459197/112313328-04ed7f80-8ca8-11eb-92df-514c66417126.png)

- [x] Løse ut fagsystemsak med midlertidig informasjon at vi vil se mer på behovet

**Comment by EivindRoyrvik** [comment]
Jeg tenker dette er et godt endringsforslag. Liten forbedring som kan gjøre det enklere for bruker å forstå hva de må dokumentere hvis de har jobbet rotasjon rett forut for permittering eller arbeidsledighet. Men, krever det også endring av navn på vedlegget de skal sende inn? Tror de i dag bare får beskjed om å sende timeliste under vedlegg. 

Forslag til ny tekst i informasjonsboksen: 

«Du må dokumentere hvilken rotasjonsordning du hadde. Du må dokumentere den siste arbeidsperioden og den siste friperioden din.»

«You have to document your rotation work. You must document your last working period and your last free period.»

**Comment by EivindRoyrvik** [comment]
Utarbeides ifm. MVP ny søknad.
