### ISSUE TITLE
Ny inntektsbeskrivelse inn i inntektsfilteret - skal den med etter kapittel 4 ?

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#743]
### **Ny midlertidig ytelse - behov for ny inntektsbeskrivelse?**
16.mars 2021 - fra Maria S i Seksjon fra informasjonsforvaltning.

Jeg har akkurat fått beskjed om at Skatteetaten selv har behov for en ny inntektsbeskrivelse for denne ytelsen. Skatteetaten ser derfor nærmere på denne saken, og vil derfor informere oss når de vet mer om hvordan dette blir.

Det vil derfor komme en ny inntektsbeskrivelse på dette, også får vi se nærmere på dette når vi vet mer.

Se https://confluence.adeo.no/pages/viewpage.action?pageId=409963069 for mer informasjon og hvor oppdateringer må gjøre av avklaringer.

**Comment by Elinvethe** [comment]
Det blir ikke en egen kode i a-melding på denne ytelsen, og denne lukkes
