### ISSUE TITLE
Søknadsdialogen - generering av vedlegg "Bekreftelse på arbeidsforhold og permittering" - Gjenopptak

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#748]
Fra Øystein i NKS:
![image](https://user-images.githubusercontent.com/61459197/112805118-7d23be80-9075-11eb-8a84-a958c47c1123.png)

---

Vi har inntil videre et redusert dokumentasjonskrav på dagpenger, som gjør at brukerne som hovedregel ikke skal dokumentere vha skjemaet "Bekreftelse på arbeidsforhold og permittering". 

Vedlegges generes av at man svarer JA på delspørsmålet "Jeg har arbeidet sammenhengende i mer enn seks uker":  
![image](https://user-images.githubusercontent.com/61459197/112807760-8d896880-9078-11eb-8bb9-6d12d824938d.png)

Dette under:
![image](https://user-images.githubusercontent.com/61459197/112808049-e0fbb680-9078-11eb-9ad5-d2077cb1e09c.png)

Må gjøres likt slik det er nå man krysser av for: "Ja, jeg var permittert fra en fiskeforedlings- eller fiskeoljebedrift" (slik at inget vedlegg genereres) 
![image](https://user-images.githubusercontent.com/61459197/112807279-ffad7d80-9077-11eb-9480-b9387e027230.png)

- [ ] Teste funksjonelt
- [ ] .

**Comment by magnefjeld** [comment]
hvordan det ser ut i oppsummeringen: 
![image](https://user-images.githubusercontent.com/61459197/112808600-7139fb80-9079-11eb-807f-f6d9d08d8e9b.png)

**Comment by magnefjeld** [comment]
Samtidig med at man ikke genererer dette vedlegget "bekreftelse på arbeidsforhold og permittering", så er det ønskelig at vi genererer vedlegget: "Varsel om permittering", når bruker svarer "Ja" på alle 4 spørsmålene under: 
![image](https://user-images.githubusercontent.com/61459197/112817878-36d55c00-9083-11eb-9f20-cef5f4e905c0.png)
![image](https://user-images.githubusercontent.com/61459197/112817979-52406700-9083-11eb-9820-cd2753c7aa8d.png)

Det er ikke interessant å etterspørre "varsel om permittering" , når bruker ikke lenger er ansatt i bedriften. Derfor vil det vel være naturlig at det derfor er om bruker svarer "JA" på 
![image](https://user-images.githubusercontent.com/61459197/112818265-a0556a80-9083-11eb-94b7-0415ad83ff57.png)
som genererer vedlegget.

**Comment by urenhale** [comment]
hva som skal gjøres:

- [x] Fjerne krav om vedlegg arbeidsforhold og permittering.
Skal fungere på samme måte som permittert fra en fiskeforedlings- eller fiskeoljebedrift.
- [ ] Migrere mellomlagrede søknader

**Comment by magnefjeld** [comment]
Hei. Da har jeg testet i Q1, og ser at vedlegget nå er fjernet (bekreftelse på arbeidsforhold og permittering) (både på norsk og engelsk)

Men det er ikke lagt til "Varsel om permittering" ? 
![image](https://user-images.githubusercontent.com/61459197/113865874-e9589d80-97ac-11eb-9ad3-641db1499114.png)


Si ifra igjen når det klar til testing igjen.

**Comment by magnefjeld** [comment]
sett litt videre på det, siden det faglig sett er litt vrient å få dette riktig, gitt eksisterende funksjonalitet, så får vi inntil videre bare fjerne vedlegget "bekreftelse på arbeidsforhold og permittering" og la være å generere noe vedlegg.

Det er testet ok, så er da bare å produksjonsette ved leilighet.
t.o @atleno
