### ISSUE TITLE
Manglende oppretting av journalføringsoppgaver

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#753]
Ref.:  https://jira.adeo.no/browse/FAGSYSTEM-162048

- Opprettes ikke journalføringsoppgaver (sannsynligvis noen 100 ish)
- Har blitt opprettet dobbelt med automatiske journalført oppgaver i Arena (sannsynligvis mindre omfang).

Skal være et sikkerhetsnett, team dokument (?), som skal fange opp der det har gått mer enn x dager, og det ikke er opprettet noen journalføringsoppgave. Imidlertid ser ikke denne ut til å fungere.

- [x] Fungerer sikkerhetsnettet og hvordan fungerer det faktisk ?
- [x] Manuell oppfølgingsliste til NAY eller automatisk ryddejobb for å oppdatere oppgaver.

Om vi må lage liste, så kan det legges inn her https://teams.microsoft.com/l/file/A7E67697-39AE-4B97-9486-8F2512276D5E?tenantId=62366534-1ec3-4962-8869-9b5535279d0b&fileType=xlsx&objectUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FKorona-dagpenger-uttrekk%2FShared%20Documents%2FDiverse%2FFeil%20-%20innl%C3%B8pet%20-%20ikke%20opprettet%20journalf%C3%B8ringsoppgaver%20i%20mars%202021.xlsx&baseUrl=https%3A%2F%2Fnavno.sharepoint.com%2Fsites%2FKorona-dagpenger-uttrekk&serviceName=teams&threadId=19:80ac0d040afd445faa0f8dce1bf9b389@thread.skype&groupId=3da29b59-dff5-4a3b-8ad4-661df303532d

**Comment by magnefjeld** [comment]
https://nav-it.slack.com/archives/C6W9E5GPJ/p1617960465159300

**Comment by magnefjeld** [comment]
kommer da inn som en journalføringsoppgave, men uten å være knyttet til person.
![image](https://user-images.githubusercontent.com/61459197/114168920-38c7d680-9931-11eb-9f58-6af794cbd123.png)

**Comment by magnefjeld** [comment]
@atleno da løser jeg ut fagsystemsaken og tilbakemelder til innmelder, om det er greit?

**Comment by atleno** [comment]
Løst av sikkerhetsnettet til team dokument, se beskrivelse her: https://github.com/navikt/doksikkerhetsnett

**Comment by magnefjeld** [comment]
ca 160 oppgaver på gosys 4450, som er ufordelte, journalføringsoppgaver (oppgavetype/oppgavegruppe) og uten f.nr.

**Comment by magnefjeld** [comment]
se jirasaken. løst den ut . også snakket med innmelder og dalflyen.
