### ISSUE TITLE
Måle treffsikkerhet av automatisk avslag

### ISSUE THREAD

**Issue by atleno** [navikt/dagpenger#766]
Hva vil vi måle:
Måle hvor godt vi treffer på sisteDagMedLønn og sluttårsak.
Her kan vi bomme litt, saksbehandler luker de bort i quiz-retting, men påvirker mengden saker vi behandler.

Måle hvor godt vi treffer, når sisteDagMedLønn og sluttårsak er satt riktig.
Her burde vi aldri bomme, vil gi feil svar til bruker.

**Få resultater ut av quiz:**
- [x] Fikse deploy-prod for aiven i spill-av
- [x] Teste at ting blir stoppa riktig i arena-sink
- [x] Fjerne manuell godkjenning i regeltreet
- [x] Fix: harInntektNesteKalendermåned og grunnbelop trigger ekstra seksjoner
- [x] Fiks at dp-doh spammer alert-kanalen

**Fikse propp:**
- [x] Klarer ikke håndtere Arbeidsforhold:  "Ingen av alternativene passer for meg"

**Sammenlikne:**
- [x] Sette opp dings for å sammenligne quiz-resultat og arena-resultat
- [x] Ta imot quiz-resultat
- [x] Ta imot arena-resultat
- [x] Ta imot fagsakid til søknadsid-kobling fra innløpet
- [x] Lagre ting
- [x] Personvern rundt lagring?

**Big data:**
- [x] Søknadsdata inn til quiz igjen
- [x] Få alt til å funke i dev
- [x] Få all data for én søknad i prod
- [x] Behandle alle innkommende søknader i quiz kontinuerlig. Store batcher er vanskelig, fordi quiz bruker dagens dato for å sjekke arbeidssøkerting.

**Se på resultatene**
- [x] Måle ventetid arena-saksbehandling

**Comment by atleno** [comment]
For å sammenlikne:
Hver søknad inn oppretter en arenasak.
Hvis flere søknader blir sendt inn, så er det bare en av sakene som får et vedtak.

Vedtak -> sak -> journalpost/søknad -> quiz-resultat.

Arena gir oss både vedtakId og sakId.
https://confluence.adeo.no/display/ARENA/Arena+-+Tjeneste+Kafka+-+Dagpengevedtak

Innløpet har sak til journalpost/søknad-kobling.
Event innsending_ferdigstilt har journalpostId, fagsakid og søknadsdata.
søknadsdata har brukerBehandlingId aka søknadsId.

Quiz-resultatet har faktumet `Innsendt søknadsId`

**Comment by atleno** [comment]
Mulig første test i dev:
Finn søknad i dp-soknad, som er ubehandlet i arena.

Manuelt legg inn søknad til arenasak-kobling i db.
Saksbehandle i quiz med dp-spill av.
Gjør vedtak i arena.

**Comment by Elinvethe** [comment]
jeg forstod fra stand-up at det begynner å nærme seg at man får på plass en tjeneste som sammenligner resultatet fra dp quiz med Arena. @Eivind833, @magnefjeld  og meg kan gjennomgå saker der vi ser at vi ikke treffer slik at vi får gitt feedback på kvalitet og justert.  Det kan jo være litt delay pga vi må avvente saksbehandlingen og har dere snakket noe om det? Har dere sett noe på hvordan vi skal sammenligne og hvordan vi skal gå igjennom de sakene der det ikke er match? Hvis ikke kunne hvertfall vi sett på det til uka? @atleno

**Comment by Elinvethe** [comment]
Jeg har også oppdatert denne siden ut fra ny versjon 2 https://confluence.adeo.no/display/TDP/INI+1.1+Delautomatiske+avslag+om+minsteinntekt

**Comment by atleno** [comment]
```sql
select quiz.innsendtsøknadsid, quiz.søknad_uuid as søknadsUuid, arena.fagsakid, quiz.resultat as quizresultat, arena.resultat as arenaresultat, arena.created
from quiz_arena_mapping as mapping
join quiz_resultat as quiz on quiz.innsendtsøknadsid = mapping.innsendtsøknadsid
join arena_resultat arena on mapping.fagsakid = arena.fagsakid;
```
