### ISSUE TITLE
Redirect til login-service etter vi har logget inn i ID-porten. For at det skal henge sammen med dekoratøren

### ISSUE THREAD

**Issue by tonjemjovik** [navikt/dagpenger#771]

**Comment by androa** [comment]
For å få det til å fungere med loginservice så må vi flytte fra `intern.dev.nav.no` til bare `dev.nav.no`.

Laget en PR for å få det fikset i loginservice: https://github.com/navikt/loginservice/pull/454

**Comment by androa** [comment]
Jeg får ikke endelig testet dette før vi har den ekte URLen den skal dukke opp på internettet. Teorien er at det fungerer, men får ikke testet enda.

**Comment by androa** [comment]
Da er dette i orden ass. I prod iallefall. Hangler litt i preprod/dev, men det ordner seg underveis :)
