### ISSUE TITLE
Refresh token i frontend. Tokenet vi får fra ID-porten er gyldig i Xmin, så må bruke refresh token

### ISSUE THREAD

**Issue by tonjemjovik** [navikt/dagpenger#772]

**Comment by androa** [comment]
Gravde litt i nøyaktig hva som skjer her, og viser seg at det mangler en liten hemmelig detalj i dokumentasjonen til NAIS/security blueprints.

https://github.com/navikt/dp-dagpenger/commit/094c68170bf9e4645166a8b3e6e739e18d2a59ea

Vi brukte `id_token` mot TokenX som har veldig kort levetid, fordi den har gyldig `aud` (audience) satt. Men så var det en hemmelig regel at om vi gjør https://github.com/navikt/dp-dagpenger/commit/c16bdb8e6db2eb8c490a3899eb4e363986cf240c#diff-ade029f3804a359be3e48f0ebc68be2963dab500b667c55dc6d31dd71df8a12aR27 så vil også `access_token` inneholde `aud`.

`access_token` er også gyldig i en hel time. Det gjør vel kanskje dette problemet litt mindre prekært.

**Comment by androa** [comment]
Dette er vel egentlig løst. Nå som vi bruker riktig token så er levetiden en time, og det ønsker vi å ha. Det brukes ofte offentlige PCer på NAV-kontor og biblioteker, så vi ønsker at folk autentiserer seg på nytt så ofte som mulig, en time er passe.
