### ISSUE TITLE
Frontend: Som bruker med flere søknader ønsker jeg å kunne velge hvilken søknad jeg ser status for

### ISSUE THREAD

**Issue by tonjemjovik** [navikt/dagpenger#776]

**Comment by tonjemjovik** [comment]
Vi må kunne vise at det er sendt inn flere søknader for de som har det, og at man kan velge hvilken søknad man vil vise

**Comment by ghost** [comment]
Design: https://www.figma.com/file/MeVgCo9zTr7DGENG0v69sp/Innsyn-i-sak?node-id=205%3A511

### Definition of done:
* Implementere valg-karusell for valg av søknad (design ikke avgjort pt.)
* Vise valgt søknad på statussiden
* Vurdere å legge søknadsid i URL.
