### ISSUE TITLE
Søknadsdialogen - midlertidig tilpasning pga endret avbruddsperiode

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#777]
LO og NHO har midlertidig avtalt at avbruddsperioden i en begrenset periode skal økes fra "mer enn 6 uker" til "mer enn 10 uker". Dette medfører blant annet at vi midlertidig må gjøre tilpasninger i den digitale søknadsdialogen fra og med 8. mai 2021. 

Fra lovdata: https://lovdata.no/pro/#document/LTI/forskrift/2021-04-27-1337 :
![image](https://user-images.githubusercontent.com/61459197/117012371-2c942680-acef-11eb-928b-648249d71a6d.png)

Det må gjøres endringer i søknadsdialogen på bokmål og engelsk, samt at endringene må testes. Berører kun søknad om gjenopptak.

**Står i dag på bokmål:**
![image](https://user-images.githubusercontent.com/61459197/117012622-711fc200-acef-11eb-9cfc-9e4aafe1067d.png)

**Skal endres til på bokmål:**
Hvor mye har du arbeidet siden forrige gang?

Jeg har arbeidet sammenhengende i 10 uker eller mindre

Jeg har arbeidet sammenhengende i mer enn 10 uker

**Står idag på engelsk:**
![image](https://user-images.githubusercontent.com/61459197/117013117-dc699400-acef-11eb-97d4-db7f34c10ac7.png)

**Skal endres til på engelsk:**
How much have you been working since last time?

I have worked continuously for 10 weeks or less

I have worked continuously for more than 10 weeks

**Comment by magnefjeld** [comment]
si ifra når klar til test i Q.

**Comment by magnefjeld** [comment]
@Eivind833 tester du denne i løpet av uka?

**Comment by EivindRoyrvik** [comment]
@magnefjeld Begynner å teste denne nå.

**Comment by EivindRoyrvik** [comment]
@atleno Hei, jeg er litt i gang med test. Er det en liten feil her på oppsummeringssiden i engelsk versjon?

![Skjermbilde 2021-05-05 142258](https://user-images.githubusercontent.com/82581338/117145076-033cce80-adb3-11eb-8b27-dfdf65e47b69.png)

**Comment by atleno** [comment]
@Eivind833 
Ikke relatert til denne endringen, men ja. Sjekka i prod, og er der også. 
Tror det har vært sånn i noen år, så bra sett!
Endret det til "No, I am no longer employed by them", vi burde uansett være konsekvent på bruken av I'm og I am.

Samme feilen finnes nok flere steder i oppsummeringen hvor apostrof brukes, men får ta det litt etterhvert

**Comment by magnefjeld** [comment]
@Eivind833 er denne testet ok ?

**Comment by EivindRoyrvik** [comment]
@magnefjeld @atleno Denne er ok

**Comment by magnefjeld** [comment]
@atleno da kan jo denne produksjonssettes på lørdag.

**Comment by atleno** [comment]
Så ikke meldingen før nå, jeg bare deployet den til prod jeg @magnefjeld

**Comment by magnefjeld** [comment]
ok. ikke helt optimalt, men skal gå fint akkurat for denne endringen, da mange brukere allerede tror, etter medieoppslagene, at avbruddsperioden er på 10 uker :)
