### ISSUE TITLE
UU gjennomgang av innsynsløsningen

### ISSUE THREAD

**Issue by ghost** [navikt/dagpenger#788]
Hvem skal gjennomføre?
* 1 utvikler + 1 designer

Krav: Wcag 2.1

Definition of done:
* Gjennomgang av wcag 2.1 krav.
* Lage oppfølgingssak for brudd på wcag.

**Comment by ingridhaland** [comment]
Satt opp møte med David Hole for å UU-teste (med skjermleser) tirsdag 25. mai kl 14.
