### ISSUE TITLE
Hvordan fungerer den nye løsningen?

### ISSUE THREAD

**Issue by ghost** [navikt/dagpenger#791]
Finne egnet metode/format for datainnsamling
* Hotjar?
* ++

Lag oppfølgingsaker ved behov.

**Comment by ingridhaland** [comment]
- Vi burde sette opp samme hotjar-undersøkelse som vi hadde sist (Fant du det du lette etter - hva lette du etter osv), så vi kan sammenligne før og etter ny innsynsside. 
- Vi kan også følge med på den andre generelle hotjar-undersøkelsen, spesielt spørsmålet "Jeg er redd for at jeg ikke har gitt NAV alle opplysningene de trenger for å behandle søknaden min".
- Vi kan følge med på antall mangelbrev (og avslag pga manglende dok?) som blir sendt ut (hente ut tall før og etter endring), for å se om siden bidrar til at flere sender inn innen fristen?
- NKS logging før og etter
- Brukertest i prod/test?
- Legge inn en "Har du innspill til denne nye siden"-boks nederst på siden? Lenke til hotjar-survey?

**Comment by ingridhaland** [comment]
Notater fra møte om målinger:
- **hotjar: sette opp samme undersøkelse**, vurdere å flytte opp "hvordan kan vi gjøre det enklere"-spørsmålet
- generell hotjar: vurdere å slå av den generelle akkurat når vi har den spesifikke (snakke med Eira)
- vi kan telle både mangelbrev og avslag pga manglende dok, men må se på det over lengre tid (siden avslag kommer etter hvert)
- telle avslag pga ikke registrert arbeidssøker (fordi vi informerer om at man må være registrert på den nye siden)
- Måle hvor lang tid bruker de fra de har sendt inn søknad til søknaden er komplett med alle vedlegg
- Færre inaktiveringer pga manglende meldekort? Vet vi hvem som blir "feilaktig" inaktivert? Feks de som blir reaktivert innen 28 dager
- Måle før og etter hvor mange som går fra dagens kvitteringsside til ny innsynsside (evt trykker på knappen) (hvis vi skal beholde dagens kvitteringsside og kanskje gjør noen endringer på knapp/lenke)
- Måle hvor mange som kommer tilbake til siden når de har vært der tidligere (dette kan bety både at siden fungerer eller at de roter rundt på ditt nav)
- Måle hvor brukerne kommer fra når de er inne på den nye innsynssiden (og hva gjør de etterpå)
- De som er inne på siden - hvor lenge siden er det de søkte? (Når er siden mest aktuell for brukerne?)
- NKS: logging 2. juni, ny logging etter ca 6 mnd?
- Tett dialog med NKS for å få tilbakemeldinger (informere på dagpenger med venner og bruke teams-kanal mm, + faste møtepunkter) - finne ut hvordan vi kan bruke de kanalene vi har på en god måte
- Sette opp nytt tid for brukertest (juni eller august) - teste i prod/test
- Sjekke om det er stor frontendjobb å lage egen tilbakemeldingsboks (javascript trigger -> hotjar), må kunne skrus av/på og vi må følge med jevnlig med et opplegg for å håndtere innspillene (og slette personopplysninger)

**Comment by ingridhaland** [comment]
Vi bør ha et sted med oversikt over alle målingene (feks en side med lenker i confluence)
