### ISSUE TITLE
Vurdere å legge til tekst på ettersendelsessiden om ettersending på papir

### ISSUE THREAD

**Issue by celinetendam** [navikt/dagpenger#807]

**Comment by celinetendam** [comment]
- Vurdere å legge inn en hjelpetekst som sier at dersom du har ettersendt vedlegg på papir så kan du se bort fra at vedlegget fortsatt står oppført under "Detter vedlegg du har sagt du skal ettersende".

For eksempel: "Dersom du har ettersendt vedlegg på papir kan det ta noe tid før det blir registrert hos oss, så snart vi har mottatt all informasjon vil du få et svar fra oss"

**Comment by tonjemjovik** [comment]
Vi har tatt en vurdering, og kommer ikke til å endre noe her i denne omgang
