### ISSUE TITLE
Registreringsløsningen var nede 19.5.2021 fra kl. 23:30 til 0200 - Kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#809]
https://nav-it.slack.com/archives/CEE8ZNS81/p1621414139012100 
![image](https://user-images.githubusercontent.com/61459197/118944382-cea14900-b954-11eb-8892-3ddfbef44ccc.png)

Listen legges i et eget excel-ark på:
https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/Shared%20Documents/Diverse/S%C3%B8knader%20-%20Registreringsl%C3%B8sning%20nede/Reg%20l%C3%B8sning%20nede%2019.%20mai%202021.xlsx?d=w981adcb120614003acff8e6e401f1a07&csf=1&web=1&e=7rVMHp 

Når klart så tagg Eivind, så sjekker han

Ref. tidligere uttrekk: #686

**Comment by atleno** [comment]
Listen er klar, @Eivind833

**Comment by EivindRoyrvik** [comment]
Gjennomgått listen.
