### ISSUE TITLE
Analyse av vedleggsfri søknad - O2T6T8 - Sjekke mulighet til å vise arbeidsforhold til søker

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#810]
- [x] Se på om vi trenger nytt faktum til arbeidsforhold som brukeren velger. Se paa hvordan faktum modellen brukes/bygd opp   i db-soknad-server
- [x] I frontenden: Vise arbeidsforhold fra Aareg/dp-soknad-server. Gi bruker mulighet til å velge og evt endre paa valgte arbeidsforhold
- [x] Fikse service bruker som har tilgang til aareg. Se på srvdp-soknad-sbs i gruppetilgang iac repoet.
- [ ] Måle antall som velger arbeidsforhold fra liste/velger og endrer/ legger til egne arbeidsforhold
- [x] Gå igjennom tekster 
- [x] Engelske oversettelser av tekster
- [ ] Skal det være med på gjennopptak? Vi sjekker hvor vanskelig/lett det er å gjøre
- [ ] Vi må legge til en validering at bruker må gjøre et valg på "Velg Arbeidsforhold"
- [ ] Endre disclaimertekst i permittering da vi ikke viser tildato

**Comment by gtcno** [comment]
- [ ] Se på om vi trenger nytt faktum til arbeidsforhold som brukeren velger. Se paa hvordan faktum modellen brukes/bygd opp   i db-soknad-server
- [x] I frontenden: Vise arbeidsforhold fra Aareg/dp-soknad-server. Gi bruker mulighet til å velge og evt endre paa valgte arbeidsforhold
- [x] Fikse service bruker som har tilgang til aareg. Se på srvdp-soknad-sbs i gruppetilgang iac repoet.
- [ ] Måle antall som velger arbeidsforhold fra liste/velger og endrer/ legger til egne arbeidsforhold
