### ISSUE TITLE
Inntekten skal ikke oppjusteres for lærlinger

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#811]
Av midlertidig forskrift https://lovdata.no/dokument/SF/forskrift/2020-03-20-368#KAPITTEL_2  § 2-3 andre ledd:

«Dagpenger til lærlinger gis med 100 prosent av den delen av lærlinglønnen som er under 1,5 ganger grunnbeløpet, og med 62,4 prosent av den delen av lærlinglønnen som er mellom 1,5 og 6 ganger grunnbeløpet. Lærlinglønnen er den lønnen lærlingen hadde på tidspunktet for permittering eller bortfall av lærlingplassen. Folketrygdloven § 4-11 annet ledd første og annet punktum og tredje ledd og § 4-12 annet og tredje ledd gjelder ikke for lærlinger.»

Vår tolkning av  lønn lærlingen hadde på tidspunktet for permittering eller bortfall av lærlingplassen.
For å beregne et dagpengegrunnlag har vi tolket det til å utgjøre det gunstigste av følgende to alternativer:
Enten den siste avsluttede kalendermåneden forut for beregningsdato, multiplisert med tolv,
Eller de tre siste avsluttede kalendermånedene forut for beregningsdato, multiplisert med fire.

For å beregne et dagpengegrunnlag har vi tolket det til å utgjøre det gunstigste av følgende to alternativer:
1. Enten den siste avsluttede kalendermåneden forut for beregningsdato, multiplisert med tolv,
2. Eller de tre siste avsluttede kalendermånedene forut for beregningsdato, multiplisert med fire.

MEN inntekt skal ikke oppjusteres. 

**Feilen vi skal rette er at vi ikke skal oppjustere inntektene ift G.**

**Comment by Elinvethe** [comment]
Feilen vi skal rette er at vi ikke skal oppjustere inntektene ift G.
