### ISSUE TITLE
Søknadsdialogen og innløpet - Slå av merking/ruting 28. januar 2022 og fjerne spørsmål om fortsatt rett 1. februar 2022

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#827]
Ref. https://github.com/navikt/dagpenger/issues/655 og https://github.com/navikt/dagpenger/issues/684 hvor vi innførte nytt spørsmål i søknadsdialogen, samt ruting av disse til 4451 Arena-benk.

1. februar 2022 avvikles regelverket, og vi må avvikle spørsmålet i søknadsdialogen og da også funksjonaliteten i innløpet som vi etablerte denne datoen.

- [ ] https://jira.adeo.no/browse/ARENA-5386 og https://jira.adeo.no/browse/ARENA-5854# , vår avvikling i søknadsdialogen og innløpet må sannsynligvis taktes mot arenaavviklingen. Spesielt innløpet hvor vi sender merker og ruter til arena 4451 om JA på spørsmålet. Kan f.eks. mellomlagrede søknader med JA på dette spørsmålet, som sendes inn av bruker etter 31.01.2022 påvirke negativt? Må analyseres noe i tid før avviklingen

- [x] Uklart når denne skal implementeres ifra, gitt at ny regjering har varslet at pandemiregelverket forlenges. Magne kommer tilbake med ny dato for avvikling. Må avventes inntil videre.

**Comment by magnefjeld** [comment]
Regelverket:
https://lovdata.no/dokument/LTI/forskrift/2021-01-29-260 
 
§ 2-8.Særlige regler om fortsatt dagpengerett for medlemmer som har avsluttet dagpengeperioden etter 31. oktober 2020 – unntak fra folketrygdloven § 4-3, § 4-4, § 4-9, § 4-11, § 4-15, § 4-19 og § 22-13
Medlemmer som i perioden fra og med 1. november 2020 har nådd maksimal dagpengeperiode etter folketrygdloven § 4-15 og § 4-19, kan søke om fortsatt dagpengerett for perioden fra og med 1. februar til og med 30. september 2021.

Dagpengene i denne perioden beregnes med utgangspunkt i den samme arbeidstidsreduksjonen og det samme dagpengegrunnlaget som gjaldt i den avsluttede dagpengeperioden. Vilkårene i folketrygdloven § 4-3 tredje ledd og § 4-4 fjerde ledd om at tidligere inntekt og arbeidstidsreduksjon bare kan legges til grunn for én full stønadsperiode, gjelder ikke, og det påløper ikke ventetid etter folketrygdloven § 4-9.

Det kan innvilges fortsatt dagpengerett med virkning fra og med 1. februar 2021 dersom det fremsettes søknad innen 1. mars 2021. Folketrygdloven § 22-13 femte ledd gjelder ikke for slike søknader. Medlemmer som fremmer søknad etter 1. mars 2021, kan få innvilget fortsatt dagpengerett tidligst fra søknadstidspunktet.

Dagpengeretten etter denne paragrafen gjelder frem til og med 30. september 2021, uten hensyn til folketrygdloven § 4-15 og § 4-19. 

Ny § 2-9 skal lyde:

 
§ 2-9.Fortsatt dagpengerett etter § 2-8 for medlemmer som er innvilget dagpenger etter folketrygdloven kap. 4 eller andre ytelser etter 31. oktober 2020
Medlemmer som etter 31. oktober 2020 har fått innvilget en ny dagpengeperiode eller andre folketrygdytelser, kan velge å si fra seg disse ytelsene og i stedet få innvilget fortsatt dagpengerett etter § 2-8 dersom vilkårene for dagpenger ellers er oppfylt. Det samme gjelder medlemmer som har fått innvilget tiltakspenger etter tiltakspengeforskriften. Tiltakspengeforskriften § 7 gjelder ikke for disse medlemmene.

Fortsatt dagpengerett etter første ledd kan gis tidligst fra søknadstidspunktet.

**Comment by magnefjeld** [comment]
![image](https://user-images.githubusercontent.com/61459197/120456457-e8e81780-c395-11eb-9f5f-d88cd161925d.png)

**Comment by magnefjeld** [comment]
**Foreløpig plan er at vi slår av ruting/merking i vårt innløp 28. september 2021, og 1. oktober fjerner spørsmålet fra søknadsdialogen.** Når ruting/merking slås av på spørsmålet vil det ikke trigge noe i Arena rundt "fortsatt rett".

**Comment by magnefjeld** [comment]
16. oktober 2021 har vi fått følgende beskjed fra Yngvar, om hva som er besluttet (tolker ut fra dette at fortsatt dagpengerett også forlenges tilsvarende):

- Perioden arbeidsgivere kan fritas fra lønnsplikt under permittering og tilsvarende periode med rett til dagpenger under permittering forlenges til og med 31. desember 2021.

- Dagpengeperioden forlenges til og med 31. desember 2021 for alle dagpengemottakere som ellers vil ha brukt opp hele dagpengeperioden før årsskiftet.

t.o @Elinvethe

**Comment by geiralund** [comment]
Håndteres av https://github.com/orgs/navikt/projects/18
