### ISSUE TITLE
Søknadsdialogen - Dokumentasjonskrav gjeninnføres 1. april 2022

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#830]
NAV har selv bestemt at vi foreløpig ut mars 2022 har et forenklet dokumentasjonskrav knyttet til permittering.
se https://confluence.adeo.no/display/TDP/Forenklet+dokumentasjonskrav for mer informasjon.

Når kravet gjeninnføres må vi se hvordan vi skal løse dette behovet i søknadsdialogen. Reversere fullt tilbake til endringene vi gjorde eller møte behovet på annen måte ?

- [ ] Behov for utarbeide et grunnlag der vi redegjør for behov og effekter, samt hva vi tenker er handlingsrommet for forenklet dokumentasjonskrav
- [ ] Avklare med NAY hvordan de vurderer å skru på dokumentasjonskravet, samt deres erfaringer med forenklet FVA, mulig om de også kunne gjort en kvalitetssjekk på sluttårsak

- [x] Dette må avklares: hva er skissert av forenklet telling av lønnspliktdager og hva blir gjeldende til 1.1.2022. Ikke aktuelt lenger

**Comment by Elinvethe** [comment]
Referat fra møte 31.08 med team regelverk for overføring av denne problemstillingen til oss: 

FVA
under korona er det vedtatt et midlertidig regelverk for FVA: 
https://lovdata.no/nav/rundskriv/r04-00-01 se § 11-2. 
Vi bør undersøke hvilke erfaringer man har fra midlertidige regler for FVA . Tilbakemeldingen fra NAY er at de i praksis ofte sjekker AA-registeret uansett og dermed ikke stoler "blindt" på det bruker oppgir i søknaden.   

Det bør utredes hvordan midlertidig regelverk har fungert. Hvilke erfaringer har NAY og NKS , samt mulig utrekk fra Arena for å vite fordelingen i FVA selv om det kan være vanskelig sammenligne med prekorona fordeling.  Team Regelverk kjenner til en klagesak der en person har bedt om FVA etter gammelt regelverk fordi det regelverket er bedre for han. 
-	Innhenting kvantitativ og kvalitativ undersøker på erfaringer fra FVA

Vi skal FVA – bedre ut ved å bruke dagpengegrunnlaget-  hva med egen næring og hva med de med tjener mye med lav stillingsbrøk og noen har høy stilling men lav inntekt. 
Kontantprinsippet og periodisering: Når bruker innvilges dagpenger innvilges forholder v oss til kontantprinsippet, på meldekort periodiseringen. 
-	Denne burde vært priortiert i regelverkprosjekt
Lenker på confluence til dette: 
Simulere dagpengegrunnlaget slik at vi kan se FVA  

forenklet dokumentasjonskrav frem til 1.1.2022
Hvis vi skal "tilbake" bør prioritere gjennomgang av skjemaer vi i dag ber bruker om, er det nødvendig alt vi ber om?

Det er relevant å kjenne til situasjonen hos NAY som nå stabiliserer seg, men de henger fortsatt vesentlig etter på klage og feilutbetaling

Vi har ingen forenklet dokumentasjonskrav for ordinære utover de midlertidige reglene for FVA som i seg seg forenkler dokumentasjonsbehovet. Hva når permitteringer går til ordinær eller konkurs

Det er opprettet et drodlenotat om dokumentasjonskrav: https://navno.sharepoint.com/:w:/s/Teamregelverkdagpenger/Ec0GuYTCTFNAqmpREeHWQUkB_6hJAWBxwpNnVAJDZcsY3Q?e=HQSkcU&CID=0234F1C6-1D79-4DC3-8AFE-28F1866CD018&wdLOR=c630CFF3E-75E7-41B3-AB06-3497D1B7F6F2
	forenklet dokumentasjonskrav: Vi etterlyser ikke arbeidsavtale eller bekreftelse på permitteringen
Hvis permitteringsvarsel har den informasjonen skal dette som hovedregel være nok. i praksis er det "grønt lys" på permittering
 Basert på dette har vi tilpasset veiledningen, papir og elektronisk søknad. 


1.1.22 skal dette reverseres – dette styrer vi i NAV så lenge vi har forsvarlig saksbehandling
Hvis man forlenger deler av koronaregelverket utover 1.10, og det vil påvirke til FVA og dokumentasjonskrav
Hva er handlingsrommet vårt på dette. Hvor mye informasjon skal man utrede første gnag, og hvor mye skal utrede

Parallelt med dette 31.12.22 alle papirskjemaene 
-	Flytte søknadene på rot
-	Foreløpig er ikke vedlegg prioritert. 
(NAY det er bare å slå på skjemaene i sin helhet) – hybridskjema

**Comment by Elinvethe** [comment]
referat  møte med Hertzberg 31.8
Hensikten med møte var å ta ned usikkerhet rundt FVA og dokumentasjonskravet - hvilke mulighetsrommet har vi å jobbe etter . I tillegg til dette vet vi at skjemadigitalisering skal erstatte alle papirvedlegg/pdf innen 31.12.2022.  

Vi vet at man har vært avhengig av både forenklet FVA og forenklet dokumentasjonskrav ellers ville man ikke klart å komme unna saksbehandlingen. ASD vil ha mest mulig forenkling for oss, og vi må gjøre en vurdering av hvor grensen går i det handlingsrommet. Endrede regler for FVA må ses i sammenheng med regelverksutviklingsprosjektet og forsåvidt p4. Trenger et grunnlag på vurdering av handlingsrommet -  Vi må også avklare hva et godt grunnlag på dette er. Nå er det bevegelse på avviklingen til 1.1.0 som kan medføre et behov og mulighet for forlengelse av forenklet FVA og dokumentasjonskravet,  og kan gi oss mye annet i tillegg. Selv om NAV i stor grad vurderer dokumentasjonskravene selv så er disse en  operasjonalisering av de rettslig rammene - ASD vil derfor også bry seg om dokumentasjon er god nok. Ikke noe vi bare kan beslutte internt. Vi må kunne beskrive hvilke effekter endring i dokumentasjonskravet  vil ha .  Neste år kommer til å bli et stramt år for ytelsene. Vi må derfor få opp et grunnlag med en god begrunnelse for å forlenge videre med FVA, hvilke konsekvenser er det - hvem kommer godt ut og hvem kommer dårlig ut. Argumentere for hvorfor vi mener at dette er de rette å gå for.  En ting er det langsiktig hva skal erstatte dagens regel, og det andre mer kortsiktige hva skjer når vi "skrur" av forenklede dokumentasjonskravet. Det vil også være slik at hvis vi skal gjeninnføre dokumentasjonskravet, så må det gjøres noe før 1.1.2022 slik at søknader som behandles fra 1.1.2022 er mest mulig komplette. Det er dog en  klar forventning fra ASD at vi gjeninnfører dette dokumentasjonskravet. må ev. finne andre hensyn. Vi må i grunnlaget beskrive hvilke handlingsrom vi tenker at vi har, hvordan har vi tenkt å håndtere dokumentasjonskravet. Hva vil situasjonen knyttet til dokumentasjonskravet være ved nyttår. Vi må være tydelige på hva er det vi spør ASD på dette - Beskrive hvordan vi har tenkt å håndtere dokumentasjonskravet på denne måten til nyttår. versjon 2.0 etter korona. 

Hvilke erfaringer har vi gjort med FVA og forenklet dokumentasjonskrav

Vi må utarbeide et grunnlag for vurdering av både FVA og forenklet dokumentasjon fra 1.1.2022

**Comment by magnefjeld** [comment]
OBG forlenget ytterligere ut mars 2022

**Comment by geiralund** [comment]
Håndteres av https://github.com/orgs/navikt/projects/18
