### ISSUE TITLE
Søknadsdialogen - Endre spørsmål knyttet til utdanning når nytt regelverk kommer 1. oktober 2021

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#831]
Det er for tiden et midlertidig regelverk på utdanning, som er planlagt avviklet 1. oktober 2021 (med overgangsregler). Regelverket blir vedtatt i løpet av juni 2021.

Team innhold har ansvar for å lage søknaden knyttet til det nye utdanningsregelverket.

Det vil også fra 1. oktober  2021 være behov for å endre spørsmålene knyttet til utdanning i søknadsdialogen. Dett må synkes mot det nye søknadsskjemaet for utdanning som lages.

Se arbeidssider på https://confluence.adeo.no/display/TDP/Utdanning+og+dagpenger+-+reform

**Comment by magnefjeld** [comment]
![image](https://user-images.githubusercontent.com/61459197/120459742-c0ade800-c398-11eb-8671-444ac04c3b5c.png)

**Comment by magnefjeld** [comment]
- https://lovdata.no/dokument/LTI/lov/2021-06-18-92 Lovendringen nytt regelverk på utdanning. Forskrift foreligger ikke ennå.

- https://lovdata.no/dokument/LTI/forskrift/2021-07-01-2320 midlertidig regelverk forlenges til og med 30. september (og oppheves fra og med 1. oktober 2021): https://lovdata.no/dokument/LTI/forskrift/2021-07-01-2320

**Comment by Elinvethe** [comment]
team innhold holder i ny søknad ved utdanning, betyr dette også at dere planlegger å gjøre endring i funksjonalitet i elektronisk søknadsdialogen  eller er det forventet at team automatisering skal utføre disse @kmriise ?

**Comment by magnefjeld** [comment]
@ChrisdeVriesEnger vil 10. august 2021 avklare med innholdsteamet (primært @kmriise) hvordan man gjennomfører de tenkte endringene i søknadsdialogen. Så vidt jeg oppfattet er foreløpig plan at man rundt 1. september 2021 gjør mindre endringer (kun informasjon - tekstboks) i søknadsdialogen med informasjon om at det kommer nytt regelverk 1. oktober 2021.

Deretter vil man til leveransen 1. oktober 2021 måtte fjerne dagens spørsmål om utdanning (sannsynligvis kun beholde om man er under utdanning eller ikke) og legge inn lenke til nytt søknadsskjema på utdanning.  Endringene må taktes mot de andre endringene vi skal gjøre i søknadsdialogen, slik at alle som gjør endringer her til rundt samme tid er klar over hva som skjer.
 
Endringene må naturlig nok testes.

t.o @Elinvethe

**Comment by kmriise** [comment]
@Elinvethe @magnefjeld @ChrisdeVriesEnger 
Jeg kan nok ta tak i denne. Jeg antar at automatisering bruker disse faktaene for å gjøre en sortering i saksbehandlingen? Isåfall må det tas høyde for at vi kanskje endrer en del av faktaene I denne bolken, kan gi en oppdatering når vi vet hva vi ønsker å gjøre med søknadsdialogen.

**Comment by kmriise** [comment]
Per i dag er målet å få til en informasjonstekstboks samtidig som brevene går ut, planlagt rundt 8. september.

Andre endringer i søknadsdialogen blir sett på når brev og utdanningssøknad er bedre spikret.

**Comment by Elinvethe** [comment]
Jeg skjønner - er det noe i innløpet vi må se på i denne forbindelse? Vi ruter søknad om utdanning til egen kø

@kmriise @geiralund

**Comment by kmriise** [comment]
Det spørs jo, ønsker vi fortsatt å rute dem til egen kø? Og går det egentlig på hovedspørsmålet som ikke kommer til å fjernes?
Jeg har en magefølelse på at det skal gå bra, men lover ingenting.

Planen vår slik jeg har forstått det er å droppe underspørsmålene på utdanning, og så heller gi en informasjonsboks om at de også må søke den ekstra søknaden om å få innvilget dagpenger under utdanning. faktumet om at man er i skole eller utdanning vil fortsatt være der, men ikke underfaktumet om at man får penger fra lånekassen, da jeg trooor det tas i den nye dagpenger med utdanning søknaden.

**Comment by kmriise** [comment]
@Elinvethe 
Ruter vi egentlig søknad om utdanning til egen kø?
Preiket med @geiralund tidligere i dag, og virker ikke som at vi ruter dagpengesøknader som kombinerer utdanning til egen kø. Er klar over at den ekstra søknaden om dagpenger under utdanning rutes, og der har ikke brevnummeret endret seg når vi gikk over til den nye "digitale" versjonen. Så den skal i teorien fungere som før.

Faktum som fortsatt vil være i bruk:
utdanning (dette er et faktum som tar en streng, svarene som sendes fra frontend er f.eks 'ikkeUtdanning', 'avsluttetUtdanning' og 'underUtdanning')

Faktum som ikke vil bli fylt ut når vi fjerner utdanningspm og går over til å veilede bruker til å fylle ut en ekstra søknad for dagpenger under utdanning, kan hende at dette brekker litt greier, kan hende at det ikke gjør det. alternativet er å fjerne faktumene helt, men det kan muligens brekke enda mer greier:
utdanning.underutdanning
utdanning.korona2020
utdanning.kveld
utdanning.kveld.progresjonUnder50
utdanning.kveld.paabegyntUnder6mnd
utdanning.kveld.sted
utdanning.kveld.navn
utdanning.kveld.varighet
utdanning.kveld.avslutning
utdanning.kortvarig
utdanning.kortvarig.sted
utdanning.kortvarig.navn
utdanning.kortvarig.varighet
utdanning.norsk
utdanning.norsk.sted
utdanning.norsk.varighet
utdanning.introduksjon
utdanning.annet
utdanning.laanekassen

**Comment by kmriise** [comment]
Hvor sikre er vi på at det er null stress å la faktumene ligge i dp-server koden?
Isåfall er dette en veldig enkel endring å gjennomføre, bare fjerne vedleggslogikken rundt faktumene og så velge å aldri stille spørsmålene i frontend. 🥳

**Comment by kmriise** [comment]
Aight, ser veldig greit ut når vi bare kverker faktumene.
Derimot så blir vedlegg hengende igjen, hvis det allerede er opprettet vedlegg rundt utdanning og så mellomlagret. Regner med det er innafor?

**Comment by kmriise** [comment]
Frontend:
https://github.com/navikt/dp-soknad-frontend/tree/feature/fjerneutdanning

Server:
https://github.com/navikt/dp-soknad-server/tree/feature/avvikling-korona-del1

Todo:
opprydding i deployfilene
engelsk tekst
???
profit

**Comment by magnefjeld** [comment]
@kmriise er ikke denne ferdig ?
