### ISSUE TITLE
Registreringsløsningen vært nede i ulike perioder - Kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#849]
https://nav-it.slack.com/archives/CEE8ZNS81/p1623260131116200  (9. juni 2021: kl. 23:00 til kl. 23:59)
![image](https://user-images.githubusercontent.com/61459197/121407359-811a6980-c95f-11eb-8e23-b9cda10a06bb.png)

https://nav-it.slack.com/archives/CEE8ZNS81/p1623416073120000 (11. juni 2021: kl. 07:30 til kl. 08:30)
![image](https://user-images.githubusercontent.com/61459197/122034033-66b61500-cdd1-11eb-8ca0-0ecb40948bc4.png)

https://nav-it.slack.com/archives/CEE8ZNS81/p1623678547129100 (14. juni 2021: kl. 23:00 til kl. 23:15 )
![image](https://user-images.githubusercontent.com/61459197/122034212-91a06900-cdd1-11eb-8a6b-d1a6d608575b.png)

Listen legges i et eget excel-ark på:
https://navno.sharepoint.com/:x:/s/Korona-dagpenger-uttrekk/EVzHzcoSSNNOjsfhfP2SlpkBABz0wjkQ553SJwsdbfckCQ?e=stmBZt (3 flipper med de ulike datoene)

Når klart så tagg Eivind, så sjekker han

Ref. tidligere uttrekk: #686

**Comment by atleno** [comment]
@Eivind833 Lagt inn i lista, kom bare inn søknader den første perioden

**Comment by EivindRoyrvik** [comment]
Sjekket listen, følger opp en sak i prod, ellers ok.
