### ISSUE TITLE
Overgang TPS til PDL

### ISSUE THREAD

**Issue by gtcno** [navikt/dagpenger#857]
Se navikt/dagpenger#650

Konkret er det følgende som må gjøres

1. dp-kalkulator-api skrives om til å bruke PDL apiet direkte
2. dp-soknad-server skrives om til å brike PDL apiet direkte 

** dp-kalkulator-api skrives om til å bruke PDL apiet direkte**

- [x] Azure AD tilgangskontroll må settes opp slik at dp-kalkulator-api kan kommunisere med pdl. Vi bruker systembrukere og gjør ikke en TokenX etter diskusjon med NAIS-teamet
- [x] Implementere graphql klienten mot PDL.

Hvis tid: 
- [ ] Når dette er i produksjon, kan dp-graphql  saneres
- [ ] Rydd opp i servibruke, api-gateways og annet ræl etter sanering av applikasjoner.

** dp-soknad-server skrives om til å brike PDL apiet direkte **

Denne har potensiall til å balle på seg så vi må bruke litt tid til å se på hva  som hentes fra TPS som kan 
hentes fra PDL

- [x] Flytte soknaddagpenger-server til teamnamespace.
- [x] Azure AD tilgangskontroll må settes opp slik at soknaddagpenger-server kan  kommunisere med PDL. 
Vi bruker systembrukere og gjør ikke en TokenX etter diskusjon med NAIS-teamet
- [ ] Implementere graphql klienten mot PDL.
- [ ] Vi henter fremdeles bankonto fra TPS, så PDL delen må flettes sammen med TPS.

**Comment by Elinvethe** [comment]
Har du fått sjekket hva som vises for kode 6 brukere av adresse i søknaden, og er det også noe eget for kode 7 @gtcno 

Videre vil det nå med PDL ikke være ønskelig med midlertidige adresser hos NAV. Det betyr at vi også må se på denne 
![image](https://user-images.githubusercontent.com/79975396/132308625-3bd004e1-01ed-4274-97ef-44758cdb85ee.png)
 
Ev. endringer i postadresse skal meldes til skatt, og NAV skal ikke en intern som i dag. Vi skal lenke til denne https://www.skatteetaten.no/person/folkeregister/flytte/endre-postadresse/ for endring av postadresser

Jeg ser om du har tid til en prat på onsdag om dette @gtcno

**Comment by gtcno** [comment]
> Har du fått sjekket hva som vises for kode 6 brukere av adresse i søknaden, og er det også noe eget for kode 7 @gtcno
> 
> Videre vil det nå med PDL ikke være ønskelig med midlertidige adresser hos NAV. Det betyr at vi også må se på denne
> ![image](https://user-images.githubusercontent.com/79975396/132308625-3bd004e1-01ed-4274-97ef-44758cdb85ee.png)
> 
> Ev. endringer i postadresse skal meldes til skatt, og NAV skal ikke en intern som i dag. Vi skal lenke til denne https://www.skatteetaten.no/person/folkeregister/flytte/endre-postadresse/ for endring av postadresser
> 
> Jeg ser om du har tid til en prat på onsdag om dette @gtcno

Hvis det er kode 6 eller 7 så sender vi tilbake en tom addresse til frontenden. 

MAO Adressen vises ikke til bruker dersom det er kode 6 eller 7

**Comment by gtcno** [comment]
Når det gjelder Midlertidig addresser, kan den endringen utfoeres uavhengig av PDL?

**Comment by Elinvethe** [comment]
Ja, den kan det. Jeg tenkte bare på at det er PDL som gjør at vi ikke skal bruke midl. adresser.
