### ISSUE TITLE
Lage en "Send inn vedlegg"-boks som lister ut søknader det kan ettersendes til

### ISSUE THREAD

**Issue by ingridhaland** [navikt/dagpenger#867]
Inngangen er litt gjemt i dag, og den er veldig viktig. Kanskje også mer naturlig å ha den i forbindelse med dokumentlisten, foreslår derfor noe sånt: 
![image](https://user-images.githubusercontent.com/76993680/122880300-26f3ae00-d33a-11eb-845c-863ac6aea6fe.png)

**Comment by androa** [comment]
Nytt forslag til hvordan vi kan løse dette.

![image](https://user-images.githubusercontent.com/588046/124553312-e1081100-de34-11eb-9641-5ed740dd35dd.png)

![image](https://user-images.githubusercontent.com/588046/124553297-dc435d00-de34-11eb-926a-9a5e8d3e07a7.png)

**Comment by ghost** [comment]
- [x] Lage Vedleggskomponent som:
- [x] Lister ut søknader (søknader som props)
- [x] Skal være ekspanderbar
- [ ] Finne ut hvor vi kan se hvor mange vedlegg som mangler
- [x] Fjerne "Last opp vedlegg" fra snarveier.
