### ISSUE TITLE
Endre tekst/lenke i arb.søkerregistrering-tekst + vurdere å lage egen status/tekst for iarbs

### ISSUE THREAD

**Issue by ingridhaland** [navikt/dagpenger#868]
De som ikke er registrert kan ikke sende meldekort. Men iarbs får ikke til å registrere seg? Forslag:
![image](https://user-images.githubusercontent.com/76993680/122880510-5b676a00-d33a-11eb-987d-5c7a160d280a.png)

**Comment by ghost** [comment]
Bruken av registrering-endepunktet fra veilarb er feil.
Vi må bruke startregistrering hvor vi får formidlingsgruppe og rettighetsgruppe. Se enumer her: https://github.com/navikt/arbeidssokerregistrering/blob/4f91f78603134ed582370a6550538abaabab7ac6/src/ducks/registreringstatus.ts#L16

Regler:

1. Hvis formidlingsgruppe == ISERV --> Ikke registrert og vi lenker til registrering som arb.søker
2. Hvis formidlingsgruppe == ARBS --> Er registrert og vi lenker til meldekort
3. Hvis formidlingsgruppe == IARBS && rettighetsgruppe === DAGP ---> Mottar dagpenger og vi lenker til meldekort
4. Hvis formidlingsgruppe == IARBS && rettighetsgruppe !== DAGP ---> Mottar IKKE dagpenger og vi lenker til registrering

Finnes det en manuell fallback i registreringsløsningen? Hvis nei må vi ikke lenke til registrering, men ta kontakt med NAV på telefon (gjelder regel 4).

**Comment by tonjemjovik** [comment]
De som er i gruppe 3: 
"For å fortsette å få dagpenger må du sende hvert meldekort innen fristen"

**Comment by androa** [comment]
Løst i https://github.com/navikt/dp-dagpenger/commit/846ec17179f9d91bbc49e62ae4e36471b49ee24b
