### ISSUE TITLE
Frontend: Håndtering av kontonummer fra andre land.

### ISSUE THREAD

**Issue by ghost** [navikt/dagpenger#871]
Visning av kontonummer (Kontonummer.tsx) antar at kontonummer er et norsk kontonummer.

**Comment by celinetendam** [comment]
![image](https://user-images.githubusercontent.com/63904343/123081998-db670000-d41e-11eb-949e-7c209322e014.png)

Eksempelet over viser et utenlandsk kontonummer. Fordi visning av kontonummer antok at nummeret er norsk, ble de første tallene gruppert etter 4 2 6, og resten forsvant. La derfor inn en midlertidig løsning som ikke formaterer dersom nummeret er lengre enn 12
