### ISSUE TITLE
Hacke til en løsning for de viktigste UU-avvikene

### ISSUE THREAD

**Issue by Elinvethe** [navikt/dagpenger#874]
Dagens søknadsdialog har flere UU avvik. Frist for å rette disse er 2021. 

Vi skal starte på ny søknadsdialog etter sommeren, men er den klar for alle tilfeller innen utløpet av 2021?

Hvis den ikke er det må vi se på løsninger for UU avvikene i dagens søknadsdialog samtidig som vi jobber med ny søknad. 

De viktigste avvikene er: 

- [x] Bytte av fokus for radiobuttons endrer valgt alternativ (3.2.1) - denne ødelegger helt for personer som ikke ser at valget endrer seg, og er svært frustrerende for mange. Den burde fikses så raskt som mulig (venter på godkjenning av PR fra team søknad for legacy frontend bibliotek)

- [x] Ved fjerning av stilark blir feilmeldinger synlige (blant annet feilmeldingen “Oops, noe gikk galt”) selv om det ikke er noen feil på siden (1.3.1 og 1.3.2) - den er også meget viktig 

- [ ] Broken aria-referanser i arbeidsforhold vindu (1.3.1 og 1.3.2) 

(kontrast burde nok kunne fikses enkelt og, men den har lavere prioritet)

**Comment by geiralund** [comment]
- data-booleanradio må også patches, er ikke kombatibel i henhold til tastaturnavigasjon (2.4.3 focus order) ref https://github.com/navikt/dagpenger/issues/880
