### ISSUE TITLE
Registreringsløsningen vært nede 30. juni 2021, kl 23.00 til 03.30 - Kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#878]
https://nav-it.slack.com/archives/CEE8ZNS81/p1625043085166300 
![image](https://user-images.githubusercontent.com/61459197/123933064-5043b800-d992-11eb-948a-3685a9cbf3a5.png)

listen kan legges på https://navno.sharepoint.com/:x:/s/Korona-dagpenger-uttrekk/ET8gbDMEWlRPjYi6ECy4c2oB-UCPgmNYSnSHBvLDhsNvCQ?e=VTkhek

si ifra til Magne når klart (Eivind ferie)

**Comment by EivindRoyrvik** [comment]
Gjennomgått listen. Alt ok.
