### ISSUE TITLE
Feil i dp-oppslag-vedtak: java.lang.NullPointerException: vedtak.vedtaksperiode.fom must not be null

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#895]
Feilogg - https://logs.adeo.no/goto/6b806e0355931a8bdf1c34a45046a289

**Comment by androa** [comment]
Jeg fiksa han med å tillate nullable FOM i vedtaket, vi bruker det uansett ikke til noe nå (vi ser kun på saker).
