### ISSUE TITLE
Endringer til 1. april 2022 - Samlekort for endringer

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#896]
Til 1. februar 2022 er det flere endringer, både regelverksendringer og praksisendringer, som treffer digidag.

1.  Lærlingeordningen avvikles i sin helhet - https://github.com/navikt/dagpenger/issues/599 (primært fjerne spørsmål i søknadsdialogen)
2. Regler for fastsetting av vanlig arbeidstid tilbake til pre-covd-19 regler  (https://github.com/navikt/dagpenger/issues/829) 
3. Fortsatt dagpengerett opphører - https://github.com/navikt/dagpenger/issues/827
4. Forhøyet dagpengesats opphører - https://github.com/navikt/dagpenger/issues/950
5. Endre "mykere" veiledning i søknadsdialogen ved reell arbeidssøker pga korona. tilbake til gammel veiledningstekst **(er det laget noe eget kort som beskriver endringene ?)**

**Comment by magnefjeld** [comment]
Redusert dokumentasjonskrav oppheves - https://github.com/navikt/dagpenger/issues/830  (Praksisendring) er foreløpig forlenget ut mars 2022

**Comment by geiralund** [comment]
Håndteres av https://jira.adeo.no/browse/DAG-148
