### ISSUE TITLE
Risikopunkter før 1. oktober 2021 - automatiske avslag i Quiz

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#914]
To problemstillinger før regelendring 1. oktober 2021. Brevutsending er planlagt å starte 2. september 2021. 

1. Gjenopptak etter fortsatt rett
2. Permitteringssaker og tolkning av "ny søknad" i forskriften § 6-5. Praksisen med ny rettighet etter avbrudd i 6/10 uker er langvarig, men det er meldt som problemstilling til Team Regelverk for å avklare om dette er korrekt. 

Det kan være nåværende sjekker fanger opp sakene som skal til manuell behandling, men dette er risikopunkter som vi bør tenke gjennom. Worst case er at vi må skru av Quiz i produksjon før 1. oktober 2021. 

avklart 

tar uttrekk av saker med lukket sak og fortsatt rett for å få størrelse på problemet - det er for vudering av om NAY må fikse opp i dette selv. 

For å håndtere 1.10 problematikk setter vi søknader innkommende i september, men som søkre fra 1.10 til manuell behandling.   NB hvis det blir forlengelse her må vi se på denne regelen igjen

avklart at tolkning av § 6-5 ikke er et problem for denne saken

**Comment by Elinvethe** [comment]
**Fortsatt rett:** 

mulig gjenopptak: har hatt dagpenger siste 36 måneder, men hvordan defineres har hatt dagpenger:

de som søker nå før sak lukkes, vil gå til manuell behandling. 

Problemet er at vi ikke kan stole helt på telleverket i disse saker. Må inkludere lukket i vår spørring.

lukket sak i 2021 og fortsatt rett - uttrekk fra Arena for vurderingen om NAY skal fikse opp i dette selv.  



**ny/G søknad ved korte avbrudd permittering:**

ikke et problem siden alle vil bli vurdert som potensielt gjenopptak. 



**virkningstidspunkt og skille mellom midlertidig og tidligere regelverk:**

i manuell saksbehandler ville disse kunne bli plukket opp, bør vi har en egen regel der søknad er innkommet i september, men ønsker fra oktober i søknader

mulig løsning: dersom søknadstidspunkt er i september og ønsker dato er i oktober så går dette til manuell. (gjeld). 

frem i tid: 

hvordan skal vi håndtere brukere som søker "for langt" frem i tid på andre siden av terksel. ikke et problem når vi nå løser punktet over

**Comment by Elinvethe** [comment]
fortsatt rett: 

mulig gjenopptak: har hatt dagpenger siste 36 måneder, men hvordan defineres har hatt dagpenger:

de som søker nå får sak lukkes, vil gå til manuell behandling. 

Problemet er at vi ikke kan stole helt på telleverket i disse saker og derfor vi risikerer å feilaktig avslå noen

lukket sak i 2021 og fortsatt rett - uttrekk fra Arena for vurderingen om NAY skal fikse opp i dette selv.  @magnefjeld  har du bedt om uttrekket?



ny/G søknad ved korte avbrudd permittering:

ikke et problem siden alle vil bli vurdert som potensielt gjenopptak. 



virkningstidspunkt og skille mellom midlertidig og tidligere regelverk:

i manuell saksbehandler ville disse kunne bli plukket opp, bør vi har en egen regel der søknad er innkommet i september, men ønsker fra oktober i søknader

mulig løsning: dersom søknadstidspunkt er i september og ønsker dato er i oktober så går dette til manuell. (gjeld).

**Comment by EivindRoyrvik** [comment]
Implementert sjekk om dersom søknadstidspunkt er i september og ønsker dato er i oktober så går dette til manuell.

Øvrige saker er vurdert til lav risiko. Uttrekket viser lav saksmengde. Manuell etterkontroll er tilstrekkelig.
