### ISSUE TITLE
Planlegge brukertest/intervjuer

### ISSUE THREAD

**Issue by ingridhaland** [navikt/dagpenger#915]
Planlegge en brukertest, kanskje i uke 35 (tirsdag+onsdag?)

To do:

- [x] Sette opp hotjar-rekruttering
- [ ] Finne ut hva vi vil teste / spørre om
- [ ] Lage testscript
- [ ] Sette opp tidspunkter og videomøter
- [ ] Finne ut hvem som blir med på hvilken test (fra teamet)

Dette lurer vi på (teste og/eller spørre om)
- Utfordringer med dagens søknadsprosess?
- Drømmesøknadsprosess?
- Hvordan brukes infosider+søknad+dittnav i dag? Bra/dårlig?
- Teste konseptskisser for ny søknad/flyt?
- Noe spesifikt mtp UU? Prøve å få med brukere med funksjonsnedsettelse?

**Comment by ghost** [comment]
Lukker denne da den er utdatert.
