### ISSUE TITLE
Registreringsløsningen nede 25. august 2021 kl. 2300 til 0030 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#919]
https://nav-it.slack.com/archives/CEE8ZNS81/p1629874922038200

![Skjermbilde 2021-08-25 110744](https://user-images.githubusercontent.com/82581338/130762719-1b0d47a0-bae8-4ac8-a628-ad0d8ede6b9b.png)

Listen kan legges på https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7B8ef42bc1-866d-406f-b2a1-c6f8904ec36a%7D&action=editnew

Kan si ifra til meg når listen er klar.

**Comment by MariusEriksen** [comment]
Har oppdatert listen med hvem som har søkt i tidsrommet 23:00 - 00:30.

**Comment by EivindRoyrvik** [comment]
Gjennomgått listen. Alt ok.
