### ISSUE TITLE
Søknadsdialogen - Veiledningstekster egen næring - Reversere til precovid-19 tekster

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#940]
ref: https://github.com/navikt/dagpenger/issues/828 

Egen næring må også reverseres til precovid-19 tekster (50 prosent). Står nå: 
![image](https://user-images.githubusercontent.com/61459197/135574739-d5c4d310-31b3-4229-9a0a-1a22029a459c.png)

Dette glemte vi også å gjøre i februar 2021. se https://github.com/navikt/dagpenger/issues/671 og kommentar av 17. februar 2021.

**Comment by magnefjeld** [comment]
hei @Eivind833  :)
ser du på denne ?

**Comment by geiralund** [comment]
@magnefjeld Vi ser på det. cc @Eivind833

**Comment by geiralund** [comment]
Denne er ute nå.
