### ISSUE TITLE
Registreringsløsningen nede 2. oktober 2021 fra klokken 0700 til 1300 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#941]
[https://nav-it.slack.com/archives/CEE8ZNS81/p1633094100113100](url)

![image](https://user-images.githubusercontent.com/82581338/135627408-8c8b198c-d046-427a-9a3e-4b1a53b9dc84.png)

Listen kan legges her: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7B18011f18-1e5e-4f2d-88f6-7ccee8499abf%7D&action=editnew

Jeg har ferie uke 40, men kan sjekke listen 11. oktober om ikke noen andre med prodtilgang har rukket å se på den før jeg er tilbake.

**Comment by geiralund** [comment]
Lagt til resultat i excel arket, 15 stk, @Eivind833  - venter ned å lukke denne til du har sett over

**Comment by EivindRoyrvik** [comment]
Gjennomgått listen, alt ok.
