### ISSUE TITLE
Søknadsdialogen - Fjerne spørsmål om Alderspensjon fra privat tjenestepensjonsordning - 1. januar 2022

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#943]
I statsbudsjettet for 2022 er det foreslått at samordning av dagpenger mot private tjenestepensjonsordninger – folketrygdloven § 4-26 første ledd bokstav b skal oppheves.

Hvis denne blir vedtatt så må vi fjerne alternativet fra søknadsdialogen fra og med januar 2022:

![image](https://user-images.githubusercontent.com/61459197/135884588-097859df-5b1a-4af3-984f-b72ee462e558.png)

- [x] Avventer vedtak i Stortinget - statsbudsjettet - desember 2021

Dette skal deployes når det blir vedtatt:
- [x] Frontend: navikt/dp-soknad-frontend#67
- [x] Backend: navikt/dp-soknad-server#157

**Comment by magnefjeld** [comment]
https://www.regjeringen.no/contentassets/917db4e3742f4dfa830068650b5b5352/no/pdfs/prp202120220004000dddpdfs.pdf 

@Elinvethe om vedtatt som foreslått, så vær oppmerksom på implementeringsdatoen på denne:
![image](https://user-images.githubusercontent.com/61459197/137156408-944015d1-d55a-41b7-bdd2-be7e8b845236.png)

Snakket med kjetil. Datoen blir da når den vedtas (en gang i løpet av desember 2021 av Stortinget). 

Foreløpig lar jeg overskriften på kortet stå, da dette foreløpig bare er forslag + at det er ny Regjering, samt at vi ikke vet hvilke dato dette eventuelt vedtas og om iverksetting blir senere enn foreslått.

**Comment by magnefjeld** [comment]
Så denne kan vi implementere tidligere enn 1. januar 2022.

**Comment by EivindRoyrvik** [comment]
Denne "trer i kraft straks" - det vil si når statsbudsjettet vedtas rundt 21. desember. Derfor kan den implementeres før 1. januar, men etter at budsjettet er vedtatt. 

Gjelder både ny rettighet og gjenopptak.

**Comment by ghost** [comment]
Endringer implementert. Lukker denne
