### ISSUE TITLE
Søknadsdialogen - Gjenopptak - avbruddsperioden FISK - 1. januar 2022

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#944]
I statsbudsjettet for 2022 er det foreslått at antall uker man kan permittere i fiskeforedlingsbedrifter (FISK) skal endres fra 52 til 26 uker (harmonisering med PERM). Vi vet ennå ikke om det blir endringer her (det vil si at avbruddsperioden blir som den er i dag) eller eventuelt om det blir en kortere avbruddsperiode.

A. Blir den samme som for PERM (mer enn 6 uker, kan vi fjerne spørsmålet rettet mot FISK og den ivaretas av eksisterende spørsmål om mer enn 6 uker):
![image](https://user-images.githubusercontent.com/61459197/136227925-943c63ee-b0c0-4824-9618-fdfed0d0dc65.png)

B. Blir den ulik PERM (mer enn seks uker), må vi tilpasse teksten med antall uker det landes på i forskriften:
![image](https://user-images.githubusercontent.com/61459197/136227714-0911d624-0dd7-4e2f-a8bc-2e725f4c5bbc.png)

Vi må da gjøre tilpasninger i vår digitale søknadsdialog.
 

- [ ] Avventer vedtak i Stortinget - statsbudsjettet - desember 2021

**Comment by celinetendam** [comment]
Deployes når det blir vedtatt:

Alternativ A:

- [ ] Frontend: navikt/dp-soknad-frontend#68
- [ ] Backend: navikt/dp-soknad-server#159

Alternativ B: Dette krever kun en tekstendring og er derfor ikke gjort klart på forhånd

**Comment by Elinvethe** [comment]
Lukker denne saken fordi forslaget ikke er med videre i statsbudsjettet for 2022

**Comment by Elinvethe** [comment]
Sak kan lukke fordi forslaget ikke er med videre i statsbudsjettet for 2022
