### ISSUE TITLE
Behov knyttet til helgen uke 41 og Koronaleveranse 26 ( lørdag 30. oktober 2021)

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#945]
- [x] Helgen 15-17. oktober 2021: Må påregne at det kommer bestillinger til statsbudsjettet for 2022 hva gjelder dagpenger. Ressurser fra digidag må være tilgjengelig til å kunne svare på spørsmål.
 - Kontaktpersoner: Geir A

- [x] Koronaleveranse 26 - lørdag 30. oktober 2021: Behov for at en utvikler fra digidag er tilgjengelig ved leveransen (avvikling av forhøyet dagpengesats).
- Kontaktperson:

**Comment by magnefjeld** [comment]
Lage denne til deg @Elinvethe , så kan du komme tilbake til hvem det blir. se også e-post som er sendt vedrørende helgen 15-17 oktober 2021.

**Comment by geiralund** [comment]
Lukker denne - jeg er kontaktperson

**Comment by geiralund** [comment]
Så det var to spørsmål på denne nå.

**Comment by magnefjeld** [comment]
@Elinvethe 
gitt ar det ikke blir noe av Koronaleveranse 26 lørdag 30. oktober 2021, så kan denne lukkes.
se også https://www.regjeringen.no/no/aktuelt/forlenger-koronatiltak-i-arbeidslivet-ut-aret/id2878080/

**Comment by Elinvethe** [comment]
koronareglene blir forlenget. ikke lengre aktuell
