### ISSUE TITLE
Registreringsløsningen nede 7. oktober 2021 klokken 2230 til 2300 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#946]
![image](https://user-images.githubusercontent.com/82581338/136772603-c6b71533-75d3-4f06-a85b-f9233022a8f7.png)

Listen kan legges her: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7B04489164-eeed-4016-a86d-8df54a004c75%7D&action=editnew

Kan si ifra til meg når listen er klar.

**Comment by geiralund** [comment]
@Eivind833 Lagt til 3 stykk

**Comment by EivindRoyrvik** [comment]
Gjennomgått listen, alt ok.
