### ISSUE TITLE
Journalføring topic fra Joark flyttet til Aiven

### ISSUE THREAD

**Issue by geiralund** [navikt/dagpenger#948]
Kafka topicet fra Joark er flyttet til Aiven. Det gjør at vi kan kvitte oss med applikasjonen som flytter topicet fra onprem til aiven (dagpenger joark mottak) og la innløpet (dp-mottak) lytte direkte til joark topic på Aiven.

**Comment by gtcno** [comment]
Appen kan vel også flyttes til GCP nå?
