### ISSUE TITLE
Spørsmål fra Stortinget  - 152 2021

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#953]
Opprettet sak til Arena-leverandør, se https://jira.adeo.no/browse/ARENA-6435. Se vedlegg og mer detaljert informasjon som ligger på jirasaken.

**Hvor lang utviklingstid vil vi trenge, for å kunne endre slik at alle som har rett til dagpenger med minimum 1,5 G i arbeidsinntekt får 104 uker ?** Kun nye tilfeller.

- [ ] Ønskelig med tilbakemelding i løpet av fredag 15.10.2021.

**Comment by magnefjeld** [comment]
@Elinvethe ivaretar du denne?

**Comment by Elinvethe** [comment]
Vi svarer i JIrasaken og lukker denne @magnefjeld . T..i @geiralund
