### ISSUE TITLE
Registreringsløsningen nede søndag 17. oktober 2021 klokken 0700 til 1600 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#954]
![image](https://user-images.githubusercontent.com/82581338/137491245-63c16c74-3c73-47a9-9085-bd0f096cdc71.png)

Listen kan legges her: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7Bcc510a8d-ede7-46e1-9498-15154bbd5dcb%7D&action=editnew

Kan si fra til meg når listen er klar.

**Comment by geiralund** [comment]
26 stykk berørte, la til i excel ark

**Comment by EivindRoyrvik** [comment]
Gjennomgått listen, alt ok.
