### ISSUE TITLE
Registreringsløsninger nede 21. oktober 2021 klokken 2300 til 2330 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#955]
![image](https://user-images.githubusercontent.com/82581338/138283981-f6ac4b79-640c-478a-9ced-900eaea990f4.png)

Listen kan legges her: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7B9244e75f-cafa-4839-bb7b-fe63e8277050%7D&action=editnew

Kan si ifra til meg når klar.

**Comment by geiralund** [comment]
1 stk berørt, la til i excel ark

**Comment by EivindRoyrvik** [comment]
Sak ok.
