### ISSUE TITLE
Registreringsløsningen nede 24. november 2021 klokken 2300 til 02000 - kjøre ut lister på hvem som har søkt

### ISSUE THREAD

**Issue by EivindRoyrvik** [navikt/dagpenger#992]
![image](https://user-images.githubusercontent.com/82581338/143237697-9dbce06a-dd22-4de3-a832-c89f50cce747.png)

Listen kan legges her: https://navno.sharepoint.com/:x:/r/sites/Korona-dagpenger-uttrekk/_layouts/15/Doc.aspx?sourcedoc=%7B4b705741-16b0-4b16-af45-03f5f15d9971%7D&action=editnew

Kan si ifra til meg når uttrekket er gjort.

**Comment by celinetendam** [comment]
Vi har lagt inn i excel arket @Eivind833

**Comment by EivindRoyrvik** [comment]
Gjennomgått listen. Alt ok.
