### ISSUE TITLE
Endringer til 1. januar 2022 - Samlekort for endringer

### ISSUE THREAD

**Issue by magnefjeld** [navikt/dagpenger#999]
Det er flere endringer til 1. januar 2022, som følge av statsbudsjettet og øvrige endringer.

1. https://github.com/navikt/dagpenger/issues/943 
2. ~~https://github.com/navikt/dagpenger/issues/944~~ (utgår - sak lukket)
3. https://github.com/navikt/dagpenger/issues/947 
5. https://github.com/navikt/dagpenger/issues/997

**Comment by Elinvethe** [comment]
Si i fra om dere vil ha en gjennomgang av disse @tonjemjovik , @celinetendam  og @rannveigskjerve
